/**
 * CW29 Sprint 7.5 — Live baseline loader.
 *
 * Reads precomputed scenario results from live-baseline.json (committed).
 * Returns null if file missing or scenario not present → caller falls back
 * to mock-results.ts so the UI never breaks.
 *
 * The JSON is generated by scripts/precompute-scenario-baselines.mjs which
 * hits production /api/v1/classify + /api/v1/calculate with the X-Demo-Request
 * bypass header. Re-run manually when tariffs or engine logic change.
 */

import type { MockResult } from './mock-results';
import baseline from './live-baseline.json';

interface LiveBaselineEntry extends MockResult {
  source?: string;
  capturedAt?: string;
  classifyElapsedMs?: number;
  calculateElapsedMs?: number;
}

interface LiveBaselineFile {
  generatedAt: string;
  source: string;
  scenarios: Record<string, LiveBaselineEntry>;
}

const typed = baseline as unknown as LiveBaselineFile;

/**
 * Return the precomputed live result for a scenario, or null if not present
 * (→ caller should fall back to mock-results).
 */
export function getLiveBaseline(scenarioId: string): MockResult | null {
  const entry = typed.scenarios?.[scenarioId];
  if (!entry) return null;

  // Defensive: ensure required landedCost fields are finite numbers.
  const lc = entry.landedCost;
  if (
    !lc ||
    !Number.isFinite(lc.productValue) ||
    !Number.isFinite(lc.total)
  ) {
    return null;
  }

  return {
    scenarioId: entry.scenarioId,
    hsCode: entry.hsCode,
    hsDescription: entry.hsDescription,
    landedCost: lc,
    restriction: entry.restriction,
    extras: entry.extras,
    notes: entry.notes || [],
  };
}

export function getBaselineMetadata(): { generatedAt: string; source: string } {
  return {
    generatedAt: typed.generatedAt,
    source: typed.source,
  };
}
