/**
 * Playground — Dropdown option lists for select params.
 * CW34: Country (40), Category (16), Currency (20).
 */

export const COUNTRY_OPTIONS = [
  { value: 'US', label: '🇺🇸 United States (US)' },
  { value: 'GB', label: '🇬🇧 United Kingdom (GB)' },
  { value: 'DE', label: '🇩🇪 Germany (DE)' },
  { value: 'FR', label: '🇫🇷 France (FR)' },
  { value: 'JP', label: '🇯🇵 Japan (JP)' },
  { value: 'KR', label: '🇰🇷 South Korea (KR)' },
  { value: 'CN', label: '🇨🇳 China (CN)' },
  { value: 'IN', label: '🇮🇳 India (IN)' },
  { value: 'BR', label: '🇧🇷 Brazil (BR)' },
  { value: 'CA', label: '🇨🇦 Canada (CA)' },
  { value: 'AU', label: '🇦🇺 Australia (AU)' },
  { value: 'MX', label: '🇲🇽 Mexico (MX)' },
  { value: 'IT', label: '🇮🇹 Italy (IT)' },
  { value: 'ES', label: '🇪🇸 Spain (ES)' },
  { value: 'NL', label: '🇳🇱 Netherlands (NL)' },
  { value: 'SE', label: '🇸🇪 Sweden (SE)' },
  { value: 'CH', label: '🇨🇭 Switzerland (CH)' },
  { value: 'SG', label: '🇸🇬 Singapore (SG)' },
  { value: 'HK', label: '🇭🇰 Hong Kong (HK)' },
  { value: 'TW', label: '🇹🇼 Taiwan (TW)' },
  { value: 'TH', label: '🇹🇭 Thailand (TH)' },
  { value: 'VN', label: '🇻🇳 Vietnam (VN)' },
  { value: 'MY', label: '🇲🇾 Malaysia (MY)' },
  { value: 'ID', label: '🇮🇩 Indonesia (ID)' },
  { value: 'PH', label: '🇵🇭 Philippines (PH)' },
  { value: 'AE', label: '🇦🇪 UAE (AE)' },
  { value: 'SA', label: '🇸🇦 Saudi Arabia (SA)' },
  { value: 'TR', label: '🇹🇷 Turkey (TR)' },
  { value: 'ZA', label: '🇿🇦 South Africa (ZA)' },
  { value: 'NG', label: '🇳🇬 Nigeria (NG)' },
  { value: 'EG', label: '🇪🇬 Egypt (EG)' },
  { value: 'IL', label: '🇮🇱 Israel (IL)' },
  { value: 'NZ', label: '🇳🇿 New Zealand (NZ)' },
  { value: 'AT', label: '🇦🇹 Austria (AT)' },
  { value: 'BE', label: '🇧🇪 Belgium (BE)' },
  { value: 'DK', label: '🇩🇰 Denmark (DK)' },
  { value: 'NO', label: '🇳🇴 Norway (NO)' },
  { value: 'FI', label: '🇫🇮 Finland (FI)' },
  { value: 'PL', label: '🇵🇱 Poland (PL)' },
  { value: 'CZ', label: '🇨🇿 Czechia (CZ)' },
];

export const CATEGORY_OPTIONS = [
  { value: 'apparel-knit', label: 'Apparel — Knit (T-shirts, sweaters)' },
  { value: 'apparel-woven', label: 'Apparel — Woven (shirts, trousers)' },
  { value: 'leather-goods', label: 'Leather Goods (bags, wallets)' },
  { value: 'footwear', label: 'Footwear (shoes, boots)' },
  { value: 'electronics-battery', label: 'Batteries & Cells' },
  { value: 'electronics-consumer', label: 'Consumer Electronics' },
  { value: 'machinery-pumps', label: 'Machinery — Pumps' },
  { value: 'machinery-industrial', label: 'Machinery — Industrial' },
  { value: 'chemicals', label: 'Chemicals / Industrial' },
  { value: 'food-beverage', label: 'Food & Beverage' },
  { value: 'cosmetics', label: 'Cosmetics / Personal Care' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'automotive-parts', label: 'Automotive Parts' },
  { value: 'textiles-raw', label: 'Textiles — Raw Materials' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'other', label: 'Other' },
];

export const CURRENCY_OPTIONS = [
  { value: 'USD', label: '🇺🇸 USD — US Dollar' },
  { value: 'EUR', label: '🇪🇺 EUR — Euro' },
  { value: 'GBP', label: '🇬🇧 GBP — British Pound' },
  { value: 'JPY', label: '🇯🇵 JPY — Japanese Yen' },
  { value: 'KRW', label: '🇰🇷 KRW — Korean Won' },
  { value: 'CNY', label: '🇨🇳 CNY — Chinese Yuan' },
  { value: 'CAD', label: '🇨🇦 CAD — Canadian Dollar' },
  { value: 'AUD', label: '🇦🇺 AUD — Australian Dollar' },
  { value: 'CHF', label: '🇨🇭 CHF — Swiss Franc' },
  { value: 'HKD', label: '🇭🇰 HKD — Hong Kong Dollar' },
  { value: 'SGD', label: '🇸🇬 SGD — Singapore Dollar' },
  { value: 'TWD', label: '🇹🇼 TWD — Taiwan Dollar' },
  { value: 'THB', label: '🇹🇭 THB — Thai Baht' },
  { value: 'VND', label: '🇻🇳 VND — Vietnamese Dong' },
  { value: 'MYR', label: '🇲🇾 MYR — Malaysian Ringgit' },
  { value: 'INR', label: '🇮🇳 INR — Indian Rupee' },
  { value: 'BRL', label: '🇧🇷 BRL — Brazilian Real' },
  { value: 'MXN', label: '🇲🇽 MXN — Mexican Peso' },
  { value: 'ZAR', label: '🇿🇦 ZAR — South African Rand' },
  { value: 'AED', label: '🇦🇪 AED — UAE Dirham' },
];
