/**
 * Playground — Dropdown option lists for select params.
 * CW34: Country (240, with Popular group), Category (16), Currency (20).
 */

export const POPULAR_COUNTRIES = ["US","GB","DE","CN","JP","KR","FR","CA","AU","IN"];

export const COUNTRY_OPTIONS: Array<{ value: string; label: string; group?: string }> = [
  // Popular
  { value: "US", label: "🇺🇸 United States (US)", group: "popular" },
  { value: "GB", label: "🇬🇧 United Kingdom (GB)", group: "popular" },
  { value: "DE", label: "🇩🇪 Germany (DE)", group: "popular" },
  { value: "CN", label: "🇨🇳 China (CN)", group: "popular" },
  { value: "JP", label: "🇯🇵 Japan (JP)", group: "popular" },
  { value: "KR", label: "🇰🇷 South Korea (KR)", group: "popular" },
  { value: "FR", label: "🇫🇷 France (FR)", group: "popular" },
  { value: "CA", label: "🇨🇦 Canada (CA)", group: "popular" },
  { value: "AU", label: "🇦🇺 Australia (AU)", group: "popular" },
  { value: "IN", label: "🇮🇳 India (IN)", group: "popular" },
  // All Countries (alphabetical)
  { value: "AF", label: "🇦🇫 Afghanistan (AF)" },
  { value: "AL", label: "🇦🇱 Albania (AL)" },
  { value: "DZ", label: "🇩🇿 Algeria (DZ)" },
  { value: "AS", label: "🇦🇸 American Samoa (AS)" },
  { value: "AD", label: "🇦🇩 Andorra (AD)" },
  { value: "AO", label: "🇦🇴 Angola (AO)" },
  { value: "AI", label: "🇦🇮 Anguilla (AI)" },
  { value: "AG", label: "🇦🇬 Antigua and Barbuda (AG)" },
  { value: "AR", label: "🇦🇷 Argentina (AR)" },
  { value: "AM", label: "🇦🇲 Armenia (AM)" },
  { value: "AW", label: "🇦🇼 Aruba (AW)" },
  { value: "AU", label: "🇦🇺 Australia (AU)" },
  { value: "AT", label: "🇦🇹 Austria (AT)" },
  { value: "AZ", label: "🇦🇿 Azerbaijan (AZ)" },
  { value: "BS", label: "🇧🇸 Bahamas (BS)" },
  { value: "BH", label: "🇧🇭 Bahrain (BH)" },
  { value: "BD", label: "🇧🇩 Bangladesh (BD)" },
  { value: "BB", label: "🇧🇧 Barbados (BB)" },
  { value: "BY", label: "🇧🇾 Belarus (BY)" },
  { value: "BE", label: "🇧🇪 Belgium (BE)" },
  { value: "BZ", label: "🇧🇿 Belize (BZ)" },
  { value: "BJ", label: "🇧🇯 Benin (BJ)" },
  { value: "BM", label: "🇧🇲 Bermuda (BM)" },
  { value: "BT", label: "🇧🇹 Bhutan (BT)" },
  { value: "BO", label: "🇧🇴 Bolivia (BO)" },
  { value: "BQ", label: "🇧🇶 Bonaire, Sint Eustatius and Saba (BQ)" },
  { value: "BA", label: "🇧🇦 Bosnia (BA)" },
  { value: "BW", label: "🇧🇼 Botswana (BW)" },
  { value: "BR", label: "🇧🇷 Brazil (BR)" },
  { value: "IO", label: "🇮🇴 British Indian Ocean Territory (IO)" },
  { value: "VG", label: "🇻🇬 British Virgin Islands (VG)" },
  { value: "BN", label: "🇧🇳 Brunei (BN)" },
  { value: "BG", label: "🇧🇬 Bulgaria (BG)" },
  { value: "BF", label: "🇧🇫 Burkina Faso (BF)" },
  { value: "BI", label: "🇧🇮 Burundi (BI)" },
  { value: "KH", label: "🇰🇭 Cambodia (KH)" },
  { value: "CM", label: "🇨🇲 Cameroon (CM)" },
  { value: "CA", label: "🇨🇦 Canada (CA)" },
  { value: "CV", label: "🇨🇻 Cape Verde (CV)" },
  { value: "KY", label: "🇰🇾 Cayman Islands (KY)" },
  { value: "CF", label: "🇨🇫 Central African Republic (CF)" },
  { value: "TD", label: "🇹🇩 Chad (TD)" },
  { value: "CL", label: "🇨🇱 Chile (CL)" },
  { value: "CN", label: "🇨🇳 China (CN)" },
  { value: "CX", label: "🇨🇽 Christmas Island (CX)" },
  { value: "CC", label: "🇨🇨 Cocos (Keeling) Islands (CC)" },
  { value: "CO", label: "🇨🇴 Colombia (CO)" },
  { value: "KM", label: "🇰🇲 Comoros (KM)" },
  { value: "CK", label: "🇨🇰 Cook Islands (CK)" },
  { value: "CR", label: "🇨🇷 Costa Rica (CR)" },
  { value: "HR", label: "🇭🇷 Croatia (HR)" },
  { value: "CU", label: "🇨🇺 Cuba (CU)" },
  { value: "CW", label: "🇨🇼 Curaçao (CW)" },
  { value: "CY", label: "🇨🇾 Cyprus (CY)" },
  { value: "CZ", label: "🇨🇿 Czech Republic (CZ)" },
  { value: "DK", label: "🇩🇰 Denmark (DK)" },
  { value: "DJ", label: "🇩🇯 Djibouti (DJ)" },
  { value: "DM", label: "🇩🇲 Dominica (DM)" },
  { value: "DO", label: "🇩🇴 Dominican Republic (DO)" },
  { value: "CD", label: "🇨🇩 DR Congo (CD)" },
  { value: "EC", label: "🇪🇨 Ecuador (EC)" },
  { value: "EG", label: "🇪🇬 Egypt (EG)" },
  { value: "SV", label: "🇸🇻 El Salvador (SV)" },
  { value: "GQ", label: "🇬🇶 Equatorial Guinea (GQ)" },
  { value: "ER", label: "🇪🇷 Eritrea (ER)" },
  { value: "EE", label: "🇪🇪 Estonia (EE)" },
  { value: "SZ", label: "🇸🇿 Eswatini (SZ)" },
  { value: "ET", label: "🇪🇹 Ethiopia (ET)" },
  { value: "FK", label: "🇫🇰 Falkland Islands (FK)" },
  { value: "FO", label: "🇫🇴 Faroe Islands (FO)" },
  { value: "FJ", label: "🇫🇯 Fiji (FJ)" },
  { value: "FI", label: "🇫🇮 Finland (FI)" },
  { value: "FR", label: "🇫🇷 France (FR)" },
  { value: "GF", label: "🇬🇫 French Guiana (GF)" },
  { value: "PF", label: "🇵🇫 French Polynesia (PF)" },
  { value: "GA", label: "🇬🇦 Gabon (GA)" },
  { value: "GM", label: "🇬🇲 Gambia (GM)" },
  { value: "GE", label: "🇬🇪 Georgia (GE)" },
  { value: "DE", label: "🇩🇪 Germany (DE)" },
  { value: "GH", label: "🇬🇭 Ghana (GH)" },
  { value: "GI", label: "🇬🇮 Gibraltar (GI)" },
  { value: "GR", label: "🇬🇷 Greece (GR)" },
  { value: "GL", label: "🇬🇱 Greenland (GL)" },
  { value: "GD", label: "🇬🇩 Grenada (GD)" },
  { value: "GP", label: "🇬🇵 Guadeloupe (GP)" },
  { value: "GU", label: "🇬🇺 Guam (GU)" },
  { value: "GT", label: "🇬🇹 Guatemala (GT)" },
  { value: "GG", label: "🇬🇬 Guernsey (GG)" },
  { value: "GN", label: "🇬🇳 Guinea (GN)" },
  { value: "GW", label: "🇬🇼 Guinea-Bissau (GW)" },
  { value: "GY", label: "🇬🇾 Guyana (GY)" },
  { value: "HT", label: "🇭🇹 Haiti (HT)" },
  { value: "HN", label: "🇭🇳 Honduras (HN)" },
  { value: "HK", label: "🇭🇰 Hong Kong (HK)" },
  { value: "HU", label: "🇭🇺 Hungary (HU)" },
  { value: "IS", label: "🇮🇸 Iceland (IS)" },
  { value: "IN", label: "🇮🇳 India (IN)" },
  { value: "ID", label: "🇮🇩 Indonesia (ID)" },
  { value: "IR", label: "🇮🇷 Iran (IR)" },
  { value: "IQ", label: "🇮🇶 Iraq (IQ)" },
  { value: "IE", label: "🇮🇪 Ireland (IE)" },
  { value: "IM", label: "🇮🇲 Isle of Man (IM)" },
  { value: "IL", label: "🇮🇱 Israel (IL)" },
  { value: "IT", label: "🇮🇹 Italy (IT)" },
  { value: "CI", label: "🇨🇮 Ivory Coast (CI)" },
  { value: "JM", label: "🇯🇲 Jamaica (JM)" },
  { value: "JP", label: "🇯🇵 Japan (JP)" },
  { value: "JE", label: "🇯🇪 Jersey (JE)" },
  { value: "JO", label: "🇯🇴 Jordan (JO)" },
  { value: "KZ", label: "🇰🇿 Kazakhstan (KZ)" },
  { value: "KE", label: "🇰🇪 Kenya (KE)" },
  { value: "KI", label: "🇰🇮 Kiribati (KI)" },
  { value: "XK", label: "🇽🇰 Kosovo (XK)" },
  { value: "KW", label: "🇰🇼 Kuwait (KW)" },
  { value: "KG", label: "🇰🇬 Kyrgyzstan (KG)" },
  { value: "AX", label: "🇦🇽 Åland Islands (AX)" },
  { value: "LA", label: "🇱🇦 Laos (LA)" },
  { value: "LV", label: "🇱🇻 Latvia (LV)" },
  { value: "LB", label: "🇱🇧 Lebanon (LB)" },
  { value: "LS", label: "🇱🇸 Lesotho (LS)" },
  { value: "LR", label: "🇱🇷 Liberia (LR)" },
  { value: "LY", label: "🇱🇾 Libya (LY)" },
  { value: "LI", label: "🇱🇮 Liechtenstein (LI)" },
  { value: "LT", label: "🇱🇹 Lithuania (LT)" },
  { value: "LU", label: "🇱🇺 Luxembourg (LU)" },
  { value: "MO", label: "🇲🇴 Macau (MO)" },
  { value: "MG", label: "🇲🇬 Madagascar (MG)" },
  { value: "MW", label: "🇲🇼 Malawi (MW)" },
  { value: "MY", label: "🇲🇾 Malaysia (MY)" },
  { value: "MV", label: "🇲🇻 Maldives (MV)" },
  { value: "ML", label: "🇲🇱 Mali (ML)" },
  { value: "MT", label: "🇲🇹 Malta (MT)" },
  { value: "MH", label: "🇲🇭 Marshall Islands (MH)" },
  { value: "MQ", label: "🇲🇶 Martinique (MQ)" },
  { value: "MR", label: "🇲🇷 Mauritania (MR)" },
  { value: "MU", label: "🇲🇺 Mauritius (MU)" },
  { value: "YT", label: "🇾🇹 Mayotte (YT)" },
  { value: "MX", label: "🇲🇽 Mexico (MX)" },
  { value: "FM", label: "🇫🇲 Micronesia (FM)" },
  { value: "MD", label: "🇲🇩 Moldova (MD)" },
  { value: "MC", label: "🇲🇨 Monaco (MC)" },
  { value: "MN", label: "🇲🇳 Mongolia (MN)" },
  { value: "ME", label: "🇲🇪 Montenegro (ME)" },
  { value: "MS", label: "🇲🇸 Montserrat (MS)" },
  { value: "MA", label: "🇲🇦 Morocco (MA)" },
  { value: "MZ", label: "🇲🇿 Mozambique (MZ)" },
  { value: "MM", label: "🇲🇲 Myanmar (MM)" },
  { value: "NA", label: "🇳🇦 Namibia (NA)" },
  { value: "NR", label: "🇳🇷 Nauru (NR)" },
  { value: "NP", label: "🇳🇵 Nepal (NP)" },
  { value: "NL", label: "🇳🇱 Netherlands (NL)" },
  { value: "NC", label: "🇳🇨 New Caledonia (NC)" },
  { value: "NZ", label: "🇳🇿 New Zealand (NZ)" },
  { value: "NI", label: "🇳🇮 Nicaragua (NI)" },
  { value: "NE", label: "🇳🇪 Niger (NE)" },
  { value: "NG", label: "🇳🇬 Nigeria (NG)" },
  { value: "NU", label: "🇳🇺 Niue (NU)" },
  { value: "NF", label: "🇳🇫 Norfolk Island (NF)" },
  { value: "KP", label: "🇰🇵 North Korea (KP)" },
  { value: "MK", label: "🇲🇰 North Macedonia (MK)" },
  { value: "MP", label: "🇲🇵 Northern Mariana Islands (MP)" },
  { value: "NO", label: "🇳🇴 Norway (NO)" },
  { value: "OM", label: "🇴🇲 Oman (OM)" },
  { value: "PK", label: "🇵🇰 Pakistan (PK)" },
  { value: "PW", label: "🇵🇼 Palau (PW)" },
  { value: "PS", label: "🇵🇸 Palestine (PS)" },
  { value: "PA", label: "🇵🇦 Panama (PA)" },
  { value: "PG", label: "🇵🇬 Papua New Guinea (PG)" },
  { value: "PY", label: "🇵🇾 Paraguay (PY)" },
  { value: "PE", label: "🇵🇪 Peru (PE)" },
  { value: "PH", label: "🇵🇭 Philippines (PH)" },
  { value: "PL", label: "🇵🇱 Poland (PL)" },
  { value: "PT", label: "🇵🇹 Portugal (PT)" },
  { value: "PR", label: "🇵🇷 Puerto Rico (PR)" },
  { value: "QA", label: "🇶🇦 Qatar (QA)" },
  { value: "CG", label: "🇨🇬 Republic of Congo (CG)" },
  { value: "RO", label: "🇷🇴 Romania (RO)" },
  { value: "RE", label: "🇷🇪 Réunion (RE)" },
  { value: "RW", label: "🇷🇼 Rwanda (RW)" },
  { value: "BL", label: "🇧🇱 Saint Barthélemy (BL)" },
  { value: "SH", label: "🇸🇭 Saint Helena (SH)" },
  { value: "KN", label: "🇰🇳 Saint Kitts and Nevis (KN)" },
  { value: "LC", label: "🇱🇨 Saint Lucia (LC)" },
  { value: "MF", label: "🇲🇫 Saint Martin (French) (MF)" },
  { value: "PM", label: "🇵🇲 Saint Pierre and Miquelon (PM)" },
  { value: "VC", label: "🇻🇨 Saint Vincent and the Grenadines (VC)" },
  { value: "WS", label: "🇼🇸 Samoa (WS)" },
  { value: "SM", label: "🇸🇲 San Marino (SM)" },
  { value: "SA", label: "🇸🇦 Saudi Arabia (SA)" },
  { value: "SN", label: "🇸🇳 Senegal (SN)" },
  { value: "RS", label: "🇷🇸 Serbia (RS)" },
  { value: "SC", label: "🇸🇨 Seychelles (SC)" },
  { value: "SL", label: "🇸🇱 Sierra Leone (SL)" },
  { value: "SG", label: "🇸🇬 Singapore (SG)" },
  { value: "SX", label: "🇸🇽 Sint Maarten (SX)" },
  { value: "SK", label: "🇸🇰 Slovakia (SK)" },
  { value: "SI", label: "🇸🇮 Slovenia (SI)" },
  { value: "ST", label: "🇸🇹 São Tomé and Príncipe (ST)" },
  { value: "SB", label: "🇸🇧 Solomon Islands (SB)" },
  { value: "SO", label: "🇸🇴 Somalia (SO)" },
  { value: "ZA", label: "🇿🇦 South Africa (ZA)" },
  { value: "KR", label: "🇰🇷 South Korea (KR)" },
  { value: "SS", label: "🇸🇸 South Sudan (SS)" },
  { value: "ES", label: "🇪🇸 Spain (ES)" },
  { value: "LK", label: "🇱🇰 Sri Lanka (LK)" },
  { value: "SD", label: "🇸🇩 Sudan (SD)" },
  { value: "SR", label: "🇸🇷 Suriname (SR)" },
  { value: "SJ", label: "🇸🇯 Svalbard and Jan Mayen (SJ)" },
  { value: "SE", label: "🇸🇪 Sweden (SE)" },
  { value: "CH", label: "🇨🇭 Switzerland (CH)" },
  { value: "SY", label: "🇸🇾 Syria (SY)" },
  { value: "TW", label: "🇹🇼 Taiwan (TW)" },
  { value: "TJ", label: "🇹🇯 Tajikistan (TJ)" },
  { value: "TZ", label: "🇹🇿 Tanzania (TZ)" },
  { value: "TH", label: "🇹🇭 Thailand (TH)" },
  { value: "TL", label: "🇹🇱 Timor-Leste (TL)" },
  { value: "TG", label: "🇹🇬 Togo (TG)" },
  { value: "TK", label: "🇹🇰 Tokelau (TK)" },
  { value: "TO", label: "🇹🇴 Tonga (TO)" },
  { value: "TT", label: "🇹🇹 Trinidad (TT)" },
  { value: "TN", label: "🇹🇳 Tunisia (TN)" },
  { value: "TR", label: "🇹🇷 Turkey (TR)" },
  { value: "TM", label: "🇹🇲 Turkmenistan (TM)" },
  { value: "TC", label: "🇹🇨 Turks and Caicos Islands (TC)" },
  { value: "TV", label: "🇹🇻 Tuvalu (TV)" },
  { value: "UG", label: "🇺🇬 Uganda (UG)" },
  { value: "UA", label: "🇺🇦 Ukraine (UA)" },
  { value: "AE", label: "🇦🇪 United Arab Emirates (AE)" },
  { value: "GB", label: "🇬🇧 United Kingdom (GB)" },
  { value: "US", label: "🇺🇸 United States (US)" },
  { value: "UY", label: "🇺🇾 Uruguay (UY)" },
  { value: "VI", label: "🇻🇮 US Virgin Islands (VI)" },
  { value: "UZ", label: "🇺🇿 Uzbekistan (UZ)" },
  { value: "VU", label: "🇻🇺 Vanuatu (VU)" },
  { value: "VE", label: "🇻🇪 Venezuela (VE)" },
  { value: "VN", label: "🇻🇳 Vietnam (VN)" },
  { value: "WF", label: "🇼🇫 Wallis and Futuna (WF)" },
  { value: "YE", label: "🇾🇪 Yemen (YE)" },
  { value: "ZM", label: "🇿🇲 Zambia (ZM)" },
  { value: "ZW", label: "🇿🇼 Zimbabwe (ZW)" },
];
// CW34: Full 67 categories from HS database chapters (alphabetical)
export const CATEGORY_OPTIONS = [
  { value: 'accessories', label: 'Accessories' },
  { value: 'aircraft', label: 'Aircraft' },
  { value: 'aluminum', label: 'Aluminum Products' },
  { value: 'animals', label: 'Animals (live)' },
  { value: 'apparel', label: 'Apparel (general)' },
  { value: 'apparel-knit', label: 'Apparel — Knit (T-shirts, sweaters)' },
  { value: 'apparel-woven', label: 'Apparel — Woven (shirts, trousers)' },
  { value: 'appliances', label: 'Appliances' },
  { value: 'arms', label: 'Arms & Ammunition' },
  { value: 'art', label: 'Art & Antiques' },
  { value: 'automotive-parts', label: 'Automotive Parts' },
  { value: 'baby', label: 'Baby Products' },
  { value: 'bags', label: 'Bags & Luggage' },
  { value: 'beauty', label: 'Beauty' },
  { value: 'beverages', label: 'Beverages' },
  { value: 'books', label: 'Books & Printed Matter' },
  { value: 'ceramics', label: 'Ceramics' },
  { value: 'chemicals', label: 'Chemicals / Industrial' },
  { value: 'cleaning', label: 'Cleaning Products' },
  { value: 'collectibles', label: 'Collectibles' },
  { value: 'copper', label: 'Copper Products' },
  { value: 'cork', label: 'Cork Products' },
  { value: 'cosmetics', label: 'Cosmetics / Personal Care' },
  { value: 'craft', label: 'Craft Supplies' },
  { value: 'electronics', label: 'Electronics (general)' },
  { value: 'electronics-battery', label: 'Batteries & Cells' },
  { value: 'electronics-consumer', label: 'Consumer Electronics' },
  { value: 'food', label: 'Food' },
  { value: 'food-beverage', label: 'Food & Beverage' },
  { value: 'footwear', label: 'Footwear (shoes, boots)' },
  { value: 'fuels', label: 'Fuels & Mineral Oils' },
  { value: 'fur', label: 'Fur & Furskins' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'garden', label: 'Garden' },
  { value: 'glass', label: 'Glass Products' },
  { value: 'headwear', label: 'Headwear (hats, caps)' },
  { value: 'health', label: 'Health' },
  { value: 'home', label: 'Home' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'instruments', label: 'Instruments (scientific, medical)' },
  { value: 'jewelry', label: 'Jewelry' },
  { value: 'lead', label: 'Lead Products' },
  { value: 'leather-goods', label: 'Leather Goods (bags, wallets)' },
  { value: 'machinery-industrial', label: 'Machinery — Industrial' },
  { value: 'machinery-pumps', label: 'Machinery — Pumps' },
  { value: 'metals', label: 'Metals (general)' },
  { value: 'minerals', label: 'Minerals' },
  { value: 'misc', label: 'Miscellaneous' },
  { value: 'music', label: 'Musical Instruments' },
  { value: 'nickel', label: 'Nickel Products' },
  { value: 'office', label: 'Office Supplies' },
  { value: 'paper', label: 'Paper & Paperboard' },
  { value: 'pet', label: 'Pet Products' },
  { value: 'pharmaceuticals', label: 'Pharmaceuticals' },
  { value: 'photographic', label: 'Photographic Equipment' },
  { value: 'plants', label: 'Plants & Flowers' },
  { value: 'plastics', label: 'Plastics' },
  { value: 'rubber', label: 'Rubber Products' },
  { value: 'ships', label: 'Ships & Boats' },
  { value: 'sports', label: 'Sports' },
  { value: 'stationery', label: 'Stationery' },
  { value: 'steel', label: 'Steel Products' },
  { value: 'stone', label: 'Stone Products' },
  { value: 'straw', label: 'Straw & Basketwork' },
  { value: 'textiles-raw', label: 'Textiles — Raw Materials' },
  { value: 'tin', label: 'Tin Products' },
  { value: 'tobacco', label: 'Tobacco' },
  { value: 'tools', label: 'Tools' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'vehicles', label: 'Vehicles' },
  { value: 'watches', label: 'Watches & Clocks' },
  { value: 'wood', label: 'Wood Products' },
  { value: 'zinc', label: 'Zinc Products' },
];

export const CURRENCY_OPTIONS = [
  { value: "USD", label: "🇺🇸 USD — US Dollar" },
  { value: "EUR", label: "🇪🇺 EUR — Euro" },
  { value: "GBP", label: "🇬🇧 GBP — British Pound" },
  { value: "JPY", label: "🇯🇵 JPY — Japanese Yen" },
  { value: "KRW", label: "🇰🇷 KRW — Korean Won" },
  { value: "CNY", label: "🇨🇳 CNY — Chinese Yuan" },
  { value: "CAD", label: "🇨🇦 CAD — Canadian Dollar" },
  { value: "AUD", label: "🇦🇺 AUD — Australian Dollar" },
  { value: "CHF", label: "🇨🇭 CHF — Swiss Franc" },
  { value: "HKD", label: "🇭🇰 HKD — Hong Kong Dollar" },
  { value: "SGD", label: "🇸🇬 SGD — Singapore Dollar" },
  { value: "TWD", label: "🇹🇼 TWD — Taiwan Dollar" },
  { value: "THB", label: "🇹🇭 THB — Thai Baht" },
  { value: "VND", label: "🇻🇳 VND — Vietnamese Dong" },
  { value: "MYR", label: "🇲🇾 MYR — Malaysian Ringgit" },
  { value: "INR", label: "🇮🇳 INR — Indian Rupee" },
  { value: "BRL", label: "🇧🇷 BRL — Brazilian Real" },
  { value: "MXN", label: "🇲🇽 MXN — Mexican Peso" },
  { value: "ZAR", label: "🇿🇦 ZAR — South African Rand" },
  { value: "AED", label: "🇦🇪 AED — UAE Dirham" },
];

// CW34: All engine-codified materials (82 total), grouped by HS chapter alignment
export const MATERIAL_OPTIONS: Array<{ value: string; label: string; group?: string }> = [
  // --- Textiles (28) ---
  { value: 'cotton', label: 'Cotton', group: 'Textiles' },
  { value: 'polyester', label: 'Polyester', group: 'Textiles' },
  { value: 'nylon', label: 'Nylon', group: 'Textiles' },
  { value: 'silk', label: 'Silk', group: 'Textiles' },
  { value: 'wool', label: 'Wool', group: 'Textiles' },
  { value: 'merino', label: 'Merino Wool', group: 'Textiles' },
  { value: 'cashmere', label: 'Cashmere', group: 'Textiles' },
  { value: 'alpaca', label: 'Alpaca', group: 'Textiles' },
  { value: 'mohair', label: 'Mohair', group: 'Textiles' },
  { value: 'angora', label: 'Angora', group: 'Textiles' },
  { value: 'linen', label: 'Linen', group: 'Textiles' },
  { value: 'rayon', label: 'Rayon', group: 'Textiles' },
  { value: 'viscose', label: 'Viscose', group: 'Textiles' },
  { value: 'modal', label: 'Modal', group: 'Textiles' },
  { value: 'acrylic', label: 'Acrylic', group: 'Textiles' },
  { value: 'spandex', label: 'Spandex / Elastane', group: 'Textiles' },
  { value: 'lycra', label: 'Lycra', group: 'Textiles' },
  { value: 'canvas', label: 'Canvas', group: 'Textiles' },
  { value: 'denim', label: 'Denim', group: 'Textiles' },
  { value: 'velvet', label: 'Velvet', group: 'Textiles' },
  { value: 'satin', label: 'Satin', group: 'Textiles' },
  { value: 'chiffon', label: 'Chiffon', group: 'Textiles' },
  { value: 'lace', label: 'Lace', group: 'Textiles' },
  { value: 'synthetic', label: 'Synthetic (general)', group: 'Textiles' },
  { value: 'natural', label: 'Natural fiber (general)', group: 'Textiles' },
  // --- Leather (7) ---
  { value: 'leather', label: 'Leather (general)', group: 'Leather' },
  { value: 'suede', label: 'Suede', group: 'Leather' },
  { value: 'nubuck', label: 'Nubuck', group: 'Leather' },
  { value: 'calfskin', label: 'Calfskin', group: 'Leather' },
  { value: 'lambskin', label: 'Lambskin', group: 'Leather' },
  { value: 'cowhide', label: 'Cowhide', group: 'Leather' },
  { value: 'pigskin', label: 'Pigskin', group: 'Leather' },
  { value: 'synthetic-leather', label: 'Synthetic Leather (PU/PVC)', group: 'Leather' },
  // --- Metals (13) ---
  { value: 'steel', label: 'Steel', group: 'Metals' },
  { value: 'stainless-steel', label: 'Stainless Steel', group: 'Metals' },
  { value: 'aluminum', label: 'Aluminum', group: 'Metals' },
  { value: 'copper', label: 'Copper', group: 'Metals' },
  { value: 'iron', label: 'Iron / Cast Iron', group: 'Metals' },
  { value: 'nickel', label: 'Nickel', group: 'Metals' },
  { value: 'titanium', label: 'Titanium', group: 'Metals' },
  { value: 'lead', label: 'Lead', group: 'Metals' },
  { value: 'tin', label: 'Tin', group: 'Metals' },
  { value: 'zinc', label: 'Zinc', group: 'Metals' },
  { value: 'gold', label: 'Gold', group: 'Metals' },
  { value: 'silver', label: 'Silver', group: 'Metals' },
  { value: 'platinum', label: 'Platinum', group: 'Metals' },
  // --- Rubber & Plastics (5) ---
  { value: 'rubber', label: 'Rubber', group: 'Rubber & Plastics' },
  { value: 'plastic', label: 'Plastic', group: 'Rubber & Plastics' },
  { value: 'pvc', label: 'PVC', group: 'Rubber & Plastics' },
  { value: 'eva', label: 'EVA (Ethylene-Vinyl Acetate)', group: 'Rubber & Plastics' },
  { value: 'silicone', label: 'Silicone', group: 'Rubber & Plastics' },
  // --- Wood & Natural (12) ---
  { value: 'wood', label: 'Wood (general)', group: 'Wood & Natural' },
  { value: 'oak', label: 'Oak', group: 'Wood & Natural' },
  { value: 'pine', label: 'Pine', group: 'Wood & Natural' },
  { value: 'walnut', label: 'Walnut', group: 'Wood & Natural' },
  { value: 'maple', label: 'Maple', group: 'Wood & Natural' },
  { value: 'birch', label: 'Birch', group: 'Wood & Natural' },
  { value: 'teak', label: 'Teak', group: 'Wood & Natural' },
  { value: 'mahogany', label: 'Mahogany', group: 'Wood & Natural' },
  { value: 'bamboo', label: 'Bamboo', group: 'Wood & Natural' },
  { value: 'plywood', label: 'Plywood / MDF', group: 'Wood & Natural' },
  { value: 'cork', label: 'Cork', group: 'Wood & Natural' },
  { value: 'rattan', label: 'Rattan', group: 'Wood & Natural' },
  { value: 'paper', label: 'Paper / Cardboard', group: 'Wood & Natural' },
  // --- Stone & Ceramics (7) ---
  { value: 'glass', label: 'Glass', group: 'Stone & Ceramics' },
  { value: 'ceramic', label: 'Ceramic', group: 'Stone & Ceramics' },
  { value: 'porcelain', label: 'Porcelain', group: 'Stone & Ceramics' },
  { value: 'stoneware', label: 'Stoneware', group: 'Stone & Ceramics' },
  { value: 'earthenware', label: 'Earthenware', group: 'Stone & Ceramics' },
  { value: 'crystal', label: 'Crystal', group: 'Stone & Ceramics' },
  { value: 'stone', label: 'Stone / Marble / Granite', group: 'Stone & Ceramics' },
  // --- Specialty (8) ---
  { value: 'lithium-ion', label: 'Lithium-ion (Li-ion)', group: 'Specialty' },
  { value: 'lithium-primary', label: 'Lithium Primary (non-rechargeable)', group: 'Specialty' },
  { value: 'carbon-fiber', label: 'Carbon Fiber', group: 'Specialty' },
  { value: 'diamond', label: 'Diamond', group: 'Specialty' },
  { value: 'ruby', label: 'Ruby', group: 'Specialty' },
  { value: 'sapphire', label: 'Sapphire', group: 'Specialty' },
  { value: 'emerald', label: 'Emerald', group: 'Specialty' },
  { value: 'pearl', label: 'Pearl', group: 'Specialty' },
];

// CW34: Full material → category mapping (82 materials) based on HS chapters
export const MATERIAL_TO_CATEGORIES: Record<string, string[]> = {
  // Textiles
  cotton: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw', 'footwear', 'home'],
  polyester: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw', 'footwear', 'home'],
  nylon: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw', 'footwear', 'bags'],
  silk: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw', 'accessories'],
  wool: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw'],
  merino: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw'],
  cashmere: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw'],
  alpaca: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw'],
  mohair: ['apparel-knit', 'apparel-woven', 'textiles-raw'],
  angora: ['apparel-knit', 'apparel-woven', 'textiles-raw'],
  linen: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw', 'home'],
  rayon: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw'],
  viscose: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw'],
  modal: ['apparel-knit', 'apparel-woven', 'apparel', 'textiles-raw'],
  acrylic: ['apparel-knit', 'apparel-woven', 'textiles-raw'],
  spandex: ['apparel-knit', 'apparel-woven', 'textiles-raw', 'sports'],
  lycra: ['apparel-knit', 'apparel-woven', 'textiles-raw', 'sports'],
  canvas: ['bags', 'footwear', 'apparel-woven', 'textiles-raw'],
  denim: ['apparel-woven', 'apparel', 'bags', 'textiles-raw'],
  velvet: ['apparel-woven', 'apparel', 'home', 'textiles-raw'],
  satin: ['apparel-woven', 'apparel', 'accessories', 'textiles-raw'],
  chiffon: ['apparel-woven', 'apparel', 'textiles-raw'],
  lace: ['apparel-woven', 'apparel', 'textiles-raw', 'accessories'],
  synthetic: ['apparel-knit', 'apparel-woven', 'textiles-raw', 'footwear'],
  natural: ['apparel-knit', 'apparel-woven', 'textiles-raw'],
  // Leather
  leather: ['leather-goods', 'footwear', 'apparel-woven', 'bags', 'accessories'],
  suede: ['leather-goods', 'footwear', 'apparel-woven', 'bags'],
  nubuck: ['leather-goods', 'footwear', 'bags'],
  calfskin: ['leather-goods', 'footwear', 'bags', 'accessories'],
  lambskin: ['leather-goods', 'apparel-woven', 'bags'],
  cowhide: ['leather-goods', 'footwear', 'bags'],
  pigskin: ['leather-goods', 'bags'],
  'synthetic-leather': ['leather-goods', 'footwear', 'apparel-woven', 'bags'],
  // Metals
  steel: ['machinery-pumps', 'machinery-industrial', 'automotive-parts', 'furniture', 'tools', 'steel'],
  'stainless-steel': ['machinery-pumps', 'machinery-industrial', 'automotive-parts', 'furniture', 'tools', 'home'],
  aluminum: ['machinery-industrial', 'automotive-parts', 'furniture', 'electronics-consumer', 'aluminum'],
  copper: ['machinery-industrial', 'electronics', 'copper'],
  iron: ['machinery-pumps', 'machinery-industrial', 'automotive-parts', 'furniture', 'tools'],
  nickel: ['machinery-industrial', 'electronics', 'nickel'],
  titanium: ['machinery-industrial', 'automotive-parts', 'instruments', 'jewelry'],
  lead: ['machinery-industrial', 'electronics', 'lead'],
  tin: ['machinery-industrial', 'tin'],
  zinc: ['machinery-industrial', 'zinc'],
  gold: ['jewelry', 'watches', 'art'],
  silver: ['jewelry', 'watches', 'art'],
  platinum: ['jewelry', 'watches', 'instruments'],
  // Rubber & Plastics
  rubber: ['footwear', 'toys', 'automotive-parts', 'machinery-industrial', 'rubber', 'sports'],
  plastic: ['toys', 'automotive-parts', 'machinery-industrial', 'plastics', 'home', 'baby'],
  pvc: ['plastics', 'footwear', 'home', 'industrial'],
  eva: ['footwear', 'sports', 'plastics'],
  silicone: ['electronics-consumer', 'home', 'baby', 'cosmetics'],
  // Wood & Natural
  wood: ['furniture', 'toys', 'home', 'wood', 'music', 'stationery'],
  oak: ['furniture', 'wood', 'home'],
  pine: ['furniture', 'wood', 'home'],
  walnut: ['furniture', 'wood', 'home', 'music'],
  maple: ['furniture', 'wood', 'music'],
  birch: ['furniture', 'wood', 'home'],
  teak: ['furniture', 'wood', 'garden', 'ships'],
  mahogany: ['furniture', 'wood', 'music'],
  bamboo: ['furniture', 'home', 'wood', 'garden'],
  plywood: ['furniture', 'wood', 'industrial'],
  cork: ['cork', 'beverages', 'home'],
  rattan: ['furniture', 'home', 'straw'],
  paper: ['paper', 'books', 'stationery', 'craft'],
  // Stone & Ceramics
  glass: ['ceramics', 'home', 'glass', 'beverages', 'instruments'],
  ceramic: ['ceramics', 'home', 'furniture'],
  porcelain: ['ceramics', 'home', 'art'],
  stoneware: ['ceramics', 'home'],
  earthenware: ['ceramics', 'home'],
  crystal: ['glass', 'home', 'jewelry'],
  stone: ['stone', 'furniture', 'art'],
  // Specialty
  'lithium-ion': ['electronics-battery', 'electronics-consumer', 'electronics'],
  'lithium-primary': ['electronics-battery', 'electronics-consumer', 'electronics'],
  'carbon-fiber': ['automotive-parts', 'machinery-industrial', 'sports'],
  diamond: ['jewelry'],
  ruby: ['jewelry'],
  sapphire: ['jewelry'],
  emerald: ['jewelry'],
  pearl: ['jewelry', 'accessories'],
};
