# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2fa34ed65342ffb7fac08dd916f470b8"
name = "POTAL"
application_url = "https://www.potal.app"
embedded = true

[webhooks]
api_version = "2026-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://www.potal.app/api/shopify/webhooks"
  customer_data_request_url = "https://www.potal.app/api/shopify/webhooks"
  shop_deletion_url = "https://www.potal.app/api/shopify/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://www.potal.app/api/shopify/callback" ]

[app_proxy]
url = "https://www.potal.app/api/v1"
subpath = "potal"
prefix = "apps"

[pos]
embedded = false
