/**
 * POTAL demo API — /api/demo/scenario
 *
 * Homepage-only demo endpoint.
 *
 * - No auth required (homepage data URL for unauthenticated visitors)
 * - Simple in-memory IP throttle: 30 req/min per IP
 * - CW29 Sprint 7.5: cache-first, mock-fallback.
 *     1. Load the precomputed live baseline from lib/scenarios/live-baseline.json
 *        (generated by scripts/precompute-scenario-baselines.mjs)
 *     2. Scale the cached result with the user's inputs (applyInputsToResult)
 *     3. If the scenario isn't in the baseline → fall back to mock-results.ts
 *     4. Response schema unchanged — NonDevPanel never sees "source" in UI
 * - Adds `X-Response-Time: {ms}` and `X-Demo-Source: {mock|live-cached}` headers
 * - Cache-Control: no-store
 *
 * Why cache instead of real-time HTTP calls:
 *   The real /api/v1/classify + /api/v1/calculate chain averages ~4.5s per
 *   scenario (GRI pipeline + tariff DB + AD/CVD lookup). That exceeds the
 *   2-second UX budget. Precomputing once and caching gives <100ms responses
 *   with real engine data.
 *
 * NOT a public API. Do not link from external docs.
 */

import { NextRequest, NextResponse } from 'next/server';
import { getMockResult, type MockResult } from '@/lib/scenarios/mock-results';
import { getLiveBaseline } from '@/lib/scenarios/live-baseline';

const WINDOW_MS = 60_000;
const LIMIT_PER_WINDOW = 30;

interface Counter {
  count: number;
  windowStart: number;
}
const ipCounters = new Map<string, Counter>();

function throttled(ip: string): boolean {
  const now = Date.now();
  const entry = ipCounters.get(ip);
  if (!entry || now - entry.windowStart >= WINDOW_MS) {
    ipCounters.set(ip, { count: 1, windowStart: now });
    return false;
  }
  if (entry.count >= LIMIT_PER_WINDOW) return true;
  entry.count += 1;
  return false;
}

function getClientIp(req: NextRequest): string {
  return (
    req.headers.get('x-forwarded-for')?.split(',')[0].trim() ||
    req.headers.get('x-real-ip') ||
    'unknown'
  );
}

interface DemoRequestBody {
  scenarioId?: string;
  inputs?: Record<string, string | number | undefined>;
}

interface DemoResponseData {
  scenarioId: string;
  source: 'mock' | 'live' | 'live-cached';
  inputs: Record<string, string | number | undefined>;
  result: MockResult;
  generatedAt: string;
}

// ─── Input scaling ──────────────────────────────────────────────

function applyInputsToResult(
  baseline: MockResult,
  inputs: Record<string, string | number | undefined>
): MockResult {
  const value = Number(
    inputs.value ?? inputs.declaredValue ?? baseline.landedCost.productValue
  );
  if (
    !Number.isFinite(value) ||
    value <= 0 ||
    value === baseline.landedCost.productValue
  ) {
    return baseline;
  }
  const ratio = value / baseline.landedCost.productValue;
  const round2 = (n: number) => Math.round(n * 100) / 100;
  return {
    ...baseline,
    landedCost: {
      ...baseline.landedCost,
      productValue: round2(value),
      duty: round2(baseline.landedCost.duty * ratio),
      taxes: round2(baseline.landedCost.taxes * ratio),
      shipping: baseline.landedCost.shipping,
      fees: baseline.landedCost.fees,
      total: round2(
        value +
          baseline.landedCost.duty * ratio +
          baseline.landedCost.taxes * ratio +
          baseline.landedCost.shipping +
          baseline.landedCost.fees
      ),
    },
  };
}

function tryLiveCachedResult(
  scenarioId: string,
  inputs: Record<string, string | number | undefined>
): MockResult | null {
  const baseline = getLiveBaseline(scenarioId);
  if (!baseline) return null;
  return applyInputsToResult(baseline, inputs);
}

// ─── Handler ────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const startedAt = Date.now();
  const ip = getClientIp(req);

  if (throttled(ip)) {
    return NextResponse.json(
      {
        success: false,
        error: {
          code: 'rate_limited',
          message: 'Demo rate limit: 30 requests per minute. Slow down and try again.',
        },
      },
      {
        status: 429,
        headers: {
          'Retry-After': '30',
          'Cache-Control': 'no-store',
          'X-Response-Time': `${Date.now() - startedAt}`,
        },
      }
    );
  }

  let body: DemoRequestBody;
  try {
    body = (await req.json()) as DemoRequestBody;
  } catch {
    return NextResponse.json(
      { success: false, error: { code: 'bad_json', message: 'Invalid JSON body.' } },
      {
        status: 400,
        headers: { 'Cache-Control': 'no-store', 'X-Response-Time': `${Date.now() - startedAt}` },
      }
    );
  }

  const scenarioId = (body.scenarioId || '').trim();
  if (!scenarioId) {
    return NextResponse.json(
      {
        success: false,
        error: { code: 'missing_scenario', message: 'scenarioId is required.' },
      },
      {
        status: 400,
        headers: { 'Cache-Control': 'no-store', 'X-Response-Time': `${Date.now() - startedAt}` },
      }
    );
  }

  const mock = getMockResult(scenarioId);
  if (!mock) {
    return NextResponse.json(
      {
        success: false,
        error: { code: 'unknown_scenario', message: `Unknown scenarioId "${scenarioId}".` },
      },
      {
        status: 404,
        headers: { 'Cache-Control': 'no-store', 'X-Response-Time': `${Date.now() - startedAt}` },
      }
    );
  }

  const inputs: Record<string, string | number | undefined> = body.inputs || {};

  // Cache-first. live-baseline.json is committed and shipped in the server
  // bundle — reading is effectively free (<5ms).
  const cached = tryLiveCachedResult(scenarioId, inputs);
  const result = cached ?? applyInputsToResult(mock, inputs);
  const source: 'mock' | 'live-cached' = cached ? 'live-cached' : 'mock';

  const data: DemoResponseData = {
    scenarioId,
    source,
    inputs,
    result,
    generatedAt: new Date().toISOString(),
  };

  return NextResponse.json(
    { success: true, data },
    {
      headers: {
        'Cache-Control': 'no-store',
        'X-Response-Time': `${Date.now() - startedAt}`,
        'X-Demo-Source': source,
      },
    }
  );
}

export async function GET() {
  return NextResponse.json(
    {
      success: false,
      error: {
        code: 'method_not_allowed',
        message:
          'Use POST with JSON body: { "scenarioId": "seller", "inputs": { "value": 45 } }',
      },
    },
    { status: 405, headers: { 'Cache-Control': 'no-store' } }
  );
}
