/**
 * F105: Document Branding
 *
 * C4: Applies seller branding to invoices, customs declarations,
 * packing lists, and certificates of origin.
 */

import { type BrandingConfig, DEFAULT_BRANDING } from './widget-theme';

// ─── Types ──────────────────────────────────────────

export type DocumentTemplate = 'invoice' | 'customs_declaration' | 'packing_list' | 'certificate_of_origin';

export interface DocumentBranding {
  logoUrl?: string;
  displayName: string;
  primaryColor: string;
  secondaryColor: string;
  fontFamily: string;
  headerHtml: string;
  footerHtml: string;
}

// ─── Apply Branding ─────────────────────────────────

export function applyDocumentBranding(
  template: DocumentTemplate,
  config: Partial<BrandingConfig>,
): DocumentBranding {
  const merged = { ...DEFAULT_BRANDING, ...config };
  const displayName = merged.displayName || 'POTAL';

  const logoHtml = merged.logoUrl
    ? `<img src="${escapeHtml(merged.logoUrl)}" alt="${escapeHtml(displayName)}" style="max-height:48px;max-width:200px;" />`
    : `<span style="font-size:20px;font-weight:700;color:${merged.primaryColor};">${escapeHtml(displayName)}</span>`;

  const templateTitles: Record<DocumentTemplate, string> = {
    invoice: 'Commercial Invoice',
    customs_declaration: 'Customs Declaration',
    packing_list: 'Packing List',
    certificate_of_origin: 'Certificate of Origin',
  };

  const headerHtml = [
    `<div style="display:flex;justify-content:space-between;align-items:center;padding:16px 0;border-bottom:2px solid ${merged.primaryColor};margin-bottom:24px;font-family:${merged.fontFamily};">`,
    `  <div>${logoHtml}</div>`,
    `  <div style="text-align:right;">`,
    `    <div style="font-size:18px;font-weight:700;color:${merged.primaryColor};">${templateTitles[template]}</div>`,
    `    <div style="font-size:12px;color:#6B7280;">Generated by ${escapeHtml(displayName)}</div>`,
    `  </div>`,
    `</div>`,
  ].join('\n');

  const footerHtml = [
    `<div style="border-top:1px solid #E5E7EB;padding-top:12px;margin-top:24px;font-family:${merged.fontFamily};font-size:11px;color:#9CA3AF;text-align:center;">`,
    merged.showPoweredBy
      ? `<span>${escapeHtml(displayName)} — Powered by POTAL (potal.app)</span>`
      : `<span>${escapeHtml(displayName)}</span>`,
    `</div>`,
  ].join('\n');

  return {
    logoUrl: merged.logoUrl,
    displayName,
    primaryColor: merged.primaryColor,
    secondaryColor: merged.secondaryColor,
    fontFamily: merged.fontFamily,
    headerHtml,
    footerHtml,
  };
}

// ─── Template-specific Styles ───────────────────────

export function getDocumentStyles(config: Partial<BrandingConfig>): string {
  const merged = { ...DEFAULT_BRANDING, ...config };

  return [
    `body { font-family: ${merged.fontFamily}; color: ${merged.textColor}; margin: 0; padding: 24px; }`,
    `h1, h2, h3 { color: ${merged.primaryColor}; }`,
    `table { width: 100%; border-collapse: collapse; margin: 16px 0; }`,
    `th { background-color: ${merged.primaryColor}; color: #fff; padding: 8px 12px; text-align: left; font-size: 13px; }`,
    `td { padding: 8px 12px; border-bottom: 1px solid #E5E7EB; font-size: 13px; }`,
    `tr:nth-child(even) td { background-color: #F9FAFB; }`,
    `.total-row { font-weight: 700; border-top: 2px solid ${merged.primaryColor}; }`,
    `.highlight { color: ${merged.secondaryColor}; font-weight: 600; }`,
  ].join('\n');
}

// ─── Helpers ────────────────────────────────────────

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
