/**
 * POTAL PDF Generator — Converts document JSON to PDF binary
 *
 * Uses pdf-lib (pure JS, no native deps, Vercel serverless compatible).
 * Supports all 5 document types: commercial_invoice, packing_list,
 * certificate_of_origin, customs_declaration, required_documents.
 */
import { PDFDocument, PDFPage, PDFFont, rgb, StandardFonts } from 'pdf-lib';
import type {
  GenerateDocumentResult,
  CommercialInvoice,
  PackingList,
  CertificateOfOrigin,
  CustomsDeclaration,
  RequiredDocumentsResult,
} from './types';

// ─── Constants ──────────────────────────────────────
const MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4
const PAGE_HEIGHT = 841.89;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 14;
const SMALL_LINE = 11;

const COLOR_BLACK = rgb(0, 0, 0);
const COLOR_GRAY = rgb(0.4, 0.4, 0.4);
const COLOR_LIGHT_GRAY = rgb(0.85, 0.85, 0.85);
const COLOR_NAVY = rgb(0.008, 0.071, 0.173); // #02122c
const COLOR_BLUE = rgb(0.1, 0.3, 0.7);

// ─── Helpers ────────────────────────────────────────

function fmt(n: number): string {
  return n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function dateStr(): string {
  return new Date().toISOString().split('T')[0];
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max - 2) + '..' : s;
}

interface PageContext {
  doc: PDFDocument;
  page: PDFPage;
  font: PDFFont;
  fontBold: PDFFont;
  y: number;
  pageNum: number;
  title: string;
}

function addFooter(ctx: PageContext) {
  const { page, font } = ctx;
  const footerY = 30;
  page.drawText(`Generated by POTAL — potal.app`, {
    x: MARGIN,
    y: footerY,
    size: 7,
    font,
    color: COLOR_GRAY,
  });
  page.drawText(`Page ${ctx.pageNum}`, {
    x: PAGE_WIDTH - MARGIN - 30,
    y: footerY,
    size: 7,
    font,
    color: COLOR_GRAY,
  });
}

function newPage(ctx: PageContext): PageContext {
  addFooter(ctx);
  const page = ctx.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  ctx.pageNum++;
  return { ...ctx, page, y: PAGE_HEIGHT - MARGIN - 20, pageNum: ctx.pageNum };
}

function ensureSpace(ctx: PageContext, needed: number): PageContext {
  if (ctx.y - needed < 50) {
    return newPage(ctx);
  }
  return ctx;
}

function drawHeader(ctx: PageContext, title: string): PageContext {
  const { page, fontBold, font } = ctx;
  let y = PAGE_HEIGHT - MARGIN;

  // POTAL logo text
  page.drawText('POTAL', { x: MARGIN, y, size: 18, font: fontBold, color: COLOR_NAVY });
  page.drawText(dateStr(), {
    x: PAGE_WIDTH - MARGIN - 70,
    y,
    size: 9,
    font,
    color: COLOR_GRAY,
  });
  y -= 8;

  // Separator line
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 1.5,
    color: COLOR_NAVY,
  });
  y -= 24;

  // Document title
  page.drawText(title, { x: MARGIN, y, size: 16, font: fontBold, color: COLOR_BLACK });
  y -= 24;

  return { ...ctx, y, title };
}

function drawText(ctx: PageContext, text: string, opts?: { size?: number; bold?: boolean; color?: typeof COLOR_BLACK; indent?: number }): PageContext {
  ctx = ensureSpace(ctx, (opts?.size || 10) + 4);
  const size = opts?.size || 10;
  const font = opts?.bold ? ctx.fontBold : ctx.font;
  const color = opts?.color || COLOR_BLACK;
  const x = MARGIN + (opts?.indent || 0);
  ctx.page.drawText(text, { x, y: ctx.y, size, font, color });
  ctx.y -= size + 4;
  return ctx;
}

function drawTableRow(
  ctx: PageContext,
  cols: string[],
  widths: number[],
  opts?: { bold?: boolean; bg?: boolean; size?: number }
): PageContext {
  const size = opts?.size || 8;
  const rowH = size + 6;
  ctx = ensureSpace(ctx, rowH + 2);
  const font = opts?.bold ? ctx.fontBold : ctx.font;

  if (opts?.bg) {
    ctx.page.drawRectangle({
      x: MARGIN,
      y: ctx.y - 3,
      width: CONTENT_WIDTH,
      height: rowH,
      color: COLOR_LIGHT_GRAY,
    });
  }

  let xOff = MARGIN + 4;
  for (let i = 0; i < cols.length; i++) {
    ctx.page.drawText(truncate(cols[i], Math.floor(widths[i] / 4.5)), {
      x: xOff,
      y: ctx.y,
      size,
      font,
      color: COLOR_BLACK,
    });
    xOff += widths[i];
  }

  ctx.y -= rowH;
  return ctx;
}

function drawPartyBlock(ctx: PageContext, label: string, party: { name: string; address?: string; city?: string; state?: string; postalCode?: string; country: string; phone?: string; email?: string; taxId?: string }, x: number, width: number): PageContext {
  const { page, fontBold, font } = ctx;
  let y = ctx.y;
  const size = 8;

  page.drawText(label, { x, y, size: 9, font: fontBold, color: COLOR_BLUE });
  y -= 13;
  page.drawText(party.name, { x, y, size, font: fontBold, color: COLOR_BLACK });
  y -= SMALL_LINE;
  if (party.address) { page.drawText(truncate(party.address, Math.floor(width / 4)), { x, y, size, font, color: COLOR_BLACK }); y -= SMALL_LINE; }
  const cityLine = [party.city, party.state, party.postalCode].filter(Boolean).join(', ');
  if (cityLine) { page.drawText(truncate(cityLine, Math.floor(width / 4)), { x, y, size, font, color: COLOR_BLACK }); y -= SMALL_LINE; }
  page.drawText(`Country: ${party.country}`, { x, y, size, font, color: COLOR_BLACK }); y -= SMALL_LINE;
  if (party.taxId) { page.drawText(`Tax ID: ${party.taxId}`, { x, y, size, font, color: COLOR_BLACK }); y -= SMALL_LINE; }
  if (party.phone) { page.drawText(`Phone: ${party.phone}`, { x, y, size, font, color: COLOR_GRAY }); y -= SMALL_LINE; }
  if (party.email) { page.drawText(`Email: ${party.email}`, { x, y, size, font, color: COLOR_GRAY }); y -= SMALL_LINE; }

  return ctx;
}

// ─── Commercial Invoice ─────────────────────────────

function renderCommercialInvoice(ctx: PageContext, inv: CommercialInvoice): PageContext {
  ctx = drawHeader(ctx, 'COMMERCIAL INVOICE');

  // Invoice meta
  ctx = drawText(ctx, `Invoice No: ${inv.invoiceNumber}     Date: ${inv.invoiceDate}     Currency: ${inv.currency}`, { size: 9 });
  ctx = drawText(ctx, `Incoterm: ${inv.incoterm}${inv.paymentTerms ? `     Payment: ${inv.paymentTerms}` : ''}`, { size: 9, color: COLOR_GRAY });
  ctx.y -= 8;

  // Parties — 2 columns
  const startY = ctx.y;
  drawPartyBlock(ctx, 'EXPORTER', inv.exporter, MARGIN, CONTENT_WIDTH / 2);
  ctx.y = startY;
  drawPartyBlock(ctx, 'IMPORTER', inv.importer, MARGIN + CONTENT_WIDTH / 2, CONTENT_WIDTH / 2);
  ctx.y = startY - 80;

  // Items table
  const colW = [160, 80, 50, 75, 75, 55];
  ctx = drawTableRow(ctx, ['Item', 'HS Code', 'Qty', 'Unit Price', 'Total', 'Origin'], colW, { bold: true, bg: true });
  for (const item of inv.items) {
    ctx = drawTableRow(ctx, [
      truncate(item.description, 35),
      item.hsCode || '-',
      String(item.quantity),
      fmt(item.unitPrice),
      fmt(item.totalPrice),
      item.countryOfOrigin || '-',
    ], colW);
  }

  // Separator
  ctx.y -= 6;
  ctx.page.drawLine({ start: { x: MARGIN, y: ctx.y }, end: { x: PAGE_WIDTH - MARGIN, y: ctx.y }, thickness: 0.5, color: COLOR_LIGHT_GRAY });
  ctx.y -= 12;

  // Totals — right aligned
  const totX = PAGE_WIDTH - MARGIN - 180;
  const drawTotal = (label: string, val: string, bold?: boolean) => {
    ctx = ensureSpace(ctx, 14);
    ctx.page.drawText(label, { x: totX, y: ctx.y, size: 9, font: bold ? ctx.fontBold : ctx.font, color: COLOR_BLACK });
    ctx.page.drawText(val, { x: totX + 120, y: ctx.y, size: 9, font: bold ? ctx.fontBold : ctx.font, color: COLOR_BLACK });
    ctx.y -= LINE_HEIGHT;
  };

  drawTotal('Subtotal:', `${inv.currency} ${fmt(inv.subtotal)}`);
  drawTotal('Shipping:', `${inv.currency} ${fmt(inv.shippingCost)}`);
  drawTotal('Insurance:', `${inv.currency} ${fmt(inv.insuranceCost)}`);
  ctx.y -= 4;
  ctx.page.drawLine({ start: { x: totX, y: ctx.y + 2 }, end: { x: PAGE_WIDTH - MARGIN, y: ctx.y + 2 }, thickness: 1, color: COLOR_NAVY });
  ctx.y -= 4;
  drawTotal('GRAND TOTAL:', `${inv.currency} ${fmt(inv.grandTotal)}`, true);

  if (inv.notes) {
    ctx.y -= 10;
    ctx = drawText(ctx, `Notes: ${inv.notes}`, { size: 8, color: COLOR_GRAY });
  }

  addFooter(ctx);
  return ctx;
}

// ─── Packing List ───────────────────────────────────

function renderPackingList(ctx: PageContext, pl: PackingList): PageContext {
  ctx = drawHeader(ctx, 'PACKING LIST');

  ctx = drawText(ctx, `Ref Invoice: ${pl.invoiceNumber}     Date: ${pl.date}`, { size: 9 });
  ctx.y -= 4;

  const startY = ctx.y;
  drawPartyBlock(ctx, 'EXPORTER', pl.exporter, MARGIN, CONTENT_WIDTH / 2);
  ctx.y = startY;
  drawPartyBlock(ctx, 'IMPORTER', pl.importer, MARGIN + CONTENT_WIDTH / 2, CONTENT_WIDTH / 2);
  ctx.y = startY - 80;

  // Items table
  const colW = [40, 140, 70, 40, 110, 55];
  ctx = drawTableRow(ctx, ['Pkg#', 'Description', 'HS Code', 'Qty', 'Dimensions (cm)', 'Weight(kg)'], colW, { bold: true, bg: true });
  for (const item of pl.items) {
    const dim = item.dimensionsCm ? `${item.dimensionsCm.length}x${item.dimensionsCm.width}x${item.dimensionsCm.height}` : '-';
    ctx = drawTableRow(ctx, [
      item.packageNumber || '-',
      truncate(item.description, 30),
      item.hsCode || '-',
      String(item.quantity),
      dim,
      item.weightKg ? String(item.weightKg) : '-',
    ], colW);
  }

  ctx.y -= 12;
  ctx = drawText(ctx, `Total Packages: ${pl.totalPackages}`, { size: 9, bold: true });
  ctx = drawText(ctx, `Total Gross Weight: ${pl.totalWeightKg} kg`, { size: 9, bold: true });
  if (pl.shippingMethod) ctx = drawText(ctx, `Shipping Method: ${pl.shippingMethod}`, { size: 9 });
  if (pl.notes) ctx = drawText(ctx, `Notes: ${pl.notes}`, { size: 8, color: COLOR_GRAY });

  addFooter(ctx);
  return ctx;
}

// ─── Certificate of Origin ──────────────────────────

function renderCertificateOfOrigin(ctx: PageContext, coo: CertificateOfOrigin): PageContext {
  ctx = drawHeader(ctx, 'CERTIFICATE OF ORIGIN');

  ctx = drawText(ctx, `Certificate No: ${coo.certificateNumber}     Issue Date: ${coo.issueDate}`, { size: 9 });
  ctx = drawText(ctx, `Origin: ${coo.originCountry} → Destination: ${coo.destinationCountry}${coo.isPreferential ? '     (Preferential)' : ''}`, { size: 9 });
  if (coo.tradeAgreement) ctx = drawText(ctx, `Trade Agreement: ${coo.tradeAgreement}`, { size: 9, color: COLOR_BLUE });
  ctx.y -= 6;

  const startY = ctx.y;
  drawPartyBlock(ctx, 'EXPORTER / PRODUCER', coo.exporter, MARGIN, CONTENT_WIDTH / 2);
  ctx.y = startY;
  drawPartyBlock(ctx, 'IMPORTER / CONSIGNEE', coo.importer, MARGIN + CONTENT_WIDTH / 2, CONTENT_WIDTH / 2);
  ctx.y = startY - 80;

  // Items
  const colW = [180, 90, 50, 90, 85];
  ctx = drawTableRow(ctx, ['Description', 'HS Code', 'Qty', 'Country of Origin', 'Criterion'], colW, { bold: true, bg: true });
  for (const item of coo.items) {
    ctx = drawTableRow(ctx, [
      truncate(item.description, 40),
      item.hsCode || '-',
      String(item.quantity),
      item.countryOfOrigin,
      item.originCriterion || '-',
    ], colW);
  }

  // Declaration
  ctx.y -= 16;
  ctx = drawText(ctx, 'DECLARATION', { size: 10, bold: true });
  // Word-wrap declaration text
  const words = coo.declaration.split(' ');
  let line = '';
  for (const w of words) {
    if ((line + ' ' + w).length > 90) {
      ctx = drawText(ctx, line.trim(), { size: 8 });
      line = w;
    } else {
      line += ' ' + w;
    }
  }
  if (line.trim()) ctx = drawText(ctx, line.trim(), { size: 8 });

  ctx.y -= 30;
  ctx = drawText(ctx, 'Authorized Signature: ________________________________', { size: 9 });
  ctx = drawText(ctx, `Date: ${coo.issueDate}`, { size: 9, color: COLOR_GRAY });

  addFooter(ctx);
  return ctx;
}

// ─── Customs Declaration ────────────────────────────

function renderCustomsDeclaration(ctx: PageContext, cd: CustomsDeclaration): PageContext {
  ctx = drawHeader(ctx, 'CUSTOMS DECLARATION');

  ctx = drawText(ctx, `Declaration No: ${cd.declarationNumber}     Type: ${cd.declarationType.toUpperCase()}     Date: ${cd.declarationDate}`, { size: 9 });
  ctx = drawText(ctx, `Origin: ${cd.countryOfOrigin} → Destination: ${cd.countryOfDestination}     Incoterm: ${cd.incoterm}     Currency: ${cd.currency}`, { size: 9 });
  if (cd.iossNumber) ctx = drawText(ctx, `IOSS: ${cd.iossNumber}`, { size: 8, color: COLOR_GRAY });
  if (cd.eoriNumber) ctx = drawText(ctx, `EORI: ${cd.eoriNumber}`, { size: 8, color: COLOR_GRAY });
  ctx.y -= 6;

  const startY = ctx.y;
  drawPartyBlock(ctx, 'DECLARANT', cd.declarant, MARGIN, CONTENT_WIDTH / 2);
  ctx.y = startY;
  drawPartyBlock(ctx, 'EXPORTER', cd.exporter, MARGIN + CONTENT_WIDTH / 2, CONTENT_WIDTH / 2);
  ctx.y = startY - 80;

  // Items
  const colW = [150, 70, 60, 60, 75, 80];
  ctx = drawTableRow(ctx, ['Description', 'HS Code', 'Value', 'Weight(kg)', 'Duty', 'VAT'], colW, { bold: true, bg: true });
  for (const item of cd.items) {
    ctx = drawTableRow(ctx, [
      truncate(item.description, 35),
      item.hsCode || '-',
      fmt(item.totalValue),
      item.weightKg ? String(item.weightKg) : '-',
      item.dutyAmount !== undefined ? fmt(item.dutyAmount) : '-',
      item.vatAmount !== undefined ? fmt(item.vatAmount) : '-',
    ], colW);
  }

  // Totals
  ctx.y -= 10;
  const totX = PAGE_WIDTH - MARGIN - 200;
  const drawTotal = (label: string, val: string, bold?: boolean) => {
    ctx = ensureSpace(ctx, 14);
    ctx.page.drawText(label, { x: totX, y: ctx.y, size: 9, font: bold ? ctx.fontBold : ctx.font, color: COLOR_BLACK });
    ctx.page.drawText(val, { x: totX + 140, y: ctx.y, size: 9, font: bold ? ctx.fontBold : ctx.font, color: COLOR_BLACK });
    ctx.y -= LINE_HEIGHT;
  };

  drawTotal('Declared Value:', `${cd.currency} ${fmt(cd.totalDeclaredValue)}`);
  drawTotal('Total Duty:', `${cd.currency} ${fmt(cd.totalDuty)}`);
  drawTotal('Total VAT/GST:', `${cd.currency} ${fmt(cd.totalVat)}`);
  drawTotal('Total Fees:', `${cd.currency} ${fmt(cd.totalFees)}`);
  ctx.y -= 2;
  ctx.page.drawLine({ start: { x: totX, y: ctx.y + 2 }, end: { x: PAGE_WIDTH - MARGIN, y: ctx.y + 2 }, thickness: 1, color: COLOR_NAVY });
  ctx.y -= 6;
  drawTotal('TOTAL PAYABLE:', `${cd.currency} ${fmt(cd.totalPayable)}`, true);

  addFooter(ctx);
  return ctx;
}

// ─── Required Documents ─────────────────────────────

function renderRequiredDocuments(ctx: PageContext, rd: RequiredDocumentsResult): PageContext {
  ctx = drawHeader(ctx, 'REQUIRED DOCUMENTS CHECKLIST');

  ctx = drawText(ctx, `Route: ${rd.originCountry} → ${rd.destinationCountry}${rd.hsCode ? `     HS Code: ${rd.hsCode}` : ''}`, { size: 9 });
  ctx.y -= 8;

  // Group documents by category
  const mandatory = rd.documents.filter(d => d.required);
  const optional = rd.documents.filter(d => !d.required);

  if (mandatory.length > 0) {
    ctx = drawText(ctx, 'MANDATORY DOCUMENTS', { size: 10, bold: true, color: COLOR_NAVY });
    ctx.y -= 4;
    for (const doc of mandatory) {
      ctx = ensureSpace(ctx, 24);
      const check = '\u2610'; // ☐
      ctx = drawText(ctx, `${check}  ${doc.name}  (${doc.code})`, { size: 9, bold: true });
      ctx = drawText(ctx, `     ${doc.description}`, { size: 8, color: COLOR_GRAY, indent: 8 });
      ctx = drawText(ctx, `     Responsible: ${doc.responsible}`, { size: 7, color: COLOR_GRAY, indent: 8 });
    }
  }

  if (optional.length > 0) {
    ctx.y -= 10;
    ctx = drawText(ctx, 'OPTIONAL / CONDITIONAL DOCUMENTS', { size: 10, bold: true, color: COLOR_NAVY });
    ctx.y -= 4;
    for (const doc of optional) {
      ctx = ensureSpace(ctx, 24);
      const check = '\u2610';
      ctx = drawText(ctx, `${check}  ${doc.name}  (${doc.code})`, { size: 9 });
      ctx = drawText(ctx, `     ${doc.description}`, { size: 8, color: COLOR_GRAY, indent: 8 });
    }
  }

  // Notes
  if (rd.notes.length > 0) {
    ctx.y -= 12;
    ctx = drawText(ctx, 'NOTES', { size: 10, bold: true });
    for (const note of rd.notes) {
      ctx = drawText(ctx, `• ${note}`, { size: 8, color: COLOR_GRAY });
    }
  }

  addFooter(ctx);
  return ctx;
}

// ─── Public API ─────────────────────────────────────

async function createBaseContext(doc: PDFDocument, title: string): Promise<PageContext> {
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  return { doc, page, font, fontBold, y: PAGE_HEIGHT - MARGIN, pageNum: 1, title };
}

/**
 * Generate a PDF for a specific document type from GenerateDocumentResult.
 */
export async function generatePdf(
  result: GenerateDocumentResult,
  options?: { documentType?: string }
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle('POTAL Document');
  doc.setProducer('POTAL — potal.app');
  doc.setCreationDate(new Date());

  const type = options?.documentType || detectType(result);

  if (type === 'commercial_invoice' && result.commercialInvoice) {
    const ctx = await createBaseContext(doc, 'Commercial Invoice');
    renderCommercialInvoice(ctx, result.commercialInvoice);
  } else if (type === 'packing_list' && result.packingList) {
    const ctx = await createBaseContext(doc, 'Packing List');
    renderPackingList(ctx, result.packingList);
  } else if (type === 'certificate_of_origin' && result.certificateOfOrigin) {
    const ctx = await createBaseContext(doc, 'Certificate of Origin');
    renderCertificateOfOrigin(ctx, result.certificateOfOrigin);
  } else if (type === 'customs_declaration' && result.customsDeclaration) {
    const ctx = await createBaseContext(doc, 'Customs Declaration');
    renderCustomsDeclaration(ctx, result.customsDeclaration);
  } else if (type === 'required_documents' && result.requiredDocuments) {
    const ctx = await createBaseContext(doc, 'Required Documents');
    renderRequiredDocuments(ctx, result.requiredDocuments);
  } else {
    // Fallback: render whatever is available
    return generateMultiPagePdf(result);
  }

  return doc.save();
}

/**
 * Generate a multi-page PDF with all available documents combined.
 */
export async function generateMultiPagePdf(
  result: GenerateDocumentResult
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle('POTAL Documents');
  doc.setProducer('POTAL — potal.app');
  doc.setCreationDate(new Date());

  let pageNum = 0;

  if (result.commercialInvoice) {
    const ctx = await createBaseContext(doc, 'Commercial Invoice');
    ctx.pageNum = ++pageNum;
    renderCommercialInvoice(ctx, result.commercialInvoice);
  }
  if (result.packingList) {
    const ctx = await createBaseContext(doc, 'Packing List');
    ctx.pageNum = ++pageNum;
    renderPackingList(ctx, result.packingList);
  }
  if (result.certificateOfOrigin) {
    const ctx = await createBaseContext(doc, 'Certificate of Origin');
    ctx.pageNum = ++pageNum;
    renderCertificateOfOrigin(ctx, result.certificateOfOrigin);
  }
  if (result.customsDeclaration) {
    const ctx = await createBaseContext(doc, 'Customs Declaration');
    ctx.pageNum = ++pageNum;
    renderCustomsDeclaration(ctx, result.customsDeclaration);
  }
  if (result.requiredDocuments) {
    const ctx = await createBaseContext(doc, 'Required Documents');
    ctx.pageNum = ++pageNum;
    renderRequiredDocuments(ctx, result.requiredDocuments);
  }

  // If nothing was generated, create a blank page with message
  if (pageNum === 0) {
    const ctx = await createBaseContext(doc, 'No Documents');
    drawText(ctx, 'No document data available to render.', { size: 12 });
  }

  return doc.save();
}

/**
 * Generate a simple table-based PDF (for reports export).
 */
export async function generateTablePdf(
  title: string,
  columns: string[],
  rows: Record<string, unknown>[],
  meta?: { dateRange?: string; total?: number }
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(title);
  doc.setProducer('POTAL — potal.app');

  let ctx = await createBaseContext(doc, title);
  ctx = drawHeader(ctx, title);

  if (meta?.dateRange) ctx = drawText(ctx, `Date Range: ${meta.dateRange}`, { size: 9, color: COLOR_GRAY });
  if (meta?.total !== undefined) ctx = drawText(ctx, `Total Records: ${meta.total}`, { size: 9, color: COLOR_GRAY });
  ctx.y -= 8;

  // Calculate column widths evenly
  const colWidth = Math.floor(CONTENT_WIDTH / columns.length);
  const widths = columns.map(() => colWidth);

  ctx = drawTableRow(ctx, columns, widths, { bold: true, bg: true, size: 7 });

  for (const row of rows) {
    ctx = drawTableRow(
      ctx,
      columns.map(c => String(row[c] ?? '')),
      widths,
      { size: 7 }
    );
  }

  addFooter(ctx);
  return doc.save();
}

/**
 * Generate a shipping label PDF (4x6 inch).
 */
export async function generateShippingLabelPdf(data: {
  from: { name: string; address?: string; city?: string; state?: string; postalCode?: string; country?: string };
  to: { name: string; address?: string; city?: string; state?: string; postalCode?: string; country?: string };
  trackingNumber: string;
  carrier: string;
  weight?: string;
  hsCode?: string;
  origin?: string;
  labelId: string;
}): Promise<Uint8Array> {
  // 4x6 inches = 288x432 points
  const W = 288;
  const H = 432;
  const M = 14;

  const doc = await PDFDocument.create();
  doc.setTitle(`Shipping Label ${data.labelId}`);
  const page = doc.addPage([W, H]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  let y = H - M;

  // Header
  page.drawText('POTAL', { x: M, y, size: 12, font: fontBold, color: COLOR_NAVY });
  page.drawText(data.carrier.toUpperCase(), { x: W - M - 60, y, size: 10, font: fontBold, color: COLOR_BLACK });
  y -= 16;
  page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 1, color: COLOR_BLACK });
  y -= 14;

  // FROM
  page.drawText('FROM:', { x: M, y, size: 7, font: fontBold, color: COLOR_GRAY });
  y -= 11;
  page.drawText(data.from.name, { x: M, y, size: 8, font: fontBold, color: COLOR_BLACK });
  y -= 10;
  if (data.from.address) { page.drawText(data.from.address, { x: M, y, size: 7, font, color: COLOR_BLACK }); y -= 9; }
  const fromCity = [data.from.city, data.from.state, data.from.postalCode].filter(Boolean).join(', ');
  if (fromCity) { page.drawText(fromCity, { x: M, y, size: 7, font, color: COLOR_BLACK }); y -= 9; }
  if (data.from.country) { page.drawText(data.from.country, { x: M, y, size: 7, font, color: COLOR_BLACK }); y -= 9; }
  y -= 6;

  // Separator
  page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.5, color: COLOR_LIGHT_GRAY });
  y -= 14;

  // TO
  page.drawText('TO:', { x: M, y, size: 7, font: fontBold, color: COLOR_GRAY });
  y -= 12;
  page.drawText(data.to.name, { x: M, y, size: 11, font: fontBold, color: COLOR_BLACK });
  y -= 13;
  if (data.to.address) { page.drawText(data.to.address, { x: M, y, size: 9, font, color: COLOR_BLACK }); y -= 11; }
  const toCity = [data.to.city, data.to.state, data.to.postalCode].filter(Boolean).join(', ');
  if (toCity) { page.drawText(toCity, { x: M, y, size: 9, font, color: COLOR_BLACK }); y -= 11; }
  if (data.to.country) { page.drawText(data.to.country, { x: M, y, size: 9, font: fontBold, color: COLOR_BLACK }); y -= 11; }
  y -= 10;

  // Barcode placeholder
  page.drawRectangle({ x: M, y: y - 40, width: W - M * 2, height: 40, borderColor: COLOR_BLACK, borderWidth: 1 });
  page.drawText('[ BARCODE PLACEHOLDER ]', { x: M + 60, y: y - 25, size: 9, font, color: COLOR_GRAY });
  y -= 52;

  // Tracking number
  page.drawText(data.trackingNumber, { x: M, y, size: 10, font: fontBold, color: COLOR_BLACK });
  y -= 16;

  // Details
  page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.5, color: COLOR_LIGHT_GRAY });
  y -= 12;
  if (data.weight) { page.drawText(`Weight: ${data.weight}`, { x: M, y, size: 8, font, color: COLOR_BLACK }); y -= 10; }
  if (data.hsCode) { page.drawText(`HS Code: ${data.hsCode}`, { x: M, y, size: 8, font, color: COLOR_BLACK }); y -= 10; }
  if (data.origin) { page.drawText(`Origin: ${data.origin}`, { x: M, y, size: 8, font, color: COLOR_BLACK }); y -= 10; }

  // Watermark
  y -= 10;
  page.drawText('Connect carrier API for production labels', { x: M, y, size: 6, font, color: COLOR_GRAY });

  // Footer
  page.drawText(`Label ID: ${data.labelId}`, { x: M, y: 10, size: 6, font, color: COLOR_GRAY });
  page.drawText('potal.app', { x: W - M - 35, y: 10, size: 6, font, color: COLOR_GRAY });

  return doc.save();
}

// ─── Internal ───────────────────────────────────────

function detectType(result: GenerateDocumentResult): string {
  if (result.commercialInvoice) return 'commercial_invoice';
  if (result.packingList) return 'packing_list';
  if (result.certificateOfOrigin) return 'certificate_of_origin';
  if (result.customsDeclaration) return 'customs_declaration';
  if (result.requiredDocuments) return 'required_documents';
  return 'commercial_invoice';
}
