// Chapter 01: Live Animals -- 34 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_01: HsCodeEntry[] = [
  { code: '010121', description: 'Live horses, asses, mules and hinnies:Horses:*Pure-bred breeding animals<951>', chapter: '01', category: 'animals', keywords: ['live', 'horses', 'asses', 'mules', 'hinnieshorsespure', 'bred', 'breeding', 'animals951'] },
  { code: '010129', description: 'Live horses, asses, mules and hinnies:Horses:*Other:**For slaughter', chapter: '01', category: 'animals', keywords: ['live', 'horses', 'asses', 'mules', 'hinnieshorsesfor', 'slaughter'] },
  { code: '010130', description: 'Live horses, asses, mules and hinnies:Asses', chapter: '01', category: 'animals', keywords: ['live', 'horses', 'asses', 'mules', 'hinniesasses'] },
  { code: '010190', description: 'Live horses, asses, mules and hinnies:Other', chapter: '01', category: 'animals', keywords: ['live', 'horses', 'asses', 'mules', 'hinnies'] },
  { code: '010221', description: 'Live bovine animals:Cattle:*Pure-bred breeding animals<952>:**Heifers (female...', chapter: '01', category: 'animals', keywords: ['live', 'bovine', 'animalscattlepure', 'bred', 'breeding', 'animals952heifers', 'female', 'bovines', 'that', 'have'] },
  { code: '010229', description: 'Live bovine animals:Cattle:*Other:**Of the sub-genus Bibos or of the sub-genu...', chapter: '01', category: 'animals', keywords: ['live', 'bovine', 'animalscattleof', 'sub', 'genus', 'bibos', 'poephagus'] },
  { code: '010231', description: 'Live bovine animals:Buffalo:*Pure-bred breeding animals<952>', chapter: '01', category: 'animals', keywords: ['live', 'bovine', 'animalsbuffalopure', 'bred', 'breeding', 'animals952'] },
  { code: '010239', description: 'Live bovine animals:Buffalo:*Other:**Domestic species', chapter: '01', category: 'animals', keywords: ['live', 'bovine', 'animalsbuffalodomestic', 'species'] },
  { code: '010290', description: 'Live bovine animals:Other:*Pure-bred breeding animals<952>', chapter: '01', category: 'animals', keywords: ['live', 'bovine', 'animalspure', 'bred', 'breeding', 'animals952'] },
  { code: '010310', description: 'Live swine:Pure-bred breeding animals<954>', chapter: '01', category: 'animals', keywords: ['live', 'swinepure', 'bred', 'breeding', 'animals954'] },
  { code: '010391', description: 'Live swine:Other:*Weighing less than 50 kg:**Domestic species', chapter: '01', category: 'animals', keywords: ['live', 'swineweighing', 'kgdomestic', 'species'] },
  { code: '010392', description: 'Live swine:Other:*Weighing 50 kg or more:**Domestic species:***Sows having fa...', chapter: '01', category: 'animals', keywords: ['live', 'swineweighing', 'moredomestic', 'speciessows', 'farrowed', 'least', 'once', '160'] },
  { code: '010410', description: 'Live sheep and goats:Sheep:*Pure-bred breeding animals<953>', chapter: '01', category: 'animals', keywords: ['live', 'sheep', 'goatssheeppure', 'bred', 'breeding', 'animals953'] },
  { code: '010420', description: 'Live sheep and goats:Goats:*Pure-bred breeding animals<953>', chapter: '01', category: 'animals', keywords: ['live', 'sheep', 'goatsgoatspure', 'bred', 'breeding', 'animals953'] },
  { code: '010511', description: 'Live poultry, that is to say, fowls of the species <AI>!Gallus domesticus!, d...', chapter: '01', category: 'animals', keywords: ['live', 'poultry', 'that', 'say', 'fowls', 'species', 'aigallus', 'domesticus', 'ducks', 'geese'] },
  { code: '010512', description: 'Live poultry, that is to say, fowls of the species <AI>!Gallus domesticus!, d...', chapter: '01', category: 'animals', keywords: ['live', 'poultry', 'that', 'say', 'fowls', 'species', 'aigallus', 'domesticus', 'ducks', 'geese'] },
  { code: '010513', description: 'Live poultry, that is to say, fowls of the species <AI>!Gallus domesticus!, d...', chapter: '01', category: 'animals', keywords: ['live', 'poultry', 'that', 'say', 'fowls', 'species', 'aigallus', 'domesticus', 'ducks', 'geese'] },
  { code: '010514', description: 'Live poultry, that is to say, fowls of the species <AI>!Gallus domesticus!, d...', chapter: '01', category: 'animals', keywords: ['live', 'poultry', 'that', 'say', 'fowls', 'species', 'aigallus', 'domesticus', 'ducks', 'geese'] },
  { code: '010515', description: 'Live poultry, that is to say, fowls of the species <AI>!Gallus domesticus!, d...', chapter: '01', category: 'animals', keywords: ['live', 'poultry', 'that', 'say', 'fowls', 'species', 'aigallus', 'domesticus', 'ducks', 'geese'] },
  { code: '010594', description: 'Live poultry, that is to say, fowls of the species <AI>!Gallus domesticus!, d...', chapter: '01', category: 'animals', keywords: ['live', 'poultry', 'that', 'say', 'fowls', 'species', 'aigallus', 'domesticus', 'ducks', 'geese'] },
  { code: '010599', description: 'Live poultry, that is to say, fowls of the species <AI>!Gallus domesticus!, d...', chapter: '01', category: 'animals', keywords: ['live', 'poultry', 'that', 'say', 'fowls', 'species', 'aigallus', 'domesticus', 'ducks', 'geese'] },
  { code: '010611', description: 'Other live animals:Mammals:*Primates', chapter: '01', category: 'animals', keywords: ['live', 'animalsmammalsprimates'] },
  { code: '010612', description: 'Other live animals:Mammals:*Whales, dolphins and porpoises (mammals of the or...', chapter: '01', category: 'animals', keywords: ['live', 'animalsmammalswhales', 'dolphins', 'porpoises', 'mammals', 'order', 'cetacea', 'manatees', 'dugongs', 'sirenia'] },
  { code: '010613', description: 'Other live animals:Mammals:*Camels and other camelids (camelidae)', chapter: '01', category: 'animals', keywords: ['live', 'animalsmammalscamels', 'camelids', 'camelidae'] },
  { code: '010614', description: 'Other live animals:Mammals:*Rabbits and hares:**Domestic rabbits', chapter: '01', category: 'animals', keywords: ['live', 'animalsmammalsrabbits', 'haresdomestic', 'rabbits'] },
  { code: '010619', description: 'Other live animals:Mammals:*Other', chapter: '01', category: 'animals', keywords: ['live', 'animalsmammals'] },
  { code: '010620', description: 'Other live animals:Reptiles(including snakes and turtles)', chapter: '01', category: 'animals', keywords: ['live', 'animalsreptiles', 'snakes', 'turtles'] },
  { code: '010631', description: 'Other live animals:Birds:*Birds of prey', chapter: '01', category: 'animals', keywords: ['live', 'animalsbirdsbirds', 'prey'] },
  { code: '010632', description: 'Other live animals:Birds:*Psittaciformes (including parrots, parakeets, macaw...', chapter: '01', category: 'animals', keywords: ['live', 'animalsbirdspsittaciformes', 'parrots', 'parakeets', 'macaws', 'cockatoos'] },
  { code: '010633', description: 'Other live animals:Birds:*Ostriches; emus (Dromaius novaehollandiae)', chapter: '01', category: 'animals', keywords: ['live', 'animalsbirdsostriches', 'emus', 'dromaius', 'novaehollandiae'] },
  { code: '010639', description: 'Other live animals:Birds:*Other:**Pigeons', chapter: '01', category: 'animals', keywords: ['live', 'animalsbirdspigeons'] },
  { code: '010641', description: 'Other live animals:Insects:*Bees', chapter: '01', category: 'animals', keywords: ['live', 'animalsinsectsbees'] },
  { code: '010649', description: 'Other live animals:Insects:*Other', chapter: '01', category: 'animals', keywords: ['live', 'animalsinsects'] },
  { code: '010690', description: 'Other live animals:Other', chapter: '01', category: 'animals', keywords: ['live', 'animals'] },
];
