// Chapter 05: Animal Products NES -- 16 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_05: HsCodeEntry[] = [
  { code: '050100', description: 'Animal products; hair, human, unworked, whether or not washed or scoured, and waste of human hair', chapter: '05', category: 'food', keywords: ['animal', 'hair', 'human', 'unworked', 'washed', 'scoured', 'waste'] },
  { code: '050110', description: 'Animal hair', chapter: '05', category: 'textiles', keywords: ['animal hair', 'alpaca', 'mohair', 'cashmere'] },
  { code: '050210', description: 'Pigs\\, hogs\\ or boars\\ bristles and hair; badger hair and other brush maki...', chapter: '05', category: 'food', keywords: ['animal', 'hair', 'bristles', 'pigs', 'hogs', 'boars', 'waste'] },
  { code: '050290', description: 'Pigs\\, hogs\\ or boars\\ bristles and hair; badger hair and other brush maki...', chapter: '05', category: 'food', keywords: ['pigs', 'hogs', 'boars', 'bristles', 'hair', 'badger', 'brush', 'making', 'waste', 'such'] },
  { code: '050400', description: 'Animal products; guts, bladders and stomachs of animals (other than fish), whole and pieces thereof, fresh, chilled, fro', chapter: '05', category: 'food', keywords: ['animal', 'guts', 'bladders', 'stomachs', 'animals', 'fish', 'whole', 'pieces', 'fresh', 'chilled', 'frozen', 'salted', 'brine', 'dried', 'smoked'] },
  { code: '050510', description: 'Animal products; feathers and down used for stuffing, not further worked than cleaned, disinfected or treated for preser', chapter: '05', category: 'food', keywords: ['animal', 'feathers', 'down', 'stuffing', 'further', 'worked', 'cleaned', 'disinfected', 'treated', 'preservation'] },
  { code: '050590', description: 'Animal products; skins and other parts of birds, feathers and down (not for stuffing), powder and waste of such, not fur', chapter: '05', category: 'food', keywords: ['animal', 'skins', 'birds', 'feathers', 'down', 'stuffing', 'powder', 'waste', 'further', 'worked', 'cleaned', 'disinfected', 'treated', 'preservation'] },
  { code: '050610', description: 'Bones and horn-cores, unworked, defatted, simply prepared (but not cut to sha...', chapter: '05', category: 'food', keywords: ['animal', 'ossein', 'bones', 'treated', 'acid'] },
  { code: '050690', description: 'Bones and horn-cores, unworked, defatted, simply prepared (but not cut to sha...', chapter: '05', category: 'food', keywords: ['bones', 'horn', 'cores', 'unworked', 'defatted', 'simply', 'prepared', 'cut', 'shape', 'treated'] },
  { code: '050710', description: 'Animal products; ivory, unworked or simply prepared but not cut to shape, ivory powder and waste', chapter: '05', category: 'food', keywords: ['animal', 'ivory', 'unworked', 'simply', 'prepared', 'cut', 'shape', 'powder', 'waste'] },
  { code: '050790', description: 'Animal products; tortoise-shell, whalebone and whalebone hair, horns, antlers, hooves, nails, claws and beaks, unworked ', chapter: '05', category: 'food', keywords: ['animal', 'tortoise-shell', 'whalebone', 'hair', 'horns', 'antlers', 'hooves', 'nails', 'claws', 'beaks', 'unworked', 'simply', 'prepared', 'cut', 'shape', 'waste', 'powder'] },
  { code: '050800', description: 'Animal products; coral and similar materials, shells of molluscs, crustaceans, echinoderms, cuttle-bone, unworked or sim', chapter: '05', category: 'food', keywords: ['animal', 'coral', 'materials', 'shells', 'molluscs', 'crustaceans', 'echinoderms', 'cuttle-bone', 'unworked', 'simply', 'prepared', 'cut', 'shape', 'powder', 'waste'] },
  { code: '051000', description: 'Animal products; ambergris, castoreum, civet, musk, cantharides, bile (dried or not) glands and other animal products, f', chapter: '05', category: 'food', keywords: ['animal', 'ambergris', 'castoreum', 'civet', 'musk', 'cantharides', 'bile', 'dried', 'glands', 'pharmaceutical', 'purposes', 'fresh', 'chilled', 'frozen', 'otherwise', 'provisionally', 'preserved'] },
  { code: '051110', description: 'Animal products not elsewhere specified or included; dead animals of Chapter ...', chapter: '05', category: 'food', keywords: ['animal', 'bovine', 'semen'] },
  { code: '051191', description: 'Animal products not elsewhere specified or included; dead animals of Chapter ...', chapter: '05', category: 'food', keywords: ['animal', 'products', 'specified', 'included', 'dead', 'animals', 'chapter', 'unfit', 'human', 'consumptionproducts'] },
  { code: '051199', description: 'Animal products not elsewhere specified or included; dead animals of Chapter ...', chapter: '05', category: 'food', keywords: ['animal'] },
];
