// Chapter 06: Live Trees & Plants -- 16 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_06: HsCodeEntry[] = [
  { code: '060110', description: 'Bulbs, tubers, tuberous roots, corms, crowns and rhizomes, dormant, in growth...', chapter: '06', category: 'plants', keywords: ['plants', 'live', 'bulbs', 'tubers', 'tuberous', 'roots', 'corms', 'crowns', 'rhizomes', 'dormant'] },
  { code: '060120', description: 'Plants, live; bulbs, tubers, tuberous roots, corms, crowns and rhizomes, in growth or in flower, chicory plants and root', chapter: '06', category: 'plants', keywords: ['plants', 'live', 'bulbs', 'tubers', 'tuberous', 'roots', 'corms', 'crowns', 'rhizomes', 'growth', 'flower', 'chicory'] },
  { code: '060210', description: 'Plants, live; unrooted cuttings and slips', chapter: '06', category: 'garden', keywords: ['plants', 'live', 'unrooted', 'cuttings', 'slips'] },
  { code: '060220', description: 'Other live plants (including their roots), cuttings and slips; mushroom spawn...', chapter: '06', category: 'plants', keywords: ['live', 'plants', 'their', 'roots', 'cuttings', 'slips', 'mushroom', 'spawntrees', 'shrubs', 'bushes'] },
  { code: '060230', description: 'Other live plants (including their roots), cuttings and slips; mushroom spawn...', chapter: '06', category: 'plants', keywords: ['plants', 'live', 'rhododendrons', 'azaleas', 'grafted'] },
  { code: '060240', description: 'Other live plants (including their roots), cuttings and slips; mushroom spawn...', chapter: '06', category: 'plants', keywords: ['live', 'plants', 'their', 'roots', 'cuttings', 'slips', 'mushroom', 'spawnroses', 'grafted'] },
  { code: '060290', description: 'Plants, live; n.e.c. in heading no. 0602', chapter: '06', category: 'garden', keywords: ['plants', 'live'] },
  { code: '060311', description: 'Cut flowers and flower buds of a kind suitable for bouquets or for ornamental...', chapter: '06', category: 'plants', keywords: ['cut', 'flowers', 'flower', 'buds', 'kind', 'suitable', 'bouquets', 'ornamental', 'purposes', 'fresh'] },
  { code: '060312', description: 'Flowers, cut; carnations, flowers and buds of a kind suitable for bouquets or ornamental purposes, fresh', chapter: '06', category: 'plants', keywords: ['flowers', 'cut', 'carnations', 'buds', 'suitable', 'bouquets', 'ornamental', 'purposes', 'fresh'] },
  { code: '060313', description: 'Flowers, cut; orchids, flowers and buds of a kind suitable for bouquets or ornamental purposes, fresh', chapter: '06', category: 'plants', keywords: ['flowers', 'cut', 'orchids', 'buds', 'suitable', 'bouquets', 'ornamental', 'purposes', 'fresh'] },
  { code: '060314', description: 'Flowers, cut; chrysanthemums, flowers and buds of a kind suitable for bouquets or ornamental purposes, fresh', chapter: '06', category: 'plants', keywords: ['flowers', 'cut', 'chrysanthemums', 'buds', 'suitable', 'bouquets', 'ornamental', 'purposes', 'fresh'] },
  { code: '060315', description: 'Flowers, cut; lilies (Lilium spp.), flowers and flower buds of a kind suitable for bouquets or ornamental purposes, fres', chapter: '06', category: 'plants', keywords: ['flowers', 'cut', 'lilies', 'lilium', 'spp', 'flower', 'buds', 'suitable', 'bouquets', 'ornamental', 'purposes', 'fresh'] },
  { code: '060319', description: 'Flowers, cut; flowers and buds of a kind suitable for bouquets or ornamental purposes, fresh, other than roses, carnatio', chapter: '06', category: 'plants', keywords: ['flowers', 'cut', 'buds', 'suitable', 'bouquets', 'ornamental', 'purposes', 'fresh', 'roses', 'carnations', 'orchids', 'chrysanthemums', 'lillies'] },
  { code: '060390', description: 'Flowers, cut; flowers and flower buds of a kind suitable for bouquets or ornamental purposes, dried, dyed, bleached, imp', chapter: '06', category: 'plants', keywords: ['flowers', 'cut', 'flower', 'buds', 'suitable', 'bouquets', 'ornamental', 'purposes', 'dried', 'dyed', 'bleached', 'impregnated', 'otherwise', 'prepared'] },
  { code: '060420', description: 'Foliage, branches and other parts of plants, without flowers or flower buds, and grasses, mosses and lichens; suitable f', chapter: '06', category: 'plants', keywords: ['foliage', 'branches', 'plants', 'without', 'flowers', 'flower', 'buds', 'grasses', 'mosses', 'lichens', 'suitable', 'bouquets', 'ornamental', 'purposes', 'fresh'] },
  { code: '060490', description: 'Foliage, branches and other parts of plants, without flowers or flower buds, and grasses, mosses and lichens; suitable f', chapter: '06', category: 'plants', keywords: ['foliage', 'branches', 'plants', 'without', 'flowers', 'flower', 'buds', 'grasses', 'mosses', 'lichens', 'suitable', 'bouquets', 'ornamental', 'purposes', 'dried', 'dyed', 'bleached', 'impregnated', 'otherwise', 'prepared'] },
];
