// Chapter 10: Cereals -- 27 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_10: HsCodeEntry[] = [
  { code: '100111', description: 'Cereals; wheat and meslin, durum wheat, seed', chapter: '10', category: 'food', keywords: ['cereals', 'wheat', 'meslin', 'durum', 'seed'] },
  { code: '100119', description: 'Cereals; wheat and meslin, durum wheat, other than seed', chapter: '10', category: 'food', keywords: ['cereals', 'wheat', 'meslin', 'durum', 'seed'] },
  { code: '100191', description: 'Cereals; wheat and meslin, other than durum wheat, seed', chapter: '10', category: 'food', keywords: ['cereals', 'wheat', 'meslin', 'durum', 'seed'] },
  { code: '100199', description: 'Cereals; wheat and meslin, other than durum wheat, other than seed', chapter: '10', category: 'food', keywords: ['cereals', 'wheat', 'meslin', 'durum', 'seed'] },
  { code: '100210', description: 'Cereals; rye, seed', chapter: '10', category: 'food', keywords: ['cereals', 'rye', 'seed'] },
  { code: '100290', description: 'Cereals; rye, other than seed', chapter: '10', category: 'food', keywords: ['cereals', 'rye', 'seed'] },
  { code: '100310', description: 'Cereals; barley, seed', chapter: '10', category: 'food', keywords: ['cereals', 'barley', 'seed'] },
  { code: '100390', description: 'Cereals; barley, other than seed', chapter: '10', category: 'food', keywords: ['cereals', 'barley', 'seed'] },
  { code: '100410', description: 'Cereals; oats, seeds', chapter: '10', category: 'food', keywords: ['cereals', 'oats', 'seeds'] },
  { code: '100490', description: 'Cereals; oats, other than seed', chapter: '10', category: 'food', keywords: ['cereals', 'oats', 'seed'] },
  { code: '100510', description: 'Maize (corn):Seed:*Hybrid<896>:**Three-cross hybrids', chapter: '10', category: 'food', keywords: ['cereals', 'maize', 'corn', 'seed'] },
  { code: '100590', description: 'Cereals', chapter: '10', category: 'food', keywords: ['grain', 'wheat', 'rice', 'corn', 'barley', 'oat', 'maize'] },
  { code: '100610', description: 'Rice:Rice in the husk (paddy or rough):*For sowing<896>', chapter: '10', category: 'food', keywords: ['cereals', 'rice', 'husk', 'paddy', 'rough'] },
  { code: '100620', description: 'Rice:Husked (brown) rice:*Parboiled:**Round grain', chapter: '10', category: 'food', keywords: ['ricehusked', 'brown', 'riceparboiledround', 'grain'] },
  { code: '100630', description: 'Rice:Semi-milled or wholly milled rice, whether or not polished or glazed:*Se...', chapter: '10', category: 'food', keywords: ['cereals', 'rice', 'semi-milled', 'milled', 'polished', 'glazed'] },
  { code: '100640', description: 'Rice:Broken rice', chapter: '10', category: 'food', keywords: ['ricebroken', 'rice'] },
  { code: '100710', description: 'Grain sorghum:Seed:*Hybrids<896>', chapter: '10', category: 'food', keywords: ['cereals', 'grain', 'sorghum', 'seed'] },
  { code: '100790', description: 'Cereals; grain sorghum, other than seed', chapter: '10', category: 'food', keywords: ['cereals', 'grain', 'sorghum', 'seed'] },
  { code: '100810', description: 'Buckwheat, millet and canary seed; other cereals:Buckwheat', chapter: '10', category: 'food', keywords: ['cereals', 'buckwheat'] },
  { code: '100821', description: 'Buckwheat, millet and canary seed; other cereals:Millet:*Seed', chapter: '10', category: 'food', keywords: ['buckwheat', 'millet', 'canary', 'seed', 'cerealsmilletseed'] },
  { code: '100829', description: 'Buckwheat, millet and canary seed; other cereals:Millet:*Other', chapter: '10', category: 'food', keywords: ['cereals', 'millet', 'seed'] },
  { code: '100830', description: 'Buckwheat, millet and canary seed; other cereals:Canary seed', chapter: '10', category: 'food', keywords: ['buckwheat', 'millet', 'canary', 'seed', 'cerealscanary'] },
  { code: '100840', description: 'Buckwheat, millet and canary seed; other cereals:Fonio (Digitaria spp.)', chapter: '10', category: 'food', keywords: ['cereals', 'fonio', 'digitaria', 'spp'] },
  { code: '100850', description: 'Buckwheat, millet and canary seed; other cereals:Quinoa (Chenopodium quinoa)', chapter: '10', category: 'food', keywords: ['buckwheat', 'millet', 'canary', 'seed', 'cerealsquinoa', 'chenopodium', 'quinoa'] },
  { code: '100860', description: 'Buckwheat, millet and canary seed; other cereals:Triticale', chapter: '10', category: 'food', keywords: ['cereals', 'triticale'] },
  { code: '100890', description: 'Buckwheat, millet and canary seed; other cereals:Other cereals', chapter: '10', category: 'food', keywords: ['buckwheat', 'millet', 'canary', 'seed', 'cereals', 'cereals'] },
  { code: '101140', description: 'Rice', chapter: '10', category: 'food', keywords: ['rice', 'white rice', 'brown rice', 'jasmine rice', 'basmati rice'] },
];
