// Chapter 17: Sugars & Confectionery -- 19 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_17: HsCodeEntry[] = [
  { code: '170111', description: 'Raw cane sugar', chapter: '17', category: 'food', keywords: ['sugar', 'cane sugar', 'raw sugar', 'brown sugar'] },
  { code: '170112', description: 'Sugars; beet sugar, raw, in solid form, not containing added flavouring or colouring matter', chapter: '17', category: 'food', keywords: ['sugars', 'beet', 'sugar', 'raw', 'solid', 'added', 'flavouring', 'colouring', 'matter'] },
  { code: '170113', description: 'Sugars; cane sugar, raw, in solid form, as specified in Subheading Note 2 to this chapter, not containing added flavouri', chapter: '17', category: 'food', keywords: ['sugars', 'cane', 'sugar', 'raw', 'solid', 'note', 'added', 'flavouring', 'colouring', 'matter'] },
  { code: '170114', description: 'Sugars; cane sugar, raw, in solid form, other than as specified in Subheading Note 2 to this chapter, not containing add', chapter: '17', category: 'food', keywords: ['sugars', 'cane', 'sugar', 'raw', 'solid', 'note', 'added', 'flavouring', 'colouring', 'matter'] },
  { code: '170191', description: 'Sugars; sucrose, chemically pure, in solid form, containing added flavouring or colouring matter', chapter: '17', category: 'food', keywords: ['sugars', 'sucrose', 'chemically', 'pure', 'solid', 'added', 'flavouring', 'colouring', 'matter'] },
  { code: '170199', description: 'Sugars; sucrose, chemically pure, in solid form, not containing added flavouring or colouring matter', chapter: '17', category: 'food', keywords: ['sugars', 'sucrose', 'chemically', 'pure', 'solid', 'added', 'flavouring', 'colouring', 'matter'] },
  { code: '170210', description: 'Lactose', chapter: '17', category: 'food', keywords: ['lactose', 'milk sugar', 'dairy ingredient'] },
  { code: '170211', description: 'Sugars; lactose and lactose syrup, containing by weight 99% or more lactose, expressed as anhydrous lactose, calculated ', chapter: '17', category: 'food', keywords: ['sugars', 'lactose', 'syrup', 'weight', '99%', 'expressed', 'anhydrous', 'calculated', 'dry', 'matter'] },
  { code: '170219', description: 'Sugars; lactose and lactose syrup, containing by weight less than 99% lactose, expressed as anhydrous lactose, calculate', chapter: '17', category: 'food', keywords: ['sugars', 'lactose', 'syrup', 'weight', '99%', 'expressed', 'anhydrous', 'calculated', 'dry', 'matter'] },
  { code: '170220', description: 'Sugars; maple sugar, chemically pure, in solid form; maple syrup, not containing added flavouring or colouring matter', chapter: '17', category: 'food', keywords: ['sugars', 'maple', 'sugar', 'chemically', 'pure', 'solid', 'syrup', 'added', 'flavouring', 'colouring', 'matter'] },
  { code: '170230', description: 'Sugars; glucose and glucose syrup, not containing fructose or containing in the dry state less than 20% by weight of fru', chapter: '17', category: 'food', keywords: ['sugars', 'glucose', 'syrup', 'fructose', 'dry', 'state', '20%', 'weight', 'added', 'flavouring', 'colouring', 'matter'] },
  { code: '170240', description: 'Sugars; glucose and glucose syrup, containing in the dry state at least 20% but less than 50% by weight of fructose, exc', chapter: '17', category: 'food', keywords: ['sugars', 'glucose', 'syrup', 'dry', 'state', 'least', '20%', '50%', 'weight', 'fructose', 'invert', 'sugar', 'added', 'flavouring', 'colouring', 'matter'] },
  { code: '170250', description: 'Other sugars, including chemically pure lactose, maltose, glucose and fructos...', chapter: '17', category: 'food', keywords: ['sugars', 'fructose', 'chemically', 'pure', 'solid'] },
  { code: '170260', description: 'Other sugars, including chemically pure lactose, maltose, glucose and fructos...', chapter: '17', category: 'food', keywords: ['sugars', 'chemically', 'pure', 'lactose', 'maltose', 'glucose', 'fructose', 'solid', 'form', 'sugar'] },
  { code: '170290', description: 'Sugars; n.e.c. in heading no. 1702, including invert sugar and other sugar and sugar syrup blends containing, in the dry', chapter: '17', category: 'food', keywords: ['sugars', 'invert', 'sugar', 'syrup', 'blends', 'dry', 'state', '50%', 'weight', 'fructose'] },
  { code: '170310', description: 'Sugars; molasses, from sugar cane, resulting from the extraction or refining of sugar', chapter: '17', category: 'food', keywords: ['sugars', 'molasses', 'from', 'sugar', 'cane', 'resulting', 'extraction', 'refining'] },
  { code: '170390', description: 'Sugars; molasses, from sugar beet, resulting from the extraction or refining of sugar', chapter: '17', category: 'food', keywords: ['sugars', 'molasses', 'from', 'sugar', 'beet', 'resulting', 'extraction', 'refining'] },
  { code: '170410', description: 'Sugar confectionery; chewing gum, whether or not sugar-coated, not containing cocoa', chapter: '17', category: 'food', keywords: ['sugar', 'confectionery', 'chewing', 'gum', 'sugar-coated', 'cocoa'] },
  { code: '170490', description: 'Candy', chapter: '17', category: 'food', keywords: ['candy', 'sweets', 'lollipop', 'hard candy', 'gummy', 'sugar', 'confectionery', 'white', 'chocolate', 'cocoaliquorice'] },
];
