// Chapter 19: Cereal & Bakery Products -- 20 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_19: HsCodeEntry[] = [
  { code: '190110', description: 'Food preparations; of flour, meal, starch, malt extract or milk products, suitable for infants or young children, put up', chapter: '19', category: 'food', keywords: ['food', 'flour', 'meal', 'starch', 'malt', 'extract', 'milk', 'suitable', 'infants', 'young', 'children', 'retail', 'sale'] },
  { code: '190120', description: 'Food preparations; mixes and doughs for the preparation of bread, pastry, cakes, biscuits and other bakers\' wares', chapter: '19', category: 'food', keywords: ['food', 'mixes', 'doughs', 'preparation', 'bread', 'pastry', 'cakes', 'biscuits', 'bakers', 'wares'] },
  { code: '190190', description: 'Food preparations; of flour, meal, starch, malt extract or milk products, for uses n.e.c. in heading no. 1901', chapter: '19', category: 'food', keywords: ['food', 'flour', 'meal', 'starch', 'malt', 'extract', 'milk', 'uses'] },
  { code: '190210', description: 'Pasta', chapter: '19', category: 'food', keywords: ['pasta', 'spaghetti', 'penne', 'noodles', 'macaroni'] },
  { code: '190211', description: 'Food preparations; pasta, containing eggs, uncooked, not stuffed or otherwise prepared', chapter: '19', category: 'food', keywords: ['food', 'pasta', 'eggs', 'uncooked', 'stuffed', 'otherwise', 'prepared'] },
  { code: '190219', description: 'Pasta, whether or not cooked or stuffed (with meat or other substances) or ot...', chapter: '19', category: 'food', keywords: ['pasta', 'cooked', 'stuffed', 'meat', 'substances', 'otherwise', 'prepared', 'such', 'spaghetti', 'macaroni'] },
  { code: '190220', description: 'Food preparations; pasta, stuffed (with meat or other substances), whether or not cooked or otherwise prepared', chapter: '19', category: 'food', keywords: ['food', 'pasta', 'stuffed', 'meat', 'substances', 'cooked', 'otherwise', 'prepared'] },
  { code: '190230', description: 'Pasta, whether or not cooked or stuffed (with meat or other substances) or ot...', chapter: '19', category: 'food', keywords: ['food', 'pasta', 'stuffed', 'cooked', 'otherwise', 'prepared'] },
  { code: '190240', description: 'Pasta, whether or not cooked or stuffed (with meat or other substances) or ot...', chapter: '19', category: 'food', keywords: ['pasta', 'cooked', 'stuffed', 'meat', 'substances', 'otherwise', 'prepared', 'such', 'spaghetti', 'macaroni'] },
  { code: '190300', description: 'Food preparations; tapioca and substitutes thereof, prepared from starch in the form of flakes, grains, pearls, siftings', chapter: '19', category: 'food', keywords: ['food', 'tapioca', 'substitutes', 'prepared', 'from', 'starch', 'flakes', 'grains', 'pearls', 'siftings'] },
  { code: '190410', description: 'Food preparations; obtained by the swelling or roasting of cereals or cereal products', chapter: '19', category: 'food', keywords: ['food', 'swelling', 'roasting', 'cereals', 'cereal'] },
  { code: '190420', description: 'Food preparations; obtained from unroasted cereal flakes or from mixtures of unroasted cereal flakes and roasted cereal ', chapter: '19', category: 'food', keywords: ['food', 'from', 'unroasted', 'cereal', 'flakes', 'mixtures', 'roasted', 'swelled', 'cereals'] },
  { code: '190430', description: 'Prepared foods obtained by the swelling or roasting of cereals or cereal products (e.g. corn flakes); cereals, not maize', chapter: '19', category: 'food', keywords: ['prepared', 'foods', 'swelling', 'roasting', 'cereals', 'cereal', 'e.g', 'corn', 'flakes', 'maize', 'grain', 'worked', 'grains', 'from', 'bulgur', 'wheat'] },
  { code: '190490', description: 'Food preparations; cereal or cereal products (excluding maize), in grain form, pre-cooked or otherwise prepared', chapter: '19', category: 'food', keywords: ['food', 'cereal', 'maize', 'grain', 'pre-cooked', 'otherwise', 'prepared'] },
  { code: '190510', description: 'Food preparations; crispbread, whether or not containing cocoa', chapter: '19', category: 'food', keywords: ['food', 'crispbread', 'cocoa'] },
  { code: '190520', description: 'Biscuits', chapter: '19', category: 'food', keywords: ['biscuit', 'cookie', 'crackers', 'wafer', 'snack', 'bread', 'pastry', 'cakes', 'biscuits', 'bakers'] },
  { code: '190531', description: 'Bread, pastry, cakes, biscuits and other bakers\\ wares, whether or not conta...', chapter: '19', category: 'food', keywords: ['food', 'sweet', 'biscuits', 'cocoa'] },
  { code: '190532', description: 'Bread, pastry, cakes, biscuits and other bakers\\ wares, whether or not conta...', chapter: '19', category: 'food', keywords: ['bread', 'pastry', 'cakes', 'biscuits', 'bakers', 'wares', 'cocoa', 'communion', 'wafers', 'empty'] },
  { code: '190540', description: 'Food preparations; rusks, toasted bread and similar toasted products, whether or not containing cocoa', chapter: '19', category: 'food', keywords: ['food', 'rusks', 'toasted', 'bread', 'cocoa'] },
  { code: '190590', description: 'Pastries', chapter: '19', category: 'food', keywords: ['pastry', 'cake', 'donut', 'croissant', 'dessert', 'bakery', 'bread', 'cakes', 'biscuits', 'bakers'] },
];
