// Chapter 23: Food Industry Residues -- 24 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_23: HsCodeEntry[] = [
  { code: '230110', description: 'Flours, meals and pellets, of meat or meat offal, of fish or of crustaceans, ...', chapter: '23', category: 'food', keywords: ['flours', 'meals', 'pellets', 'meat', 'offal', 'greaves'] },
  { code: '230120', description: 'Flours, meals and pellets, of meat or meat offal, of fish or of crustaceans, ...', chapter: '23', category: 'food', keywords: ['flours', 'meals', 'pellets', 'meat', 'offal', 'fish', 'crustaceans', 'molluscs', 'aquatic', 'invertebrates'] },
  { code: '230210', description: 'Bran, sharps and other residues; of maize (corn), whether or not in the form of pellets, derived from the sifting, milli', chapter: '23', category: 'food', keywords: ['bran', 'sharps', 'residues', 'maize', 'corn', 'pellets', 'derived', 'from', 'sifting', 'milling', 'workings'] },
  { code: '230230', description: 'Bran, sharps and other residues; of wheat, whether or not in the form of pellets, derived from the sifting, milling or o', chapter: '23', category: 'food', keywords: ['bran', 'sharps', 'residues', 'wheat', 'pellets', 'derived', 'from', 'sifting', 'milling', 'workings'] },
  { code: '230240', description: 'Bran, sharps and other residues; of other cereals, whether or not in the form of pellets, derived from the sifting, mill', chapter: '23', category: 'food', keywords: ['bran', 'sharps', 'residues', 'cereals', 'pellets', 'derived', 'from', 'sifting', 'milling', 'workings'] },
  { code: '230250', description: 'Bran, sharps and other residues; of leguminous plants, whether or not in the form of pellets, derived from the sifting, ', chapter: '23', category: 'food', keywords: ['bran', 'sharps', 'residues', 'leguminous', 'plants', 'pellets', 'derived', 'from', 'sifting', 'milling', 'workings'] },
  { code: '230310', description: 'Residues of starch manufacture and similar residues; whether or not in the form of pellets', chapter: '23', category: 'food', keywords: ['residues', 'starch', 'manufacture', 'pellets'] },
  { code: '230320', description: 'Residues of starch manufacture and similar residues, beet-pulp, bagasse and o...', chapter: '23', category: 'food', keywords: ['residues', 'starch', 'manufacture', 'similar', 'beet', 'pulp', 'bagasse', 'waste', 'sugar', 'brewing'] },
  { code: '230330', description: 'Residues of starch manufacture and similar residues, beet-pulp, bagasse and o...', chapter: '23', category: 'food', keywords: ['brewing', 'distilling', 'dregs', 'waste', 'pellets'] },
  { code: '230400', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'soya'] },
  { code: '230500', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of gro', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'ground-nut', 'oil'] },
  { code: '230610', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of cot', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'cotton', 'seed', 'oils'] },
  { code: '230620', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of lin', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'linseed', 'oils'] },
  { code: '230630', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of sun', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'sunflower', 'seed', 'oils'] },
  { code: '230641', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of low', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'low', 'erucic', 'acid', 'rape', 'colza', 'seed', 'oils'] },
  { code: '230649', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of rap', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'rape', 'seed', 'oils', 'low', 'erucic', 'acid', 'colza'] },
  { code: '230650', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of coc', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'coconut', 'copra', 'seed', 'oils'] },
  { code: '230660', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of pal', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'palm', 'nuts', 'kernels', 'oils'] },
  { code: '230690', description: 'Oil-cake and other solid residues; whether or not ground or in the form of pellets, resulting from the extraction of oil', chapter: '23', category: 'food', keywords: ['oil-cake', 'solid', 'residues', 'ground', 'pellets', 'resulting', 'from', 'extraction', 'oils'] },
  { code: '230700', description: 'Wine lees; argol:*Wine lees:**Having a total alcoholic strength by mass not e...', chapter: '23', category: 'food', keywords: ['wine', 'lees', 'argol'] },
  { code: '230800', description: 'Vegetable materials and vegetable waste, vegetable residues and by-products, ...', chapter: '23', category: 'food', keywords: ['vegetable', 'materials', 'waste', 'residues', 'products', 'form', 'pellets', 'kind', 'animal', 'feeding'] },
  { code: '230910', description: 'Dog or cat food; put up for retail sale, used in animal feeding', chapter: '23', category: 'pet', keywords: ['dog', 'cat', 'food', 'retail', 'sale', 'animal', 'feeding'] },
  { code: '230920', description: 'Pet food (cat)', chapter: '23', category: 'pet', keywords: ['cat food', 'cat treat', 'kitten food', 'wet cat food'] },
  { code: '230990', description: 'Preparations of a kind used in animal feeding:Other:*Fish or marine mammal so...', chapter: '23', category: 'food', keywords: ['dog', 'cat', 'food', 'retail', 'sale', 'animal', 'feeding'] },
];
