// Chapter 23: Food Industry Residues -- 24 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_23: HsCodeEntry[] = [
  { code: '230110', description: 'Flours, meals and pellets, of meat or meat offal, of fish or of crustaceans, ...', chapter: '23', category: 'food', keywords: ['flours', 'meals', 'pellets', 'meat', 'offal', 'fish', 'crustaceans', 'molluscs', 'aquatic', 'invertebrates'] },
  { code: '230120', description: 'Flours, meals and pellets, of meat or meat offal, of fish or of crustaceans, ...', chapter: '23', category: 'food', keywords: ['flours', 'meals', 'pellets', 'meat', 'offal', 'fish', 'crustaceans', 'molluscs', 'aquatic', 'invertebrates'] },
  { code: '230210', description: 'Bran, sharps and other residues, whether or not in the form of pellets derive...', chapter: '23', category: 'food', keywords: ['bran', 'sharps', 'residues', 'form', 'pellets', 'derived', 'sifting', 'milling', 'working', 'cereals'] },
  { code: '230230', description: 'Bran, sharps and other residues, whether or not in the form of pellets derive...', chapter: '23', category: 'food', keywords: ['bran', 'sharps', 'residues', 'form', 'pellets', 'derived', 'sifting', 'milling', 'working', 'cereals'] },
  { code: '230240', description: 'Bran, sharps and other residues, whether or not in the form of pellets derive...', chapter: '23', category: 'food', keywords: ['bran', 'sharps', 'residues', 'form', 'pellets', 'derived', 'sifting', 'milling', 'working', 'cereals'] },
  { code: '230250', description: 'Bran, sharps and other residues, whether or not in the form of pellets derive...', chapter: '23', category: 'food', keywords: ['bran', 'sharps', 'residues', 'form', 'pellets', 'derived', 'sifting', 'milling', 'working', 'cereals'] },
  { code: '230310', description: 'Residues of starch manufacture and similar residues, beet-pulp, bagasse and o...', chapter: '23', category: 'food', keywords: ['residues', 'starch', 'manufacture', 'similar', 'beet', 'pulp', 'bagasse', 'waste', 'sugar', 'brewing'] },
  { code: '230320', description: 'Residues of starch manufacture and similar residues, beet-pulp, bagasse and o...', chapter: '23', category: 'food', keywords: ['residues', 'starch', 'manufacture', 'similar', 'beet', 'pulp', 'bagasse', 'waste', 'sugar', 'brewing'] },
  { code: '230330', description: 'Residues of starch manufacture and similar residues, beet-pulp, bagasse and o...', chapter: '23', category: 'food', keywords: ['residues', 'starch', 'manufacture', 'similar', 'beet', 'pulp', 'bagasse', 'waste', 'sugar', 'brewing'] },
  { code: '230400', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'soya'] },
  { code: '230500', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'nut'] },
  { code: '230610', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'vegetable'] },
  { code: '230620', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'vegetable'] },
  { code: '230630', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'vegetable'] },
  { code: '230641', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'vegetable'] },
  { code: '230649', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'vegetable'] },
  { code: '230650', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'vegetable'] },
  { code: '230660', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'vegetable'] },
  { code: '230690', description: 'Oil-cake and other solid residues, whether or not ground or in the form of pe...', chapter: '23', category: 'food', keywords: ['oil', 'cake', 'solid', 'residues', 'ground', 'form', 'pellets', 'resulting', 'extraction', 'vegetable'] },
  { code: '230700', description: 'Wine lees; argol:*Wine lees:**Having a total alcoholic strength by mass not e...', chapter: '23', category: 'food', keywords: ['wine', 'lees', 'argolwine', 'leeshaving', 'total', 'alcoholic', 'strength', 'mass', '79', 'mas'] },
  { code: '230800', description: 'Vegetable materials and vegetable waste, vegetable residues and by-products, ...', chapter: '23', category: 'food', keywords: ['vegetable', 'materials', 'waste', 'residues', 'products', 'form', 'pellets', 'kind', 'animal', 'feeding'] },
  { code: '230910', description: 'Pet food (dog)', chapter: '23', category: 'pet', keywords: ['dog food', 'pet food', 'kibble', 'dog treat', 'puppy food', 'kind', 'animal', 'feedingdog', 'cat', 'food'] },
  { code: '230920', description: 'Pet food (cat)', chapter: '23', category: 'pet', keywords: ['cat food', 'cat treat', 'kitten food', 'wet cat food'] },
  { code: '230990', description: 'Preparations of a kind used in animal feeding:Other:*Fish or marine mammal so...', chapter: '23', category: 'food', keywords: ['kind', 'animal', 'feedingfish', 'marine', 'mammal', 'solubles'] },
];
