// Chapter 26: Ores, Slag, Ash -- 37 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_26: HsCodeEntry[] = [
  { code: '260111', description: 'Iron ores and concentrates, including roasted iron pyrites:Iron ores and conc...', chapter: '26', category: 'minerals', keywords: ['iron', 'ores', 'concentrates', 'roasted', 'pyritesiron', 'pyritesnon', 'agglomerated'] },
  { code: '260112', description: 'Iron ores and concentrates, including roasted iron pyrites:Iron ores and conc...', chapter: '26', category: 'minerals', keywords: ['iron', 'ores', 'concentrates', 'roasted', 'pyritesiron', 'pyritesagglomerated'] },
  { code: '260120', description: 'Iron ores and concentrates, including roasted iron pyrites:Roasted iron pyrites', chapter: '26', category: 'minerals', keywords: ['iron', 'ores', 'concentrates', 'roasted', 'pyritesroasted', 'pyrites'] },
  { code: '260200', description: 'Manganese ores and concentrates, including ferruginous manganese ores and con...', chapter: '26', category: 'minerals', keywords: ['manganese', 'ores', 'concentrates', 'ferruginous', 'calculated', 'dry', 'ecsc'] },
  { code: '260300', description: 'Copper ores and concentrates', chapter: '26', category: 'minerals', keywords: ['copper', 'ores', 'concentrates'] },
  { code: '260400', description: 'Nickel ores and concentrates', chapter: '26', category: 'minerals', keywords: ['nickel', 'ores', 'concentrates'] },
  { code: '260500', description: 'Cobalt ores and concentrates', chapter: '26', category: 'minerals', keywords: ['cobalt', 'ores', 'concentrates'] },
  { code: '260600', description: 'Aluminium ores and concentrates', chapter: '26', category: 'minerals', keywords: ['aluminium', 'ores', 'concentrates'] },
  { code: '260700', description: 'Lead ores and concentrates', chapter: '26', category: 'minerals', keywords: ['lead', 'ores', 'concentrates'] },
  { code: '260800', description: 'Zinc ores and concentrates', chapter: '26', category: 'minerals', keywords: ['zinc', 'ores', 'concentrates'] },
  { code: '260900', description: 'Tin ores and concentrates', chapter: '26', category: 'minerals', keywords: ['tin', 'ores', 'concentrates'] },
  { code: '261000', description: 'Chromium ores and concentrates', chapter: '26', category: 'minerals', keywords: ['chromium', 'ores', 'concentrates'] },
  { code: '261100', description: 'Tungsten ores and concentrates', chapter: '26', category: 'minerals', keywords: ['tungsten', 'ores', 'concentrates'] },
  { code: '261210', description: 'Uranium or thorium ores and concentrates:Uranium ores and concentrates:*Urani...', chapter: '26', category: 'minerals', keywords: ['uranium', 'thorium', 'ores', 'concentratesuranium', 'concentratesuranium', 'pitchblende', 'concentrates', 'aieuratom', '209'] },
  { code: '261220', description: 'Uranium or thorium ores and concentrates:Thorium ores and concentrates:*Monaz...', chapter: '26', category: 'minerals', keywords: ['uranium', 'thorium', 'ores', 'concentratesthorium', 'concentratesmonazite', 'urano', 'thorianite', 'concentrates', 'aieuratom', '209'] },
  { code: '261310', description: 'Molybdenum ores and concentrates:Roasted', chapter: '26', category: 'minerals', keywords: ['molybdenum', 'ores', 'concentratesroasted'] },
  { code: '261390', description: 'Molybdenum ores and concentrates:Other', chapter: '26', category: 'minerals', keywords: ['molybdenum', 'ores', 'concentrates'] },
  { code: '261400', description: 'Titanium ores and concentrates', chapter: '26', category: 'minerals', keywords: ['titanium', 'ores', 'concentrates'] },
  { code: '261510', description: 'Niobium, tantalum, vanadium or zirconium ores and concentrates:Zirconium ores...', chapter: '26', category: 'minerals', keywords: ['niobium', 'tantalum', 'vanadium', 'zirconium', 'ores', 'concentrateszirconium', 'concentrates'] },
  { code: '261590', description: 'Niobium, tantalum, vanadium or zirconium ores and concentrates:Other', chapter: '26', category: 'minerals', keywords: ['niobium', 'tantalum', 'vanadium', 'zirconium', 'ores', 'concentrates'] },
  { code: '261610', description: 'Precious-metal ores and concentrates:Silver ores and concentrates', chapter: '26', category: 'minerals', keywords: ['precious', 'metal', 'ores', 'concentratessilver', 'concentrates'] },
  { code: '261690', description: 'Precious-metal ores and concentrates:Other', chapter: '26', category: 'minerals', keywords: ['precious', 'metal', 'ores', 'concentrates'] },
  { code: '261710', description: 'Other ores and concentrates:Antimony ores and concentrates', chapter: '26', category: 'minerals', keywords: ['ores', 'concentratesantimony', 'concentrates'] },
  { code: '261790', description: 'Other ores and concentrates:Other', chapter: '26', category: 'minerals', keywords: ['ores', 'concentrates'] },
  { code: '261800', description: 'Granulated slag (slag sand) from the manufacture of iron or steel', chapter: '26', category: 'minerals', keywords: ['granulated', 'slag', 'sand', 'manufacture', 'iron', 'steel'] },
  { code: '261900', description: 'Slag, dross (other than granulated slag), scalings and other waste from the m...', chapter: '26', category: 'minerals', keywords: ['slag', 'dross', 'granulated', 'scalings', 'waste', 'manufacture', 'iron', 'steelwaste', 'suitable', 'recovery'] },
  { code: '262011', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262019', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262021', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262029', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262030', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262040', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262060', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262091', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262099', description: 'Slag, ash and residues (other than from the manufacture of iron or steel), co...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'residues', 'manufacture', 'iron', 'steel', 'metals', 'arsenic', 'their', 'compoundscontaining'] },
  { code: '262110', description: 'Other slag and ash, including seaweed ash (kelp); ash and residues from the i...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'seaweed', 'kelp', 'residues', 'incineration', 'municiple', 'wasteash', 'waste'] },
  { code: '262190', description: 'Other slag and ash, including seaweed ash (kelp); ash and residues from the i...', chapter: '26', category: 'minerals', keywords: ['slag', 'ash', 'seaweed', 'kelp', 'residues', 'incineration', 'municiple', 'waste'] },
];
