// Chapter 31: Fertilizers -- 23 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_31: HsCodeEntry[] = [
  { code: '310100', description: 'Fertilizers, animal or vegetable; whether or not mixed together or chemically treated; fertilizers, produced by the mixi', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'animal', 'vegetable', 'mixed', 'together', 'chemically', 'treated', 'produced', 'mixing', 'chemical', 'treatment'] },
  { code: '310210', description: 'Fertilizers, mineral or chemical; nitrogenous, urea, whether or not in aqueous solution', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'nitrogenous', 'urea', 'aqueous', 'solution'] },
  { code: '310221', description: 'Mineral or chemical fertilisers, nitrogenous:Ammonium sulphate; double salts ...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousammonium', 'sulphate', 'double', 'salts', 'mixtures', 'ammonium', 'nitrateammonium'] },
  { code: '310229', description: 'Mineral or chemical fertilisers, nitrogenous:Ammonium sulphate; double salts ...', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'nitrogenous', 'ammonium', 'sulphate'] },
  { code: '310230', description: 'Mineral or chemical fertilisers, nitrogenous:Ammonium nitrate, whether or not...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousammonium', 'nitrate', 'aqueous', 'solutionin', 'solution'] },
  { code: '310240', description: 'Fertilizers, mineral or chemical; ammonium nitrate with calcium carbonate or other inorganic non-fertilizing substances,', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'ammonium', 'nitrate', 'calcium', 'carbonate', 'inorganic', 'non-fertilizing', 'substances', 'mixtures'] },
  { code: '310250', description: 'Fertilizers, mineral or chemical; nitrogenous, sodium nitrate', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'nitrogenous', 'sodium', 'nitrate'] },
  { code: '310260', description: 'Fertilizers, mineral or chemical; nitrogenous, double salts and mixtures of calcium nitrate and ammonium nitrate', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'nitrogenous', 'double', 'salts', 'mixtures', 'calcium', 'nitrate', 'ammonium'] },
  { code: '310280', description: 'Fertilizers, mineral or chemical; nitrogenous, mixtures of urea and ammonium nitrate in aqueous or ammoniacal solution', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'nitrogenous', 'mixtures', 'urea', 'ammonium', 'nitrate', 'aqueous', 'ammoniacal', 'solution'] },
  { code: '310290', description: 'Fertilizers, mineral or chemical; nitrogenous, other kinds including mixtures not specified in the foregoing subheadings', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'nitrogenous', 'kinds', 'mixtures', 'foregoing', 'subheadings'] },
  { code: '310310', description: 'Mineral or chemical fertilisers, phosphatic:Superphosphates:*Containing more ...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'phosphaticsuperphosphatescontaining', '35', 'diphosphorus', 'pentaoxide'] },
  { code: '310390', description: 'Fertilizers, mineral or chemical; phosphatic, n.e.c. in heading no. 3103', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'phosphatic'] },
  { code: '310420', description: 'Mineral or chemical fertilisers, potassic:Potassium chloride:*With a potassiu...', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'potassic', 'potassium', 'chloride'] },
  { code: '310430', description: 'Mineral or chemical fertilisers, potassic:Potassium sulphate', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'potassicpotassium', 'sulphate'] },
  { code: '310490', description: 'Fertilizers, mineral or chemical; potassic, n.e.c. in heading no. 3104', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'potassic'] },
  { code: '310510', description: 'Fertilizers, mineral or chemical; in tablets or similar forms or in packages of a gross weight not exceeding 10kg', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'tablets', 'packages', 'gross', 'weight', 'exceeding', '10kg'] },
  { code: '310520', description: 'Fertilizers, mineral or chemical; containing the three fertilizing elements nitrogen, phosphorus and potassium', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'three', 'fertilizing', 'elements', 'nitrogen', 'phosphorus', 'potassium'] },
  { code: '310530', description: 'Fertilizers, mineral or chemical; diammonium hydrogenorthophosphate (diammonium phosphate)', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'diammonium', 'hydrogenorthophosphate', 'phosphate'] },
  { code: '310540', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310551', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'nitrates', 'phosphates'] },
  { code: '310559', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310560', description: 'Fertilizers, mineral or chemical; containing the two fertilizing elements phosphorus and potassium', chapter: '31', category: 'chemicals', keywords: ['fertilizers', 'mineral', 'chemical', 'two', 'fertilizing', 'elements', 'phosphorus', 'potassium'] },
  { code: '310590', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
];
