// Chapter 31: Fertilizers -- 23 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_31: HsCodeEntry[] = [
  { code: '310100', description: 'Animal or vegetable fertilisers, whether or not mixed together or chemically ...', chapter: '31', category: 'chemicals', keywords: ['animal', 'vegetable', 'fertilisers', 'mixed', 'together', 'chemically', 'treated', 'produced', 'mixing', 'chemical'] },
  { code: '310210', description: 'Mineral or chemical fertilisers, nitrogenous:Urea, whether or not in aqueous ...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousurea', 'aqueous', 'solutionurea', 'nitrogen', 'dry', 'anhydrous', 'product'] },
  { code: '310221', description: 'Mineral or chemical fertilisers, nitrogenous:Ammonium sulphate; double salts ...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousammonium', 'sulphate', 'double', 'salts', 'mixtures', 'ammonium', 'nitrateammonium'] },
  { code: '310229', description: 'Mineral or chemical fertilisers, nitrogenous:Ammonium sulphate; double salts ...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousammonium', 'sulphate', 'double', 'salts', 'mixtures', 'ammonium', 'nitrate'] },
  { code: '310230', description: 'Mineral or chemical fertilisers, nitrogenous:Ammonium nitrate, whether or not...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousammonium', 'nitrate', 'aqueous', 'solutionin', 'solution'] },
  { code: '310240', description: 'Mineral or chemical fertilisers, nitrogenous:Mixtures of ammonium nitrate wit...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousmixtures', 'ammonium', 'nitrate', 'calcium', 'carbonate', 'inorganic', 'non'] },
  { code: '310250', description: 'Mineral or chemical fertilisers, nitrogenous:Sodium nitrate', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenoussodium', 'nitrate'] },
  { code: '310260', description: 'Mineral or chemical fertilisers, nitrogenous:Double salts and mixtures of cal...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousdouble', 'salts', 'mixtures', 'calcium', 'nitrate', 'ammonium'] },
  { code: '310280', description: 'Mineral or chemical fertilisers, nitrogenous:Mixtures of urea and ammonium ni...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenousmixtures', 'urea', 'ammonium', 'nitrate', 'aqueous', 'ammoniacal', 'solution'] },
  { code: '310290', description: 'Mineral or chemical fertilisers, nitrogenous:Other, including mixtures not sp...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'nitrogenous', 'mixtures', 'specified', 'foregoing', 'subheadings'] },
  { code: '310310', description: 'Mineral or chemical fertilisers, phosphatic:Superphosphates:*Containing more ...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'phosphaticsuperphosphatescontaining', '35', 'diphosphorus', 'pentaoxide'] },
  { code: '310390', description: 'Mineral or chemical fertilisers, phosphatic:Other', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'phosphatic'] },
  { code: '310420', description: 'Mineral or chemical fertilisers, potassic:Potassium chloride:*With a potassiu...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'potassicpotassium', 'chloridewith', 'potassium', 'evaluated', 'kah2o', 'dry', 'anhydrous'] },
  { code: '310430', description: 'Mineral or chemical fertilisers, potassic:Potassium sulphate', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'potassicpotassium', 'sulphate'] },
  { code: '310490', description: 'Mineral or chemical fertilisers, potassic:Other', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'potassic'] },
  { code: '310510', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310520', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310530', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310540', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310551', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310559', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310560', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
  { code: '310590', description: 'Mineral or chemical fertilisers containing two or three of the fertilising el...', chapter: '31', category: 'chemicals', keywords: ['mineral', 'chemical', 'fertilisers', 'three', 'fertilising', 'elements', 'nitrogen', 'phosphorus', 'potassium', 'goods'] },
];
