// Chapter 35: Albuminoidal Substances -- 15 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_35: HsCodeEntry[] = [
  { code: '350110', description: 'Casein, caseinates and other casein derivatives; casein glues:Casein:*For the...', chapter: '35', category: 'chemicals', keywords: ['casein', 'caseinates', 'derivatives', 'gluescaseinfor', 'manufacture', 'regenerated', 'textile', 'fibres961867'] },
  { code: '350190', description: 'Casein, caseinates and other casein derivatives; casein glues:Other:*Casein g...', chapter: '35', category: 'chemicals', keywords: ['casein', 'caseinates', 'derivatives', 'gluescasein', 'glues'] },
  { code: '350211', description: 'Albumins (including concentrates of two  or more whey proteins, containing by...', chapter: '35', category: 'chemicals', keywords: ['albumins', 'concentrates', 'whey', 'proteins', '80', 'calculated', 'dry', 'matter', 'albuminates', 'albumin'] },
  { code: '350219', description: 'Albumins (including concentrates of two  or more whey proteins, containing by...', chapter: '35', category: 'chemicals', keywords: ['albumins', 'concentrates', 'whey', 'proteins', '80', 'calculated', 'dry', 'matter', 'albuminates', 'albumin'] },
  { code: '350220', description: 'Albumins (including concentrates of two  or more whey proteins, containing by...', chapter: '35', category: 'chemicals', keywords: ['albumins', 'concentrates', 'whey', 'proteins', '80', 'calculated', 'dry', 'matter', 'albuminates', 'albumin'] },
  { code: '350290', description: 'Albumins (including concentrates of two  or more whey proteins, containing by...', chapter: '35', category: 'chemicals', keywords: ['albumins', 'concentrates', 'whey', 'proteins', '80', 'calculated', 'dry', 'matter', 'albuminates', 'albumin'] },
  { code: '350300', description: 'Gelatin (including gelatin in rectangular (including square) sheets, whether ...', chapter: '35', category: 'chemicals', keywords: ['gelatin', 'rectangular', 'square', 'sheets', 'surface', 'worked', 'coloured', 'derivatives', 'isinglass', 'glues'] },
  { code: '350400', description: 'Peptones and protein substances (industrial)', chapter: '35', category: 'chemicals', keywords: ['peptone', 'casein', 'gelatin', 'protein isolate', 'albumin', 'hydrolysate', 'collagen peptide'] },
  { code: '350510', description: 'Dextrins and other modified starches (for example, pregelatinised or esterifi...', chapter: '35', category: 'chemicals', keywords: ['dextrins', 'modified', 'starches', 'example', 'pregelatinised', 'esterified', 'glues', 'based', 'starchesdextrins', 'starchesdextrins'] },
  { code: '350520', description: 'Dextrins and other modified starches (for example, pregelatinised or esterifi...', chapter: '35', category: 'chemicals', keywords: ['dextrins', 'modified', 'starches', 'example', 'pregelatinised', 'esterified', 'glues', 'based', 'starchesgluescontaining'] },
  { code: '350610', description: 'Prepared glues and other prepared adhesives, not elsewhere specified or inclu...', chapter: '35', category: 'chemicals', keywords: ['prepared', 'glues', 'adhesives', 'specified', 'included', 'products', 'suitable', 'retail', 'sale', 'net'] },
  { code: '350691', description: 'Prepared glues and other prepared adhesives, not elsewhere specified or inclu...', chapter: '35', category: 'chemicals', keywords: ['prepared', 'glues', 'adhesives', 'specified', 'included', 'products', 'suitable', 'retail', 'sale', 'net'] },
  { code: '350699', description: 'Prepared glues and other prepared adhesives, not elsewhere specified or inclu...', chapter: '35', category: 'chemicals', keywords: ['prepared', 'glues', 'adhesives', 'specified', 'included', 'products', 'suitable', 'retail', 'sale', 'net'] },
  { code: '350710', description: 'Enzymes; prepared enzymes not elsewhere specified or included:Rennet and conc...', chapter: '35', category: 'chemicals', keywords: ['enzymes', 'prepared', 'specified', 'includedrennet', 'concentrates'] },
  { code: '350790', description: 'Enzymes; prepared enzymes not elsewhere specified or included:Other:*Lipoprot...', chapter: '35', category: 'chemicals', keywords: ['enzymes', 'prepared', 'specified', 'includedlipoprotein', 'lipase', 'aspergillus', 'alkaline', 'protease'] },
];
