// Chapter 42: Leather Goods -- 22 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_42: HsCodeEntry[] = [
  { code: '420100', description: 'Saddlery and harness; for any animal (including traces, leads, knee pads, muzzles, saddle cloths, saddle bags, dog coats', chapter: '42', category: 'pet', keywords: ['saddlery', 'harness', 'animal', 'traces', 'leads', 'knee', 'pads', 'muzzles', 'saddle', 'cloths', 'bags', 'dog', 'coats', 'materials'] },
  { code: '420110', description: 'Saddlery', chapter: '42', category: 'accessories', keywords: ['saddle', 'horse tack', 'bridle', 'equestrian'] },
  { code: '420210', description: 'Bags, cases & accessories', chapter: '42', category: 'bags', keywords: ['handbag', 'purse', 'wallet', 'backpack', 'luggage', 'suitcase', 'bag', 'tote', 'clutch', 'briefcase', 'phone case', 'smartphone case', 'laptop bag', 'leather handbag', 'tablet case'] },
  { code: '420211', description: 'Cases and containers; trunks, suit-cases, vanity-cases, executive-cases, brief-cases, school satchels and similar contai', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'trunks', 'suit-cases', 'vanity-cases', 'executive-cases', 'brief-cases', 'school', 'satchels', 'outer', 'surface', 'leather', 'composition'] },
  { code: '420212', description: 'Cases and containers; trunks, suit-cases, vanity-cases, executive-cases, brief-cases, school satchels and similar contai', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'trunks', 'suit-cases', 'vanity-cases', 'executive-cases', 'brief-cases', 'school', 'satchels', 'outer', 'surface', 'plastics', 'textile', 'materials'] },
  { code: '420219', description: 'Cases and containers; trunks, suit-cases, vanity-cases, executive-cases, brief-cases, school satchels and similar contai', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'trunks', 'suit-cases', 'vanity-cases', 'executive-cases', 'brief-cases', 'school', 'satchels', 'vulcanised', 'fibre', 'paperboard', 'materials', 'paper'] },
  { code: '420221', description: 'Cases and containers; handbags (whether or not with shoulder strap and including those without handle), with outer surfa', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'handbags', 'shoulder', 'strap', 'without', 'handle', 'outer', 'surface', 'leather', 'composition'] },
  { code: '420222', description: 'Cases and containers; handbags (whether or not with shoulder strap and including those without handle), with outer surfa', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'handbags', 'shoulder', 'strap', 'without', 'handle', 'outer', 'surface', 'sheeting', 'plastics', 'textile', 'materials'] },
  { code: '420229', description: 'Cases and containers; handbags (whether or not with shoulder strap and including those without handle), of vulcanised fi', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'handbags', 'shoulder', 'strap', 'without', 'handle', 'vulcanised', 'fibre', 'paperboard', 'materials', 'paper'] },
  { code: '420231', description: 'Cases and containers; of a kind normally carried in the pocket or in the handbag, with outer surface of leather or of co', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'normally', 'carried', 'pocket', 'handbag', 'outer', 'surface', 'leather', 'composition'] },
  { code: '420232', description: 'Cases and containers; of a kind normally carried in the pocket or in the handbag, with outer surface of sheeting of plas', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'normally', 'carried', 'pocket', 'handbag', 'outer', 'surface', 'sheeting', 'plastics', 'textile', 'materials'] },
  { code: '420239', description: 'Cases and containers; of a kind normally carried in the pocket or in the handbag, of vulcanised fibre or of paperboard, ', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'normally', 'carried', 'pocket', 'handbag', 'vulcanised', 'fibre', 'paperboard', 'materials', 'paper'] },
  { code: '420291', description: 'Cases and containers; n.e.c. in heading 4202, with outer surface of leather or of composition leather', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'outer', 'surface', 'leather', 'composition'] },
  { code: '420292', description: 'Cases and containers; n.e.c. in heading 4202, with outer surface of sheeting of plastics or of textile materials', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'outer', 'surface', 'sheeting', 'plastics', 'textile', 'materials'] },
  { code: '420299', description: 'Cases and containers; n.e.c. in heading 4202, of vulcanised fibre or of paperboard, or wholly or mainly covered with suc', chapter: '42', category: 'leather', keywords: ['cases', 'containers', 'vulcanised', 'fibre', 'paperboard', 'materials', 'paper'] },
  { code: '420310', description: 'Apparel; articles of apparel, of leather or of composition leather', chapter: '42', category: 'accessories', keywords: ['apparel', 'leather', 'composition'] },
  { code: '420321', description: 'Clothing accessories; gloves, mittens and mitts, specially designed for use in sports, of leather or composition leather', chapter: '42', category: 'leather', keywords: ['clothing', 'gloves', 'mittens', 'mitts', 'specially', 'designed', 'use', 'sports', 'leather', 'composition', 'padded'] },
  { code: '420329', description: 'Clothing accessories; gloves, mittens and mitts, n.e.c. in heading no. 4203, of leather or composition leather, not spec', chapter: '42', category: 'leather', keywords: ['clothing', 'gloves', 'mittens', 'mitts', 'leather', 'composition', 'specially', 'designed', 'use', 'sports'] },
  { code: '420330', description: 'Articles of apparel and clothing accessories, of leather or of composition le...', chapter: '42', category: 'leather', keywords: ['clothing', 'belts', 'bandoliers', 'leather', 'composition'] },
  { code: '420340', description: 'Clothing accessories; of leather or of composition leather, n.e.c. in heading no. 4203', chapter: '42', category: 'leather', keywords: ['clothing', 'leather', 'composition'] },
  { code: '420500', description: 'Leather articles; n.e.c. in chapter 42, of leather or composition leather', chapter: '42', category: 'apparel', keywords: ['leather', 'composition'] },
  { code: '420600', description: 'Articles of gut (other than silk-worm gut), of goldbeater\'s skin, of bladders or of tendons', chapter: '42', category: 'leather', keywords: ['gut', 'silk-worm', 'goldbeater\'s', 'skin', 'bladders', 'tendons'] },
];
