// Chapter 42: Leather Goods -- 22 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_42: HsCodeEntry[] = [
  { code: '420100', description: 'Pet collars & leashes', chapter: '42', category: 'pet', keywords: ['dog collar', 'pet leash', 'cat collar', 'pet harness', 'dog harness', 'saddlery', 'harness', 'animal', 'traces', 'leads'] },
  { code: '420110', description: 'Saddlery', chapter: '42', category: 'accessories', keywords: ['saddle', 'horse tack', 'bridle', 'equestrian'] },
  { code: '420210', description: 'Trunks, suitcases, bags', chapter: '42', category: 'bags', keywords: ['handbag', 'purse', 'wallet', 'backpack', 'luggage', 'suitcase', 'bag', 'tote', 'clutch', 'briefcase'] },
  { code: '420211', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420212', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420219', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420221', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420222', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420229', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420231', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420232', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420239', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420291', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420292', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420299', description: 'Trunks, suitcases, vanity cases, executive-cases, briefcases, school satchels...', chapter: '42', category: 'leather', keywords: ['trunks', 'suitcases', 'vanity', 'cases', 'executive', 'briefcases', 'school', 'satchels', 'spectacle', 'binocular'] },
  { code: '420310', description: 'Belts', chapter: '42', category: 'accessories', keywords: ['belt', 'leather belt', 'dress belt', 'casual belt', 'apparel', 'clothing', 'accessories', 'leather', 'composition', 'leather'] },
  { code: '420321', description: 'Articles of apparel and clothing accessories, of leather or of composition le...', chapter: '42', category: 'leather', keywords: ['apparel', 'clothing', 'accessories', 'leather', 'composition', 'leathergloves', 'mittens', 'mittsspecially', 'designed', 'sports'] },
  { code: '420329', description: 'Articles of apparel and clothing accessories, of leather or of composition le...', chapter: '42', category: 'leather', keywords: ['apparel', 'clothing', 'accessories', 'leather', 'composition', 'leathergloves', 'mittens', 'mittsprotective', 'trades'] },
  { code: '420330', description: 'Articles of apparel and clothing accessories, of leather or of composition le...', chapter: '42', category: 'leather', keywords: ['apparel', 'clothing', 'accessories', 'leather', 'composition', 'leatherbelts', 'bandoliers'] },
  { code: '420340', description: 'Articles of apparel and clothing accessories, of leather or of composition le...', chapter: '42', category: 'leather', keywords: ['apparel', 'clothing', 'accessories', 'leather', 'composition', 'leather'] },
  { code: '420500', description: 'Clothing articles', chapter: '42', category: 'apparel', keywords: ['leather jacket', 'leather pants', 'leather vest', 'leather coat', 'leather', 'composition', 'leatherof', 'kind', 'machinery', 'mechanical'] },
  { code: '420600', description: 'Articles of gut (other than silk-worm gut), of goldbeater\\s skin, of bladder...', chapter: '42', category: 'leather', keywords: ['gut', 'silk', 'worm', 'goldbeaters', 'skin', 'bladders', 'tendons'] },
];
