// Chapter 46: Basketwork -- 13 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_46: HsCodeEntry[] = [
  { code: '460110', description: 'Baskets', chapter: '46', category: 'home', keywords: ['basket', 'wicker basket', 'storage basket', 'decorative basket', 'picnic basket'] },
  { code: '460121', description: 'Plaiting materials, plaits and similar products of plaiting materials; mats, matting and screens, of bamboo', chapter: '46', category: 'straw', keywords: ['plaiting', 'materials', 'plaits', 'mats', 'matting', 'screens', 'bamboo'] },
  { code: '460122', description: 'Plaits and similar products of plaiting materials, whether or not assembled i...', chapter: '46', category: 'straw', keywords: ['plaits', 'similar', 'products', 'plaiting', 'materials', 'assembled', 'strips', 'bound', 'together', 'parallel'] },
  { code: '460129', description: 'Plaiting materials, plaits and similar products of plaiting materials; mats, matting and screens, of vegetable materials', chapter: '46', category: 'straw', keywords: ['plaiting', 'materials', 'plaits', 'mats', 'matting', 'screens', 'vegetable', 'bamboo', 'rattan'] },
  { code: '460190', description: 'Other wicker articles', chapter: '46', category: 'home', keywords: ['wicker furniture', 'rattan chair', 'woven furniture', 'basket weave'] },
  { code: '460192', description: 'Plaiting materials, plaits and similar products of plaiting materials; (not mats, matting or screens), of bamboo', chapter: '46', category: 'straw', keywords: ['plaiting', 'materials', 'plaits', 'mats', 'matting', 'screens', 'bamboo'] },
  { code: '460193', description: 'Plaits and similar products of plaiting materials, whether or not assembled i...', chapter: '46', category: 'straw', keywords: ['plaits', 'similar', 'products', 'plaiting', 'materials', 'assembled', 'strips', 'bound', 'together', 'parallel'] },
  { code: '460194', description: 'Plaiting materials, plaits and similar products of plaiting materials; (not mats, matting or screens), of vegetable mate', chapter: '46', category: 'straw', keywords: ['plaiting', 'materials', 'plaits', 'mats', 'matting', 'screens', 'vegetable', 'bamboo', 'rattan'] },
  { code: '460199', description: 'Plaiting materials, plaits and similar products of plaiting materials; products of non-vegetable materials', chapter: '46', category: 'straw', keywords: ['plaiting', 'materials', 'plaits', 'non-vegetable'] },
  { code: '460211', description: 'Basketwork, wickerwork and other articles, made directly to shape from plaiti...', chapter: '46', category: 'straw', keywords: ['basketwork', 'wickerwork', 'directly', 'shape', 'plaiting', 'materials', 'goods', 'heading', '4601', 'loofahof'] },
  { code: '460212', description: 'Basketwork, wickerwork and other articles; of rattan, made directly to shape from plaiting materials or made up from goo', chapter: '46', category: 'straw', keywords: ['basketwork', 'wickerwork', 'rattan', 'directly', 'shape', 'from', 'plaiting', 'materials'] },
  { code: '460219', description: 'Basketwork, wickerwork and other articles; of vegetable materials (not bamboo or rattan), made directly to shape from pl', chapter: '46', category: 'straw', keywords: ['basketwork', 'wickerwork', 'vegetable', 'materials', 'bamboo', 'rattan', 'directly', 'shape', 'from', 'plaiting', 'loofah'] },
  { code: '460290', description: 'Basketwork, wickerwork and other articles; of non-vegetable materials, made directly to shape from plaiting materials or', chapter: '46', category: 'straw', keywords: ['basketwork', 'wickerwork', 'non-vegetable', 'materials', 'directly', 'shape', 'from', 'plaiting'] },
];
