// Chapter 47: Wood Pulp -- 21 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_47: HsCodeEntry[] = [
  { code: '470100', description: 'Mechanical wood pulp:*Thermo-mechanical wood pulp', chapter: '47', category: 'paper', keywords: ['mechanical', 'wood', 'pulpthermo', 'pulp'] },
  { code: '470200', description: 'Chemical wood pulp, dissolving grades', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'dissolving', 'grades'] },
  { code: '470311', description: 'Chemical wood pulp, soda or sulphate, other than dissolving grades:Unbleached...', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'soda', 'sulphate', 'dissolving', 'gradesunbleachedconiferous'] },
  { code: '470319', description: 'Chemical wood pulp, soda or sulphate, other than dissolving grades:Unbleached...', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'soda', 'sulphate', 'dissolving', 'gradesunbleachednon', 'coniferous'] },
  { code: '470321', description: 'Chemical wood pulp, soda or sulphate, other than dissolving grades:Semi-bleac...', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'soda', 'sulphate', 'dissolving', 'gradessemi', 'bleached', 'bleachedconiferous'] },
  { code: '470329', description: 'Chemical wood pulp, soda or sulphate, other than dissolving grades:Semi-bleac...', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'soda', 'sulphate', 'dissolving', 'gradessemi', 'bleached', 'bleachednon', 'coniferous'] },
  { code: '470411', description: 'Chemical wood pulp, sulphite, other than dissolving grades:Unbleached:*Conife...', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'sulphite', 'dissolving', 'gradesunbleachedconiferous'] },
  { code: '470419', description: 'Chemical wood pulp, sulphite, other than dissolving grades:Unbleached:*Non-co...', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'sulphite', 'dissolving', 'gradesunbleachednon', 'coniferous'] },
  { code: '470421', description: 'Chemical wood pulp, sulphite, other than dissolving grades:Semi-bleached or b...', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'sulphite', 'dissolving', 'gradessemi', 'bleached', 'bleachedconiferous'] },
  { code: '470429', description: 'Chemical wood pulp, sulphite, other than dissolving grades:Semi-bleached or b...', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'sulphite', 'dissolving', 'gradessemi', 'bleached', 'bleachednon', 'coniferous'] },
  { code: '470500', description: 'Wood pulp obtained by a combination of mechanical and chemical pulping processes', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'obtained', 'combination', 'mechanical', 'chemical', 'pulping', 'processes'] },
  { code: '470610', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulps', 'fibres', 'derived', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'fibrous', 'cellulosic'] },
  { code: '470620', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulps', 'fibres', 'derived', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'fibrous', 'cellulosic'] },
  { code: '470630', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulps', 'fibres', 'derived', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'fibrous', 'cellulosic'] },
  { code: '470691', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulps', 'fibres', 'derived', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'fibrous', 'cellulosic'] },
  { code: '470692', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulps', 'fibres', 'derived', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'fibrous', 'cellulosic'] },
  { code: '470693', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulps', 'fibres', 'derived', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'fibrous', 'cellulosic'] },
  { code: '470710', description: 'Recovered (waste and scrap) paper or paperboard:Unbleached kraft paper or pap...', chapter: '47', category: 'paper', keywords: ['recovered', 'waste', 'scrap', 'paper', 'paperboardunbleached', 'kraft', 'paperboard', 'corrugated'] },
  { code: '470720', description: 'Recovered (waste and scrap) paper or paperboard:Other paper or paperboard mad...', chapter: '47', category: 'paper', keywords: ['recovered', 'waste', 'scrap', 'paper', 'paperboard', 'paperboard', 'mainly', 'bleached', 'chemical', 'pulp'] },
  { code: '470730', description: 'Recovered (waste and scrap) paper or paperboard:Paper or paperboard made main...', chapter: '47', category: 'paper', keywords: ['recovered', 'waste', 'scrap', 'paper', 'paperboardpaper', 'paperboard', 'mainly', 'mechanical', 'pulp', 'example'] },
  { code: '470790', description: 'Recovered (waste and scrap) paper or paperboard:Other, including unsorted was...', chapter: '47', category: 'paper', keywords: ['recovered', 'waste', 'scrap', 'paper', 'paperboard', 'unsorted', 'scrapunsorted'] },
];
