// Chapter 47: Wood Pulp -- 21 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_47: HsCodeEntry[] = [
  { code: '470100', description: 'Mechanical wood pulp:*Thermo-mechanical wood pulp', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'mechanical'] },
  { code: '470200', description: 'Chemical wood pulp, dissolving grades', chapter: '47', category: 'paper', keywords: ['chemical', 'wood', 'pulp', 'dissolving', 'grades'] },
  { code: '470311', description: 'Wood pulp; chemical wood pulp, soda or sulphate, (other than dissolving grades), unbleached, of coniferous wood', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'chemical', 'soda', 'sulphate', 'dissolving', 'grades', 'unbleached', 'coniferous'] },
  { code: '470319', description: 'Wood pulp; chemical wood pulp, soda or sulphate, (other than dissolving grades), unbleached, of non-coniferous wood', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'chemical', 'soda', 'sulphate', 'dissolving', 'grades', 'unbleached', 'non-coniferous'] },
  { code: '470321', description: 'Wood pulp; chemical wood pulp, soda or sulphate, (other than dissolving grades), semi-bleached or bleached, of coniferou', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'chemical', 'soda', 'sulphate', 'dissolving', 'grades', 'semi-bleached', 'bleached', 'coniferous'] },
  { code: '470329', description: 'Wood pulp; chemical wood pulp, soda or sulphate, (other than dissolving grades), semi-bleached or bleached, of non-conif', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'chemical', 'soda', 'sulphate', 'dissolving', 'grades', 'semi-bleached', 'bleached', 'non-coniferous'] },
  { code: '470411', description: 'Wood pulp; chemical wood pulp, sulphite, (other than dissolving grades), unbleached, of coniferous wood', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'chemical', 'sulphite', 'dissolving', 'grades', 'unbleached', 'coniferous'] },
  { code: '470419', description: 'Wood pulp; chemical wood pulp, sulphite, (other than dissolving grades), unbleached, of non-coniferous wood', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'chemical', 'sulphite', 'dissolving', 'grades', 'unbleached', 'non-coniferous'] },
  { code: '470421', description: 'Wood pulp; chemical wood pulp, sulphite, (other than dissolving grades), semi-bleached or bleached, of coniferous wood', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'chemical', 'sulphite', 'dissolving', 'grades', 'semi-bleached', 'bleached', 'coniferous'] },
  { code: '470429', description: 'Wood pulp; chemical wood pulp, sulphite, (other than dissolving grades), semi-bleached or bleached, of non-coniferous wo', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'chemical', 'sulphite', 'dissolving', 'grades', 'semi-bleached', 'bleached', 'non-coniferous'] },
  { code: '470500', description: 'Wood pulp; obtained by a combination of mechanical and chemical pulping processes', chapter: '47', category: 'paper', keywords: ['wood', 'pulp', 'combination', 'mechanical', 'chemical', 'pulping', 'processes'] },
  { code: '470610', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulps', 'fibres', 'derived', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'fibrous', 'cellulosic'] },
  { code: '470620', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulp', 'fibres', 'derived', 'from', 'recovered', 'waste', 'scrap', 'paper', 'paperboard'] },
  { code: '470630', description: 'Pulps of fibres derived from recovered (waste and scrap) paper or paperboard ...', chapter: '47', category: 'paper', keywords: ['pulps', 'fibres', 'derived', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'fibrous', 'cellulosic'] },
  { code: '470691', description: 'Pulp; of fibrous cellulosic material, other than of bamboo or fibres derived from recovered (waste and scrap) paper or p', chapter: '47', category: 'paper', keywords: ['pulp', 'fibrous', 'cellulosic', 'material', 'bamboo', 'fibres', 'derived', 'from', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'cotton', 'linters', 'mechanical'] },
  { code: '470692', description: 'Pulp; of fibrous cellulosic material, other than of bamboo or fibres derived from recovered (waste and scrap) paper or p', chapter: '47', category: 'paper', keywords: ['pulp', 'fibrous', 'cellulosic', 'material', 'bamboo', 'fibres', 'derived', 'from', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'cotton', 'linters', 'chemical'] },
  { code: '470693', description: 'Pulp; of fibrous cellulosic material, other than of bamboo or fibres derived from recovered (waste and scrap) paper or p', chapter: '47', category: 'paper', keywords: ['pulp', 'fibrous', 'cellulosic', 'material', 'bamboo', 'fibres', 'derived', 'from', 'recovered', 'waste', 'scrap', 'paper', 'paperboard', 'cotton', 'linters', 'combination', 'mechanical', 'chemical', 'processes'] },
  { code: '470710', description: 'Paper or paperboard; waste and scrap, of unbleached kraft paper or paperboard or corrugated paper or paperboard', chapter: '47', category: 'paper', keywords: ['paper', 'paperboard', 'waste', 'scrap', 'unbleached', 'kraft', 'corrugated'] },
  { code: '470720', description: 'Paper or paperboard; waste and scrap, paper or paperboard made mainly of bleached chemical pulp, not coloured in the mas', chapter: '47', category: 'paper', keywords: ['paper', 'paperboard', 'waste', 'scrap', 'bleached', 'chemical', 'pulp', 'coloured', 'mass'] },
  { code: '470730', description: 'Paper or paperboard; waste and scrap, paper or paperboard made mainly of mechanical pulp (e.g. newspapers, journals and ', chapter: '47', category: 'paper', keywords: ['paper', 'paperboard', 'waste', 'scrap', 'mechanical', 'pulp', 'e.g', 'newspapers', 'journals', 'printed', 'matter'] },
  { code: '470790', description: 'Paper or paperboard; waste and scrap, of paper or paperboard n.e.c. in heading no. 4707 and of unsorted waste and scrap', chapter: '47', category: 'paper', keywords: ['paper', 'paperboard', 'waste', 'scrap', 'unsorted'] },
];
