// Chapter 49: Books & Printed Materials -- 20 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_49: HsCodeEntry[] = [
  { code: '490110', description: 'Printed matter; in single sheets, whether or not folded', chapter: '49', category: 'books', keywords: ['printed', 'matter', 'single', 'sheets', 'folded'] },
  { code: '490191', description: 'Digital books', chapter: '49', category: 'books', keywords: ['ebook', 'digital book', 'pdf book', 'printed', 'books', 'brochures', 'leaflets', 'similar', 'matter', 'single'] },
  { code: '490199', description: 'Printed matter; books, brochures, leaflets and similar printed matter n.e.c. in item no. 4901.10 or 4901.91', chapter: '49', category: 'books', keywords: ['printed', 'matter', 'books', 'brochures', 'leaflets', 'item'] },
  { code: '490200', description: 'Newspapers', chapter: '49', category: 'books', keywords: ['newspaper', 'publication', 'news'] },
  { code: '490210', description: 'Newspapers, journals and periodicals; whether or not illustrated or containing advertising material, appearing at least ', chapter: '49', category: 'books', keywords: ['newspapers', 'journals', 'periodicals', 'illustrated', 'advertising', 'material', 'appearing', 'least', 'four', 'times', 'week'] },
  { code: '490290', description: 'Newspapers, journals and periodicals; whether or not illustrated or containing advertising material, appearing less freq', chapter: '49', category: 'books', keywords: ['newspapers', 'journals', 'periodicals', 'illustrated', 'advertising', 'material', 'appearing', 'frequently', 'four', 'times', 'week'] },
  { code: '490300', description: 'Printed matter; children\'s picture, drawing or colouring books', chapter: '49', category: 'books', keywords: ['printed', 'matter', 'children\'s', 'picture', 'drawing', 'colouring', 'books'] },
  { code: '490400', description: 'Music, printed or in manuscript, whether or not bound or illustrated', chapter: '49', category: 'books', keywords: ['music', 'printed', 'manuscript', 'bound', 'illustrated'] },
  { code: '490510', description: 'Maps', chapter: '49', category: 'office', keywords: ['map', 'wall map', 'road map', 'topographic map', 'maps', 'hydrographic', 'similar', 'charts', 'kinds', 'atlases'] },
  { code: '490591', description: 'Maps and hydrographic or similar charts of all kinds, including atlases, wall...', chapter: '49', category: 'books', keywords: ['maps', 'hydrographic', 'similar', 'charts', 'kinds', 'atlases', 'wall', 'topographical', 'plans', 'globes'] },
  { code: '490599', description: 'Maps and hydrographic or similar charts of all kinds, including atlases, wall...', chapter: '49', category: 'books', keywords: ['maps', 'hydrographic', 'similar', 'charts', 'kinds', 'atlases', 'wall', 'topographical', 'plans', 'globes'] },
  { code: '490600', description: 'Plans and drawings; for architectural, engineering, industrial, commercial, topographical or similar, being originals dr', chapter: '49', category: 'books', keywords: ['plans', 'drawings', 'architectural', 'engineering', 'industrial', 'commercial', 'topographical', 'originals', 'drawn', 'hand', 'hand-written', 'texts', 'photo-', 'graphic', 'reproductions', 'carbon', 'copies'] },
  { code: '490700', description: 'Unused postage, revenue or similar stamps of current or new issue in the country in which they have, or will have, a rec', chapter: '49', category: 'books', keywords: ['unused', 'postage', 'revenue', 'stamps', 'current', 'new', 'issue', 'country', 'which', 'they', 'recognised', 'face', 'value', 'stamp-impressed', 'paper', 'cheque', 'banknotes', 'stock', 'share', 'bond', 'certificates', 'title'] },
  { code: '490810', description: 'Transfers (decalcomanias):Transfers (decalcomanias), vitrifiable', chapter: '49', category: 'books', keywords: ['printed', 'matter', 'transfers', 'decalcomanias', 'vitrifiable'] },
  { code: '490890', description: 'Printed matter; transfers (decalcomanias), other than vitrifiable', chapter: '49', category: 'books', keywords: ['printed', 'matter', 'transfers', 'decalcomanias', 'vitrifiable'] },
  { code: '490900', description: 'Printed or illustrated postcards; printed cards bearing personal greetings, messages or announcements, whether or not il', chapter: '49', category: 'books', keywords: ['printed', 'illustrated', 'postcards', 'cards', 'bearing', 'personal', 'greetings', 'messages', 'announcements', 'without', 'envelopes', 'trimmings'] },
  { code: '491000', description: 'Calendars; printed, of any kind, including calendar blocks', chapter: '49', category: 'books', keywords: ['calendars', 'printed', 'calendar', 'blocks'] },
  { code: '491110', description: 'Other printed matter, including printed pictures and photographs:Trade advert...', chapter: '49', category: 'books', keywords: ['printed', 'matter', 'pictures', 'photographstrade', 'advertising', 'material', 'commercial', 'catalogues', 'likecommercial'] },
  { code: '491191', description: 'Other printed matter, including printed pictures and photographs:Other:*Pictu...', chapter: '49', category: 'books', keywords: ['printed', 'matter', 'pictures', 'designs', 'photographs', 'item'] },
  { code: '491199', description: 'Other printed matter, including printed pictures and photographs:Other:*Other...', chapter: '49', category: 'books', keywords: ['printed', 'matter', 'pictures', 'photographs209'] },
];
