// Chapter 53: Other Vegetable Textiles -- 23 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_53: HsCodeEntry[] = [
  { code: '530110', description: 'Flax, raw or processed but not spun; flax tow and waste (including yarn waste...', chapter: '53', category: 'textiles', keywords: ['flax', 'raw', 'retted', 'spun'] },
  { code: '530121', description: 'Flax, raw or processed but not spun; flax tow and waste (including yarn waste...', chapter: '53', category: 'textiles', keywords: ['flax', 'raw', 'processed', 'spun', 'tow', 'waste', 'yarn', 'garnetted', 'stock', 'flax'] },
  { code: '530129', description: 'Flax, raw or processed but not spun; flax tow and waste (including yarn waste...', chapter: '53', category: 'textiles', keywords: ['flax', 'hackled', 'otherwise', 'processed', 'spun'] },
  { code: '530130', description: 'Flax, raw or processed but not spun; flax tow and waste (including yarn waste...', chapter: '53', category: 'textiles', keywords: ['flax', 'raw', 'processed', 'spun', 'tow', 'waste', 'yarn', 'garnetted', 'stock', 'flax'] },
  { code: '530210', description: 'True hemp (<AI>!Cannabis sativa L.!), raw or processed but not spun; tow and ...', chapter: '53', category: 'textiles', keywords: ['hemp', 'cannabis', 'sativa', 'raw', 'retted', 'spun'] },
  { code: '530290', description: 'True hemp (<AI>!Cannabis sativa L.!), raw or processed but not spun; tow and ...', chapter: '53', category: 'textiles', keywords: ['true', 'hemp', 'aicannabis', 'sativa', 'l', 'raw', 'processed', 'spun', 'tow', 'waste'] },
  { code: '530310', description: 'Jute and other textile bast fibres; raw or retted, but not spun, (excluding flax, hemp (cannabis sativa L.), and ramie)', chapter: '53', category: 'textiles', keywords: ['jute', 'textile', 'bast', 'fibres', 'raw', 'retted', 'spun', 'flax', 'hemp', 'cannabis', 'sativa', 'ramie'] },
  { code: '530390', description: 'Jute and other textile bast fibres; processed but not spun, tow and waste of these fibres, including yarn waste and garn', chapter: '53', category: 'textiles', keywords: ['jute', 'textile', 'bast', 'fibres', 'processed', 'spun', 'tow', 'waste', 'yarn', 'garnetted', 'stock', 'flax', 'hemp', 'cannabis', 'sativa', 'ramie'] },
  { code: '530500', description: 'Coconut, abaca (Manila hemp or Musa textilis Nee), ramie and other vegetable textile fibres n.e.c., raw or processed but', chapter: '53', category: 'textiles', keywords: ['coconut', 'abaca', 'manila', 'hemp', 'musa', 'textilis', 'nee', 'ramie', 'vegetable', 'textile', 'fibres', 'raw', 'processed', 'spun', 'tow', 'noils', 'waste', 'yarn', 'garnetted', 'stock'] },
  { code: '530610', description: 'Flax yarn:Single:*Not put up for retail sale:**Measuring 833.3 decitex or mor...', chapter: '53', category: 'textiles', keywords: ['yarn', 'flax', 'single'] },
  { code: '530620', description: 'Flax yarn:Multiple (folded) or cabled:*Not put up for retail sale(TEXT 115)', chapter: '53', category: 'textiles', keywords: ['flax', 'yarnmultiple', 'folded', 'cablednot', 'retail', 'sale', 'text', '115'] },
  { code: '530710', description: 'Yarn of jute or of other textile bast fibres of heading 5303:Single(TEXT 148A)', chapter: '53', category: 'textiles', keywords: ['yarn', 'jute', 'textile', 'bast', 'fibres', 'single'] },
  { code: '530720', description: 'Yarn of jute or of other textile bast fibres of heading 5303:Multiple (folded...', chapter: '53', category: 'textiles', keywords: ['yarn', 'jute', 'textile', 'bast', 'fibres', 'heading', '5303multiple', 'folded', 'cabled', 'text'] },
  { code: '530810', description: 'Yarn of other vegetable textile fibres; paper yarn:Coir yarn(TEXT 148B)', chapter: '53', category: 'textiles', keywords: ['yarn', 'coir'] },
  { code: '530820', description: 'Yarn of other vegetable textile fibres; paper yarn:True hemp yarn:*Not put up...', chapter: '53', category: 'textiles', keywords: ['yarn', 'vegetable', 'textile', 'fibres', 'paper', 'yarntrue', 'hemp', 'yarnnot', 'retail', 'sale'] },
  { code: '530890', description: 'Yarn of other vegetable textile fibres; paper yarn:Other:*Ramie yarn:**Measur...', chapter: '53', category: 'textiles', keywords: ['yarn', 'vegetable', 'textile', 'fibres'] },
  { code: '530911', description: 'Woven fabrics of flax:Containing 85 % or more by weight of flax:*Unbleached o...', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'flaxcontaining', 'flaxunbleached', 'bleachedunbleached', 'text', '117'] },
  { code: '530919', description: 'Fabrics, woven; of flax, containing 85% or more flax, other than bleached or unbleached', chapter: '53', category: 'textiles', keywords: ['fabrics', 'woven', 'flax', '85%', 'bleached', 'unbleached'] },
  { code: '530921', description: 'Woven fabrics of flax:Containing less than 85 % by weight of flax:*Unbleached...', chapter: '53', category: 'textiles', keywords: ['fabrics', 'woven', 'flax', '85%', 'unbleached', 'bleached'] },
  { code: '530929', description: 'Woven fabrics of flax:Containing less than 85 % by weight of flax:*Other(TEXT...', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'flaxcontaining', 'flax', 'text', '117'] },
  { code: '531010', description: 'Fabrics, woven; of jute or of other textile bast fibres of heading no. 5303, unbleached', chapter: '53', category: 'textiles', keywords: ['fabrics', 'woven', 'jute', 'textile', 'bast', 'fibres', 'unbleached'] },
  { code: '531090', description: 'Woven fabrics of jute or of other textile bast fibres of heading 5303:Other', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'jute', 'textile', 'bast', 'fibres', 'heading', '5303'] },
  { code: '531100', description: 'Fabrics, woven; of vegetable textile fibres n.e.c. in heading no. 5309 and 5310, woven fabrics of paper yarn', chapter: '53', category: 'textiles', keywords: ['fabrics', 'woven', 'vegetable', 'textile', 'fibres', 'paper', 'yarn'] },
];
