// Chapter 53: Other Vegetable Textiles -- 23 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_53: HsCodeEntry[] = [
  { code: '530110', description: 'Flax, raw or processed but not spun; flax tow and waste (including yarn waste...', chapter: '53', category: 'textiles', keywords: ['flax', 'raw', 'processed', 'spun', 'tow', 'waste', 'yarn', 'garnetted', 'stock', 'flax'] },
  { code: '530121', description: 'Flax, raw or processed but not spun; flax tow and waste (including yarn waste...', chapter: '53', category: 'textiles', keywords: ['flax', 'raw', 'processed', 'spun', 'tow', 'waste', 'yarn', 'garnetted', 'stock', 'flax'] },
  { code: '530129', description: 'Flax, raw or processed but not spun; flax tow and waste (including yarn waste...', chapter: '53', category: 'textiles', keywords: ['flax', 'raw', 'processed', 'spun', 'tow', 'waste', 'yarn', 'garnetted', 'stock', 'flax'] },
  { code: '530130', description: 'Flax, raw or processed but not spun; flax tow and waste (including yarn waste...', chapter: '53', category: 'textiles', keywords: ['flax', 'raw', 'processed', 'spun', 'tow', 'waste', 'yarn', 'garnetted', 'stock', 'flax'] },
  { code: '530210', description: 'True hemp (<AI>!Cannabis sativa L.!), raw or processed but not spun; tow and ...', chapter: '53', category: 'textiles', keywords: ['true', 'hemp', 'aicannabis', 'sativa', 'l', 'raw', 'processed', 'spun', 'tow', 'waste'] },
  { code: '530290', description: 'True hemp (<AI>!Cannabis sativa L.!), raw or processed but not spun; tow and ...', chapter: '53', category: 'textiles', keywords: ['true', 'hemp', 'aicannabis', 'sativa', 'l', 'raw', 'processed', 'spun', 'tow', 'waste'] },
  { code: '530310', description: 'Jute and other textile bast fibres (excluding flax, true hemp and ramie), raw...', chapter: '53', category: 'textiles', keywords: ['jute', 'textile', 'bast', 'fibres', 'flax', 'true', 'hemp', 'ramie', 'raw', 'processed'] },
  { code: '530390', description: 'Jute and other textile bast fibres (excluding flax, true hemp and ramie), raw...', chapter: '53', category: 'textiles', keywords: ['jute', 'textile', 'bast', 'fibres', 'flax', 'true', 'hemp', 'ramie', 'raw', 'processed'] },
  { code: '530500', description: 'Coconut, abaca (Manila hemp or <AI>!Musa textilis Nee!), ramie and other vege...', chapter: '53', category: 'textiles', keywords: ['coconut', 'abaca', 'manila', 'hemp', 'aimusa', 'textilis', 'nee', 'ramie', 'vegetable', 'textile'] },
  { code: '530610', description: 'Flax yarn:Single:*Not put up for retail sale:**Measuring 833.3 decitex or mor...', chapter: '53', category: 'textiles', keywords: ['flax', 'yarnsinglenot', 'retail', 'salemeasuring', '8333', 'decitex', 'metric', 'number', 'text', '115'] },
  { code: '530620', description: 'Flax yarn:Multiple (folded) or cabled:*Not put up for retail sale(TEXT 115)', chapter: '53', category: 'textiles', keywords: ['flax', 'yarnmultiple', 'folded', 'cablednot', 'retail', 'sale', 'text', '115'] },
  { code: '530710', description: 'Yarn of jute or of other textile bast fibres of heading 5303:Single(TEXT 148A)', chapter: '53', category: 'textiles', keywords: ['yarn', 'jute', 'textile', 'bast', 'fibres', 'heading', '5303single', 'text', '148a'] },
  { code: '530720', description: 'Yarn of jute or of other textile bast fibres of heading 5303:Multiple (folded...', chapter: '53', category: 'textiles', keywords: ['yarn', 'jute', 'textile', 'bast', 'fibres', 'heading', '5303multiple', 'folded', 'cabled', 'text'] },
  { code: '530810', description: 'Yarn of other vegetable textile fibres; paper yarn:Coir yarn(TEXT 148B)', chapter: '53', category: 'textiles', keywords: ['yarn', 'vegetable', 'textile', 'fibres', 'paper', 'yarncoir', 'text', '148b'] },
  { code: '530820', description: 'Yarn of other vegetable textile fibres; paper yarn:True hemp yarn:*Not put up...', chapter: '53', category: 'textiles', keywords: ['yarn', 'vegetable', 'textile', 'fibres', 'paper', 'yarntrue', 'hemp', 'yarnnot', 'retail', 'sale'] },
  { code: '530890', description: 'Yarn of other vegetable textile fibres; paper yarn:Other:*Ramie yarn:**Measur...', chapter: '53', category: 'textiles', keywords: ['yarn', 'vegetable', 'textile', 'fibres', 'paper', 'yarnramie', 'yarnmeasuring', '2778', 'decitex', 'metric'] },
  { code: '530911', description: 'Woven fabrics of flax:Containing 85 % or more by weight of flax:*Unbleached o...', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'flaxcontaining', 'flaxunbleached', 'bleachedunbleached', 'text', '117'] },
  { code: '530919', description: 'Woven fabrics of flax:Containing 85 % or more by weight of flax:*Other(TEXT 117)', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'flaxcontaining', 'flax', 'text', '117'] },
  { code: '530921', description: 'Woven fabrics of flax:Containing less than 85 % by weight of flax:*Unbleached...', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'flaxcontaining', 'flaxunbleached', 'bleached', 'text', '117'] },
  { code: '530929', description: 'Woven fabrics of flax:Containing less than 85 % by weight of flax:*Other(TEXT...', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'flaxcontaining', 'flax', 'text', '117'] },
  { code: '531010', description: 'Woven fabrics of jute or of other textile bast fibres of heading 5303:Unbleac...', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'jute', 'textile', 'bast', 'fibres', 'heading', '5303unbleachedof', 'width', '150'] },
  { code: '531090', description: 'Woven fabrics of jute or of other textile bast fibres of heading 5303:Other', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'jute', 'textile', 'bast', 'fibres', 'heading', '5303'] },
  { code: '531100', description: 'Woven fabrics of other vegetable textile fibres; woven fabrics of paper yarn:...', chapter: '53', category: 'textiles', keywords: ['woven', 'fabrics', 'vegetable', 'textile', 'fibres', 'paper', 'yarnof', 'ramie', 'text', '117'] },
];
