// Chapter 57: Carpets & Rugs -- 22 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_57: HsCodeEntry[] = [
  { code: '570110', description: 'Carpets and other textile floor coverings; knotted, of wool or fine animal hair, whether or not made up', chapter: '57', category: 'furniture', keywords: ['carpets', 'textile', 'floor', 'coverings', 'knotted', 'wool', 'fine', 'animal', 'hair'] },
  { code: '570190', description: 'Carpets and other textile floor coverings; knotted, of textile materials (other than wool or fine animal hair), whether ', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'knotted', 'materials', 'wool', 'fine', 'animal', 'hair'] },
  { code: '570210', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), whether or not made up, including kelem, schu', chapter: '57', category: 'furniture', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie', 'hand-woven', 'rugs'] },
  { code: '570220', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), whether or not made up, of coconut fibres (co', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'coconut', 'fibres', 'coir'] },
  { code: '570231', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of wool or fine animal hair, of pile construc', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'wool', 'fine', 'animal', 'hair', 'pile', 'construction', 'item'] },
  { code: '570232', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of man-made textile materials, of pile constr', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'man-made', 'materials', 'pile', 'construction', 'item'] },
  { code: '570239', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of textile materials (other than man-made, wo', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'materials', 'man-made', 'wool', 'fine', 'animal', 'hair', 'pile', 'construction', 'item'] },
  { code: '570241', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of wool or fine animal hair, of pile construc', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'wool', 'fine', 'animal', 'hair', 'pile', 'construction', 'item'] },
  { code: '570242', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of man-made textile materials, of pile constr', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'man-made', 'materials', 'pile', 'construction', 'item'] },
  { code: '570249', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of textile materials (other than man-made, wo', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'materials', 'man-made', 'wool', 'fine', 'animal', 'hair', 'pile', 'construction', 'item'] },
  { code: '570250', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), not of pile construction, not made up, n.e.c.', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'pile', 'construction', 'item'] },
  { code: '570290', description: 'Other carpets & floor mats', chapter: '57', category: 'furniture', keywords: ['floor mat', 'door mat', 'welcome mat', 'entrance mat', 'carpet runner'] },
  { code: '570291', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of wool or fine animal hair, (not of pile con', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'wool', 'fine', 'animal', 'hair', 'pile', 'construction', 'item'] },
  { code: '570292', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of man-made textile materials, (not of pile c', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'man-made', 'materials', 'pile', 'construction', 'item'] },
  { code: '570299', description: 'Carpets and other textile floor coverings; woven, (not tufted or flocked), of textile materials (other than man-made or ', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'materials', 'man-made', 'wool', 'fine', 'animal', 'hair', 'pile', 'construction', 'item'] },
  { code: '570310', description: 'Carpets and other textile floor coverings (including turf); tufted, of wool or fine animal hair, whether or not made up', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'turf', 'tufted', 'wool', 'fine', 'animal', 'hair'] },
  { code: '570320', description: 'Carpets and other textile floor coverings, tufted, whether or not made up:Of ...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'tufted', 'upof', 'nylon', 'polyamidesprintedtiles', 'maximum', 'surface'] },
  { code: '570330', description: 'Carpets and other textile floor coverings, tufted, whether or not made up:Of ...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'tufted', 'upof', 'man', 'materialsof', 'polypropylenetiles', 'maximum'] },
  { code: '570390', description: 'Carpets and other textile floor coverings; tufted, of textile materials (other than man-made, wool or fine animal hair),', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'tufted', 'materials', 'man-made', 'wool', 'fine', 'animal', 'hair'] },
  { code: '570410', description: 'Textile floor coverings; felt tiles, (not tufted or flocked), whether or not made up, having a maximum surface area of 0', chapter: '57', category: 'textiles', keywords: ['textile', 'floor', 'coverings', 'felt', 'tiles', 'tufted', 'flocked', 'maximum', 'surface', 'area', '0.3m2'] },
  { code: '570490', description: 'Carpets and other textile floor coverings; of felt, (not tufted or flocked), in the piece, whether or not made up, havin', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'felt', 'tufted', 'flocked', 'piece', 'maximum', 'surface', 'area', 'exceeding'] },
  { code: '570500', description: 'Carpets and other textile floor coverings; n.e.c. in chapter 57, whether or not made up', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings'] },
];
