// Chapter 57: Carpets & Rugs -- 22 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_57: HsCodeEntry[] = [
  { code: '570110', description: 'Carpets of wool', chapter: '57', category: 'furniture', keywords: ['carpet', 'wool carpet', 'area rug', 'floor rug', 'oriental rug', 'carpets', 'textile', 'floor', 'coverings', 'knotted'] },
  { code: '570190', description: 'Carpets and other textile floor coverings, knotted, whether or not made up:Of...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'knotted', 'upof', 'materialsof', 'silk', 'waste', 'noil'] },
  { code: '570210', description: 'Carpets of synthetic', chapter: '57', category: 'furniture', keywords: ['synthetic carpet', 'nylon carpet', 'polyester carpet', 'modern rug', 'carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted'] },
  { code: '570220', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570231', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570232', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570239', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570241', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570242', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570249', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570250', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570290', description: 'Other carpets', chapter: '57', category: 'furniture', keywords: ['floor mat', 'door mat', 'welcome mat', 'yoga mat'] },
  { code: '570291', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570292', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570299', description: 'Carpets and other textile floor coverings, woven, not tufted or flocked, whet...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'woven', 'tufted', 'flocked', 'kelem', 'schumacks', 'karamanie'] },
  { code: '570310', description: 'Carpets and other textile floor coverings, tufted, whether or not made up:*Of...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'tufted', 'upof', 'wool', 'fine', 'animal', 'hair'] },
  { code: '570320', description: 'Carpets and other textile floor coverings, tufted, whether or not made up:Of ...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'tufted', 'upof', 'nylon', 'polyamidesprintedtiles', 'maximum', 'surface'] },
  { code: '570330', description: 'Carpets and other textile floor coverings, tufted, whether or not made up:Of ...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'tufted', 'upof', 'man', 'materialsof', 'polypropylenetiles', 'maximum'] },
  { code: '570390', description: 'Carpets and other textile floor coverings, tufted, whether or not made up:Of ...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'tufted', 'upof', 'man', 'materialsof', 'materialstiles', 'maximum'] },
  { code: '570410', description: 'Carpets and other textile floor coverings, of felt, not tufted or flocked,  w...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'felt', 'tufted', 'flocked', 'uptiles', 'maximum', 'surface'] },
  { code: '570490', description: 'Carpets and other textile floor coverings, of felt, not tufted or flocked,  w...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'felt', 'tufted', 'flocked', 'up'] },
  { code: '570500', description: 'Other carpets and other textile floor coverings, whether or not made up:*Of m...', chapter: '57', category: 'textiles', keywords: ['carpets', 'textile', 'floor', 'coverings', 'upof', 'man', 'materials', 'text', '059'] },
];
