// Chapter 59: Impregnated Textiles -- 24 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_59: HsCodeEntry[] = [
  { code: '590110', description: 'Textile fabrics coated with gum or amylaceous substances, of a kind used for ...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'coated', 'gum', 'amylaceous', 'substances', 'kind', 'outer', 'covers', 'books'] },
  { code: '590190', description: 'Textile fabrics coated with gum or amylaceous substances, of a kind used for ...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'coated', 'gum', 'amylaceous', 'substances', 'kind', 'outer', 'covers', 'books'] },
  { code: '590210', description: 'Tyre cord fabric of high tenacity yarn of nylon or other polyamides, polyeste...', chapter: '59', category: 'textiles', keywords: ['tyre', 'cord', 'fabric', 'high', 'tenacity', 'yarn', 'nylon', 'polyamides', 'polyesters', 'viscose'] },
  { code: '590220', description: 'Tyre cord fabric of high tenacity yarn of nylon or other polyamides, polyeste...', chapter: '59', category: 'textiles', keywords: ['tyre', 'cord', 'fabric', 'high', 'tenacity', 'yarn', 'nylon', 'polyamides', 'polyesters', 'viscose'] },
  { code: '590290', description: 'Tyre cord fabric of high tenacity yarn of nylon or other polyamides, polyeste...', chapter: '59', category: 'textiles', keywords: ['tyre', 'cord', 'fabric', 'high', 'tenacity', 'yarn', 'nylon', 'polyamides', 'polyesters', 'viscose'] },
  { code: '590310', description: 'Textile fabrics impregnated, coated, covered or laminated with plastics, othe...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'impregnated', 'coated', 'covered', 'laminated', 'plastics', 'those', 'heading', '5902with'] },
  { code: '590320', description: 'Textile fabrics impregnated, coated, covered or laminated with plastics, othe...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'impregnated', 'coated', 'covered', 'laminated', 'plastics', 'those', 'heading', '5902with'] },
  { code: '590390', description: 'Textile fabrics impregnated, coated, covered or laminated with plastics, othe...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'impregnated', 'coated', 'covered', 'laminated', 'plastics', 'those', 'heading', '5902impregnated'] },
  { code: '590410', description: 'Linoleum, whether or not cut to shape; floor coverings consisting of a coatin...', chapter: '59', category: 'textiles', keywords: ['linoleum', 'cut', 'shape', 'floor', 'coverings', 'consisting', 'coating', 'covering', 'applied', 'textile'] },
  { code: '590490', description: 'Linoleum, whether or not cut to shape; floor coverings consisting of a coatin...', chapter: '59', category: 'textiles', keywords: ['linoleum', 'cut', 'shape', 'floor', 'coverings', 'consisting', 'coating', 'covering', 'applied', 'textile'] },
  { code: '590500', description: 'Textile wall coverings:*Consisting of parallel yarns, fixed on a backing of a...', chapter: '59', category: 'textiles', keywords: ['textile', 'wall', 'coveringsconsisting', 'parallel', 'yarns', 'fixed', 'backing', 'material', 'text', '098'] },
  { code: '590610', description: 'Rubberised textile fabrics, other than those of heading 5902:Adhesive tape of...', chapter: '59', category: 'textiles', keywords: ['rubberised', 'textile', 'fabrics', 'those', 'heading', '5902adhesive', 'tape', 'width', '20cm', 'text'] },
  { code: '590691', description: 'Rubberised textile fabrics, other than those of heading 5902:Other:*Knitted o...', chapter: '59', category: 'textiles', keywords: ['rubberised', 'textile', 'fabrics', 'those', 'heading', '5902knitted', 'crocheted', 'text', '063'] },
  { code: '590699', description: 'Rubberised textile fabrics, other than those of heading 5902:Other:*Other:**F...', chapter: '59', category: 'textiles', keywords: ['rubberised', 'textile', 'fabrics', 'those', 'heading', '5902fabrics', 'mentioned', 'note', 'this', 'chapter'] },
  { code: '590700', description: 'Textile fabrics otherwise impregnated, coated or covered; painted canvas bein...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'otherwise', 'impregnated', 'coated', 'covered', 'painted', 'canvas', 'being', 'theatrical'] },
  { code: '590800', description: 'Textile wicks, woven, plaited or knitted, for lamps, stoves, lighters, candle...', chapter: '59', category: 'textiles', keywords: ['textile', 'wicks', 'woven', 'plaited', 'knitted', 'lamps', 'stoves', 'lighters', 'candles', 'like'] },
  { code: '590900', description: 'Textile hosepiping and similar textile tubing, with or without lining, armour...', chapter: '59', category: 'textiles', keywords: ['textile', 'hosepiping', 'similar', 'tubing', 'without', 'lining', 'armour', 'accessories', 'materialsof', 'synthetic'] },
  { code: '591000', description: 'Transmission or conveyor belts or belting, of textile material, whether or  n...', chapter: '59', category: 'textiles', keywords: ['transmission', 'conveyor', 'belts', 'belting', 'textile', 'material', 'whether', 'impregrated', 'coated', 'covered'] },
  { code: '591110', description: 'Textile products and articles, for technical uses, specified in Note 7 to thi...', chapter: '59', category: 'textiles', keywords: ['textile', 'products', 'technical', 'uses', 'specified', 'note', 'this', 'chaptertextile', 'fabrics', 'felt'] },
  { code: '591120', description: 'Textile products and articles, for technical uses, specified in Note 7 to thi...', chapter: '59', category: 'textiles', keywords: ['textile', 'products', 'technical', 'uses', 'specified', 'note', 'this', 'chapterbolting', 'cloth', 'up036'] },
  { code: '591131', description: 'Textile products and articles, for technical uses, specified in Note 7 to thi...', chapter: '59', category: 'textiles', keywords: ['textile', 'products', 'technical', 'uses', 'specified', 'note', 'this', 'chaptertextile', 'fabrics', 'felts'] },
  { code: '591132', description: 'Textile products and articles, for technical uses, specified in Note 7 to thi...', chapter: '59', category: 'textiles', keywords: ['textile', 'products', 'technical', 'uses', 'specified', 'note', 'this', 'chaptertextile', 'fabrics', 'felts'] },
  { code: '591140', description: 'Textile products and articles, for technical uses, specified in Note 7 to thi...', chapter: '59', category: 'textiles', keywords: ['textile', 'products', 'technical', 'uses', 'specified', 'note', 'this', 'chapterstraining', 'cloth', 'kind'] },
  { code: '591190', description: 'Textile products and articles, for technical uses, specified in Note 7 to thi...', chapter: '59', category: 'textiles', keywords: ['textile', 'products', 'technical', 'uses', 'specified', 'note', 'this', 'chapterof', 'felt', 'text'] },
];
