// Chapter 59: Impregnated Textiles -- 24 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_59: HsCodeEntry[] = [
  { code: '590110', description: 'Textile fabrics; coated with gum or amylaceous substances, of a kind used for the outer covers of books or the like', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'coated', 'gum', 'amylaceous', 'substances', 'outer', 'covers', 'books'] },
  { code: '590190', description: 'Textile fabrics; coated with gum or amylaceous substances, tracing cloth, prepared painting canvas, buckram and similar ', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'coated', 'gum', 'amylaceous', 'substances', 'tracing', 'cloth', 'prepared', 'painting', 'canvas', 'buckram', 'stiffened', 'hat', 'foundations', 'book', 'covers'] },
  { code: '590210', description: 'Tyre cord fabric of high tenacity yarn of nylon or other polyamides, polyeste...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'tyrecord', 'high', 'tenacity', 'yarn', 'nylon', 'polyamides'] },
  { code: '590220', description: 'Tyre cord fabric of high tenacity yarn of nylon or other polyamides, polyeste...', chapter: '59', category: 'textiles', keywords: ['tyre', 'cord', 'fabric', 'high', 'tenacity', 'yarn', 'nylon', 'polyamides', 'polyesters', 'viscose'] },
  { code: '590290', description: 'Tyre cord fabric of high tenacity yarn of nylon or other polyamides, polyeste...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'tyrecord', 'high', 'tenacity', 'yarn', 'viscose', 'rayon'] },
  { code: '590310', description: 'Textile fabrics impregnated, coated, covered or laminated with plastics, othe...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'impregnated', 'coated', 'covered', 'laminated', 'plastics', 'those', 'heading', '5902with'] },
  { code: '590320', description: 'Textile fabrics impregnated, coated, covered or laminated with plastics, othe...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'impregnated', 'coated', 'laminated', 'polyurethane'] },
  { code: '590390', description: 'Textile fabrics impregnated, coated, covered or laminated with plastics, othe...', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'impregnated', 'coated', 'covered', 'laminated', 'plastics', 'those', 'heading', '5902impregnated'] },
  { code: '590410', description: 'Linoleum, whether or not cut to shape; floor coverings consisting of a coatin...', chapter: '59', category: 'textiles', keywords: ['linoleum', 'cut', 'shape'] },
  { code: '590490', description: 'Linoleum, whether or not cut to shape; floor coverings consisting of a coatin...', chapter: '59', category: 'textiles', keywords: ['linoleum', 'cut', 'shape', 'floor', 'coverings', 'consisting', 'coating', 'covering', 'applied', 'textile'] },
  { code: '590500', description: 'Textile wall coverings:*Consisting of parallel yarns, fixed on a backing of a...', chapter: '59', category: 'textiles', keywords: ['textile', 'wall', 'coverings', 'fabrics', 'impregnated', 'coated', 'laminated'] },
  { code: '590610', description: 'Rubberised textile fabrics, other than those of heading 5902:Adhesive tape of...', chapter: '59', category: 'textiles', keywords: ['rubberised', 'textile', 'fabrics', 'those', 'heading', '5902adhesive', 'tape', 'width', '20cm', 'text'] },
  { code: '590691', description: 'Textile fabrics, rubberised; (excluding those of heading no. 5902 and adhesive tape of a width not exceeding 20cm), knit', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'rubberised', 'adhesive', 'tape', 'width', 'exceeding', '20cm', 'knitted', 'crocheted'] },
  { code: '590699', description: 'Textile fabrics, rubberised; (excluding those of heading no. 5902 and adhesive tape of a width not exceeding 20cm), not ', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'rubberised', 'adhesive', 'tape', 'width', 'exceeding', '20cm', 'knitted', 'crocheted'] },
  { code: '590700', description: 'Textile fabrics; otherwise impregnated, coated or covered, painted canvas being theatrical scenery, studio back-cloths o', chapter: '59', category: 'textiles', keywords: ['textile', 'fabrics', 'otherwise', 'impregnated', 'coated', 'painted', 'canvas', 'theatrical', 'scenery', 'studio', 'back-cloths'] },
  { code: '590800', description: 'Textile wicks, woven, plaited or knitted; for lamps, stoves, lighters, candles or the like; incandescent gas mantles and', chapter: '59', category: 'textiles', keywords: ['textile', 'wicks', 'woven', 'plaited', 'knitted', 'lamps', 'stoves', 'lighters', 'candles', 'incandescent', 'gas', 'mantles', 'tubular', 'mantle', 'fabric', 'therefor', 'impregnated'] },
  { code: '590900', description: 'Textile hosepiping and similar textile tubing; with or without lining, armour or accessories of other materials', chapter: '59', category: 'textiles', keywords: ['textile', 'hosepiping', 'tubing', 'without', 'lining', 'armour', 'materials'] },
  { code: '591000', description: 'Transmission or conveyor belts or belting, of textile material, whether or  n...', chapter: '59', category: 'textiles', keywords: ['transmission', 'conveyor', 'belts', 'belting', 'textile', 'material', 'whether', 'impregrated', 'coated', 'covered'] },
  { code: '591110', description: 'Textile fabric, felt & felt-lined woven fabrics, coated/covered/laminated with rubber, leather or other material, for ca', chapter: '59', category: 'textiles', keywords: ['textile', 'fabric', 'felt', 'felt-lined', 'woven', 'fabrics', 'coated', 'laminated', 'rubber', 'leather', 'material', 'card', 'clothing', 'technical', 'purposes', 'impregnated', 'narrow', 'velvet', 'cover', 'weaving', 'spindles'] },
  { code: '591120', description: 'Textile products and articles for technical uses; bolting cloth, whether or not made up', chapter: '59', category: 'textiles', keywords: ['textile', 'technical', 'uses', 'bolting', 'cloth'] },
  { code: '591131', description: 'Textile products and articles, for technical uses, specified in Note 7 to thi...', chapter: '59', category: 'textiles', keywords: ['textile', 'products', 'technical', 'uses', 'specified', 'note', 'this', 'chaptertextile', 'fabrics', 'felts'] },
  { code: '591132', description: 'Textiles; fabrics and felts, endless or fitted with linking devices, of a kind used in paper-making or similar machines,', chapter: '59', category: 'textiles', keywords: ['textiles', 'fabrics', 'felts', 'endless', 'fitted', 'linking', 'devices', 'paper-making', 'machines', 'weighing', '650g'] },
  { code: '591140', description: 'Textile products and articles for technical uses; straining cloth of a kind used in oil presses and the like, including ', chapter: '59', category: 'textiles', keywords: ['textile', 'technical', 'uses', 'straining', 'cloth', 'oil', 'presses', 'human', 'hair'] },
  { code: '591190', description: 'Textile products and articles, for technical uses, specified in Note 7 to thi...', chapter: '59', category: 'textiles', keywords: ['textile', 'technical', 'uses'] },
];
