// Chapter 86: Railway -- 23 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_86: HsCodeEntry[] = [
  { code: '860110', description: 'Rail locomotives powered from an external source of electricity or by electri...', chapter: '86', category: 'vehicles', keywords: ['rail', 'locomotives', 'powered', 'external', 'source', 'electricity', 'electric', 'accumulatorspowered'] },
  { code: '860120', description: 'Rail locomotives powered from an external source of electricity or by electri...', chapter: '86', category: 'vehicles', keywords: ['rail', 'locomotives', 'powered', 'external', 'source', 'electricity', 'electric', 'accumulatorspowered', 'accumulators'] },
  { code: '860210', description: 'Other rail locomotives; locomotive tenders:Diesel-electric locomotives', chapter: '86', category: 'vehicles', keywords: ['rail', 'locomotives', 'locomotive', 'tendersdiesel', 'electric'] },
  { code: '860290', description: 'Other rail locomotives; locomotive tenders:Other', chapter: '86', category: 'vehicles', keywords: ['rail', 'locomotives', 'locomotive', 'tenders'] },
  { code: '860310', description: 'Self-propelled railway or tramway coaches, vans and trucks, other than those ...', chapter: '86', category: 'vehicles', keywords: ['self', 'propelled', 'railway', 'tramway', 'coaches', 'vans', 'trucks', 'those', 'heading', 'no'] },
  { code: '860390', description: 'Self-propelled railway or tramway coaches, vans and trucks, other than those ...', chapter: '86', category: 'vehicles', keywords: ['self', 'propelled', 'railway', 'tramway', 'coaches', 'vans', 'trucks', 'those', 'heading', 'no'] },
  { code: '860400', description: 'Railway or tramway maintenance or service vehicles, whether or not self-prope...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'maintenance', 'service', 'vehicles', 'self', 'propelled', 'example', 'workshops', 'cranes'] },
  { code: '860500', description: 'Railway or tramway passenger coaches, not self-propelled; luggage vans, post ...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'passenger', 'coaches', 'self', 'propelled', 'luggage', 'vans', 'post', 'office'] },
  { code: '860610', description: 'Railway or tramway goods vans and wagons, not self-propelled:Tank wagons and ...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'goods', 'vans', 'wagons', 'self', 'propelledtank', 'like'] },
  { code: '860630', description: 'Railway or tramway goods vans and wagons, not self-propelled:Self-discharging...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'goods', 'vans', 'wagons', 'self', 'propelledself', 'discharging', 'those', 'subheading'] },
  { code: '860691', description: 'Railway or tramway goods vans and wagons, not self-propelled:Other:*Covered a...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'goods', 'vans', 'wagons', 'self', 'propelledcovered', 'closedspecially', 'designed', 'transport'] },
  { code: '860692', description: 'Railway or tramway goods vans and wagons, not self-propelled:Other:*Open, wit...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'goods', 'vans', 'wagons', 'self', 'propelledopen', 'non', 'removable', 'sides'] },
  { code: '860699', description: 'Railway or tramway goods vans and wagons, not self-propelled:Other:*Other', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'goods', 'vans', 'wagons', 'self', 'propelled'] },
  { code: '860711', description: 'Parts of railway or tramway locomotives or rolling stock:Bogies, bissel-bogie...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockbogies', 'bissel', 'bogies', 'axles', 'wheels', 'driving'] },
  { code: '860712', description: 'Parts of railway or tramway locomotives or rolling stock:Bogies, bissel-bogie...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockbogies', 'bissel', 'bogies', 'axles', 'wheels'] },
  { code: '860719', description: 'Parts of railway or tramway locomotives or rolling stock:Bogies, bissel-bogie...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockbogies', 'bissel', 'bogies', 'axles', 'wheels', 'axles'] },
  { code: '860721', description: 'Parts of railway or tramway locomotives or rolling stock:Brakes and parts the...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockbrakes', 'air', 'brakes', 'of', 'cast', 'iron'] },
  { code: '860729', description: 'Parts of railway or tramway locomotives or rolling stock:Brakes and parts the...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockbrakes'] },
  { code: '860730', description: 'Parts of railway or tramway locomotives or rolling stock:Hooks and other coup...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockhooks', 'coupling', 'devices', 'buffers'] },
  { code: '860791', description: 'Parts of railway or tramway locomotives or rolling stock:Other:*Of locomotive...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockof', 'locomotivesaxle', 'boxes'] },
  { code: '860799', description: 'Parts of railway or tramway locomotives or rolling stock:Other:*Other:**Axle-...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockaxle', 'boxes'] },
  { code: '860800', description: 'Railway or tramway track fixtures and fittings; mechanical (including electro...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'track', 'fixtures', 'fittings', 'mechanical', 'electromechanical', 'signalling', 'safety', 'traffic'] },
  { code: '860900', description: 'Containers (including containers for the transport of fluids) specially desig...', chapter: '86', category: 'vehicles', keywords: ['containers', 'transport', 'fluids', 'specially', 'designed', 'equipped', 'carriage', 'modes', 'transportcontainers', 'anti'] },
];
