// Chapter 86: Railway -- 23 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_86: HsCodeEntry[] = [
  { code: '860110', description: 'Rail locomotives powered from an external source of electricity or by electri...', chapter: '86', category: 'vehicles', keywords: ['rail', 'locomotives', 'powered', 'from', 'external', 'source', 'electricity'] },
  { code: '860120', description: 'Rail locomotives powered from an external source of electricity or by electri...', chapter: '86', category: 'vehicles', keywords: ['rail', 'locomotives', 'powered', 'external', 'source', 'electricity', 'electric', 'accumulatorspowered', 'accumulators'] },
  { code: '860210', description: 'Other rail locomotives; locomotive tenders:Diesel-electric locomotives', chapter: '86', category: 'vehicles', keywords: ['rail', 'locomotives', 'diesel-electric', 'powered'] },
  { code: '860290', description: 'Other rail locomotives; locomotive tenders:Other', chapter: '86', category: 'vehicles', keywords: ['rail', 'locomotives', 'locomotive', 'tenders'] },
  { code: '860310', description: 'Railway or tramway coaches, vans and trucks; self-propelled, powered from an external source of electricity (excluding t', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'coaches', 'vans', 'trucks', 'self-propelled', 'powered', 'from', 'external', 'source', 'electricity'] },
  { code: '860390', description: 'Railway or tramway coaches, vans and trucks; self-propelled, powered other than from an external source of electricity (', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'coaches', 'vans', 'trucks', 'self-propelled', 'powered', 'from', 'external', 'source', 'electricity'] },
  { code: '860400', description: 'Railway or tramway maintenance or service vehicles; whether or not self-propelled (e.g. workshops, cranes, ballast tampe', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'maintenance', 'service', 'vehicles', 'self-propelled', 'e.g', 'workshops', 'cranes', 'ballast', 'tampers', 'trackliners', 'testing', 'coaches', 'track', 'inspection'] },
  { code: '860500', description: 'Railway or tramway coaches; passenger coaches, luggage vans, post office coaches and other special purpose railway or tr', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'coaches', 'passenger', 'luggage', 'vans', 'post', 'office', 'special', 'purpose', 'self-propelled'] },
  { code: '860610', description: 'Railway or tramway goods vans and wagons; tank wagons and the like, not self-propelled', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'vans', 'wagons', 'tank', 'self-propelled'] },
  { code: '860630', description: 'Railway or tramway goods vans and wagons, not self-propelled:Self-discharging...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'goods', 'vans', 'wagons', 'self', 'propelledself', 'discharging', 'those', 'subheading'] },
  { code: '860691', description: 'Railway or tramway goods vans and wagons, not self-propelled:Other:*Covered a...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'vans', 'wagons', 'closed', 'self-propelled'] },
  { code: '860692', description: 'Railway or tramway goods vans and wagons, not self-propelled:Other:*Open, wit...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'goods', 'vans', 'wagons', 'self', 'propelledopen', 'non', 'removable', 'sides'] },
  { code: '860699', description: 'Railway or tramway goods vans and wagons; n.e.c. in heading no. 8606, not self-propelled', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'vans', 'wagons', 'self-propelled'] },
  { code: '860711', description: 'Railway or tramway locomotives or rolling stock; parts, driving bogies and bissel-bogies', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stock', 'driving', 'bogies', 'bissel-bogies'] },
  { code: '860712', description: 'Parts of railway or tramway locomotives or rolling stock:Bogies, bissel-bogie...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockbogies', 'bissel', 'bogies', 'axles', 'wheels'] },
  { code: '860719', description: 'Railway or tramway locomotives or rolling stock; parts, axles and wheels, and parts thereof', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stock', 'axles', 'wheels'] },
  { code: '860721', description: 'Parts of railway or tramway locomotives or rolling stock:Brakes and parts the...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockbrakes', 'air', 'brakes', 'of', 'cast', 'iron'] },
  { code: '860729', description: 'Railway or tramway locomotives or rolling stock; parts, brakes (other than air brakes) and parts thereof', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stock', 'brakes', 'air'] },
  { code: '860730', description: 'Railway or tramway locomotives or rolling stock; parts, hooks and other coupling devices, buffers and parts thereof', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stock', 'hooks', 'coupling', 'devices', 'buffers'] },
  { code: '860791', description: 'Parts of railway or tramway locomotives or rolling stock:Other:*Of locomotive...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives'] },
  { code: '860799', description: 'Parts of railway or tramway locomotives or rolling stock:Other:*Other:**Axle-...', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'locomotives', 'rolling', 'stockaxle', 'boxes'] },
  { code: '860800', description: 'Railway or tramway track fixtures and fittings; mechanical (including electro-mechanical) signalling, safety or traffic ', chapter: '86', category: 'vehicles', keywords: ['railway', 'tramway', 'track', 'fixtures', 'fittings', 'mechanical', 'electro-mechanical', 'signalling', 'safety', 'traffic', 'control', 'equipment', 'railways', 'tramways', 'roads', 'inland', 'waterways', 'parking', 'facilities', 'port', 'installations', 'airfields'] },
  { code: '860900', description: 'Containers; (including containers for transport of fluids) specially designed and equipped for carriage by one or more m', chapter: '86', category: 'vehicles', keywords: ['containers', 'transport', 'fluids', 'specially', 'designed', 'equipped', 'carriage', 'one', 'modes'] },
];
