// Chapter 92: Musical Instruments -- 21 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_92: HsCodeEntry[] = [
  { code: '920110', description: 'Pianos, including automatic pianos; harpsichords and other keyboard stringed ...', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'pianos', 'upright', 'automatic'] },
  { code: '920120', description: 'Pianos, including automatic pianos; harpsichords and other keyboard stringed ...', chapter: '92', category: 'music', keywords: ['pianos', 'automatic', 'harpsichords', 'keyboard', 'stringed', 'instrumentsgrand'] },
  { code: '920190', description: 'Musical instruments; harpsichords and other keyboard stringed instruments n.e.c. in heading no. 9201', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'harpsichords', 'keyboard', 'stringed'] },
  { code: '920210', description: 'Musical instruments; string, played with a bow (e.g. violins)', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'string', 'played', 'bow', 'e.g', 'violins'] },
  { code: '920290', description: 'Musical instruments; string, played other than with a bow (e.g. guitars and harps)', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'string', 'played', 'bow', 'e.g', 'guitars', 'harps'] },
  { code: '920300', description: 'Acoustic stringed instruments', chapter: '92', category: 'music', keywords: ['guitar', 'acoustic guitar', 'bass guitar', 'violin', 'ukulele', 'banjo', 'harp', 'cello', 'mandolin'] },
  { code: '920400', description: 'Wind instruments', chapter: '92', category: 'music', keywords: ['trumpet', 'saxophone', 'flute', 'clarinet', 'trombone', 'harmonica', 'recorder'] },
  { code: '920500', description: 'Percussion instruments', chapter: '92', category: 'music', keywords: ['drum', 'drums', 'percussion', 'cymbals', 'xylophone', 'timpani', 'timpani'] },
  { code: '920510', description: 'Musical instruments; brass-wind (e.g. trumpets), other than fairground organs and mechanical street organs', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'brass-wind', 'e.g', 'trumpets', 'fairground', 'organs', 'mechanical', 'street'] },
  { code: '920590', description: 'Musical instruments; wind, other than brass, (eg. clarinet, bagpipes, pipe organs), other than fairground organs and mec', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'wind', 'brass', 'clarinet', 'bagpipes', 'pipe', 'organs', 'fairground', 'mechanical', 'street'] },
  { code: '920600', description: 'Musical instruments; percussion (e.g. drums, xylophones, cymbals, castanets, maracas)', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'percussion', 'e.g', 'drums', 'xylophones', 'cymbals', 'castanets', 'maracas'] },
  { code: '920710', description: 'Musical instruments; keyboard, (other than accordions), the sound of which is produced or must be amplified electrically', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'keyboard', 'accordions', 'sound', 'which', 'produced', 'must', 'amplified', 'electrically'] },
  { code: '920790', description: 'Musical instruments; (other than keyboard), the sound of which is produced or must be amplified electrically', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'keyboard', 'sound', 'which', 'produced', 'must', 'amplified', 'electrically'] },
  { code: '920810', description: 'Musical boxes, fairground organs, mechanical street organs, mechanical singin...', chapter: '92', category: 'music', keywords: ['musical', 'boxes'] },
  { code: '920890', description: 'Musical boxes, fairground organs, mechanical street organs, mechanical singin...', chapter: '92', category: 'music', keywords: ['musical', 'boxes', 'fairground', 'organs', 'mechanical', 'street', 'singing', 'birds', 'saws', 'instruments'] },
  { code: '920900', description: 'Music scores & parts', chapter: '92', category: 'books', keywords: ['sheet music', 'music score', 'chord chart', 'songbook'] },
  { code: '920930', description: 'Parts (for example, mechanisms for musical boxes) and accessories (for exampl...', chapter: '92', category: 'music', keywords: ['musical', 'instrument', 'strings'] },
  { code: '920991', description: 'Parts (for example, mechanisms for musical boxes) and accessories (for exampl...', chapter: '92', category: 'music', keywords: ['example', 'mechanisms', 'musical', 'boxes', 'accessories', 'cards', 'discs', 'rolls', 'mechanical', 'instruments'] },
  { code: '920992', description: 'Musical instruments; parts and accessories for string musical instruments other than keyboard instruments', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'string', 'keyboard'] },
  { code: '920994', description: 'Parts (for example, mechanisms for musical boxes) and accessories (for exampl...', chapter: '92', category: 'music', keywords: ['example', 'mechanisms', 'musical', 'boxes', 'accessories', 'cards', 'discs', 'rolls', 'mechanical', 'instruments'] },
  { code: '920999', description: 'Musical instruments; parts and accessories for musical instruments n.e.c. in heading no. 9209; metronomes, tuning forks ', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'metronomes', 'tuning', 'forks', 'pitch', 'pipes'] },
];
