// Chapter 92: Musical Instruments -- 21 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_92: HsCodeEntry[] = [
  { code: '920110', description: 'Pianos, including automatic pianos; harpsichords and other keyboard stringed ...', chapter: '92', category: 'music', keywords: ['pianos', 'automatic', 'harpsichords', 'keyboard', 'stringed', 'instrumentsupright', 'pianosnew'] },
  { code: '920120', description: 'Pianos, including automatic pianos; harpsichords and other keyboard stringed ...', chapter: '92', category: 'music', keywords: ['pianos', 'automatic', 'harpsichords', 'keyboard', 'stringed', 'instrumentsgrand'] },
  { code: '920190', description: 'Pianos, including automatic pianos; harpsichords and other keyboard stringed ...', chapter: '92', category: 'music', keywords: ['pianos', 'automatic', 'harpsichords', 'keyboard', 'stringed', 'instruments'] },
  { code: '920210', description: 'Pianos', chapter: '92', category: 'music', keywords: ['piano', 'digital piano', 'keyboard', 'music instrument', 'string', 'musical', 'instruments', 'example', 'guitars', 'violins'] },
  { code: '920290', description: 'Other string musical instruments (for example, guitars, violins, harps):Other...', chapter: '92', category: 'music', keywords: ['string', 'musical', 'instruments', 'example', 'guitars', 'violins', 'harps', 'guitars'] },
  { code: '920300', description: 'Acoustic stringed instruments', chapter: '92', category: 'music', keywords: ['guitar', 'acoustic guitar', 'bass guitar', 'violin', 'ukulele', 'banjo', 'harp', 'cello', 'mandolin'] },
  { code: '920400', description: 'Wind instruments', chapter: '92', category: 'music', keywords: ['trumpet', 'saxophone', 'flute', 'clarinet', 'trombone', 'harmonica', 'recorder'] },
  { code: '920500', description: 'Percussion instruments', chapter: '92', category: 'music', keywords: ['drum', 'drums', 'percussion', 'cymbals', 'xylophone', 'timpani', 'timpani'] },
  { code: '920510', description: 'Wind musical instruments (for example, keyboard, pipe organs, accordions, cla...', chapter: '92', category: 'music', keywords: ['wind', 'musical', 'instruments', 'example', 'keyboard', 'pipe', 'organs', 'accordions', 'clarinets', 'trumpets'] },
  { code: '920590', description: 'Wind musical instruments (for example, keyboard, pipe organs, accordions, cla...', chapter: '92', category: 'music', keywords: ['wind', 'musical', 'instruments', 'example', 'keyboard', 'pipe', 'organs', 'accordions', 'clarinets', 'trumpets'] },
  { code: '920600', description: 'Percussion musical instruments (for example, drums, xylophones, cymbals, cast...', chapter: '92', category: 'music', keywords: ['percussion', 'musical', 'instruments', 'example', 'drums', 'xylophones', 'cymbals', 'castanets', 'maracas'] },
  { code: '920710', description: 'Electric musical instruments', chapter: '92', category: 'music', keywords: ['electric guitar', 'electric bass', 'electric piano', 'synthesizer', 'electronic keyboard', 'electric violin', 'midi controller', 'electric organ'] },
  { code: '920790', description: 'Musical instruments, the sound of which is produced, or must be amplified, el...', chapter: '92', category: 'music', keywords: ['musical', 'instruments', 'sound', 'which', 'produced', 'must', 'amplified', 'electrically', 'example', 'organs'] },
  { code: '920810', description: 'Musical boxes, fairground organs, mechanical street organs, mechanical singin...', chapter: '92', category: 'music', keywords: ['musical', 'boxes', 'fairground', 'organs', 'mechanical', 'street', 'singing', 'birds', 'saws', 'instruments'] },
  { code: '920890', description: 'Musical boxes, fairground organs, mechanical street organs, mechanical singin...', chapter: '92', category: 'music', keywords: ['musical', 'boxes', 'fairground', 'organs', 'mechanical', 'street', 'singing', 'birds', 'saws', 'instruments'] },
  { code: '920900', description: 'Music scores & parts', chapter: '92', category: 'books', keywords: ['sheet music', 'music score', 'chord chart', 'songbook'] },
  { code: '920930', description: 'Parts (for example, mechanisms for musical boxes) and accessories (for exampl...', chapter: '92', category: 'music', keywords: ['example', 'mechanisms', 'musical', 'boxes', 'accessories', 'cards', 'discs', 'rolls', 'mechanical', 'instruments'] },
  { code: '920991', description: 'Parts (for example, mechanisms for musical boxes) and accessories (for exampl...', chapter: '92', category: 'music', keywords: ['example', 'mechanisms', 'musical', 'boxes', 'accessories', 'cards', 'discs', 'rolls', 'mechanical', 'instruments'] },
  { code: '920992', description: 'Parts (for example, mechanisms for musical boxes) and accessories (for exampl...', chapter: '92', category: 'music', keywords: ['example', 'mechanisms', 'musical', 'boxes', 'accessories', 'cards', 'discs', 'rolls', 'mechanical', 'instruments'] },
  { code: '920994', description: 'Parts (for example, mechanisms for musical boxes) and accessories (for exampl...', chapter: '92', category: 'music', keywords: ['example', 'mechanisms', 'musical', 'boxes', 'accessories', 'cards', 'discs', 'rolls', 'mechanical', 'instruments'] },
  { code: '920999', description: 'Parts (for example, mechanisms for musical boxes) and accessories (for exampl...', chapter: '92', category: 'music', keywords: ['example', 'mechanisms', 'musical', 'boxes', 'accessories', 'cards', 'discs', 'rolls', 'mechanical', 'instruments'] },
];
