// Chapter 93: Arms & Ammunition -- 20 codes
import type { HsCodeEntry } from '../types';

export const CHAPTER_93: HsCodeEntry[] = [
  { code: '930100', description: 'Guns', chapter: '93', category: 'industrial', keywords: ['firearm', 'shotgun', 'rifle', 'pistol', 'revolver'] },
  { code: '930110', description: 'Military weapons, other than revolvers, pistols and the arms of heading 9307:...', chapter: '93', category: 'arms', keywords: ['military', 'weapons', 'revolvers', 'pistols', 'arms', 'heading', '9307artillery', 'example', 'guns', 'howitzers'] },
  { code: '930120', description: 'Military weapons, other than revolvers, pistols and the arms of heading 9307:...', chapter: '93', category: 'arms', keywords: ['military', 'weapons', 'revolvers', 'pistols', 'arms', 'heading', '9307rocket', 'launchers', 'flame', 'throwers'] },
  { code: '930190', description: 'Military weapons, other than revolvers, pistols and the arms of heading 9307:...', chapter: '93', category: 'arms', keywords: ['military', 'weapons', 'revolvers', 'pistols', 'arms', 'heading', '9307'] },
  { code: '930200', description: 'Rifles & carbines', chapter: '93', category: 'industrial', keywords: ['rifle', 'carbine', 'hunting rifle', 'assault rifle', 'revolvers', 'pistols', 'those', 'heading', '9303', '9304'] },
  { code: '930300', description: 'Shotguns', chapter: '93', category: 'industrial', keywords: ['shotgun', 'hunting shotgun', 'sport shotgun'] },
  { code: '930310', description: 'Other firearms and similar devices which operate by the firing of an explosiv...', chapter: '93', category: 'arms', keywords: ['firearms', 'similar', 'devices', 'which', 'operate', 'firing', 'explosive', 'charge', 'example', 'sporting'] },
  { code: '930320', description: 'Other firearms and similar devices which operate by the firing of an explosiv...', chapter: '93', category: 'arms', keywords: ['firearms', 'similar', 'devices', 'which', 'operate', 'firing', 'explosive', 'charge', 'example', 'sporting'] },
  { code: '930330', description: 'Other firearms and similar devices which operate by the firing of an explosiv...', chapter: '93', category: 'arms', keywords: ['firearms', 'similar', 'devices', 'which', 'operate', 'firing', 'explosive', 'charge', 'example', 'sporting'] },
  { code: '930390', description: 'Other firearms and similar devices which operate by the firing of an explosiv...', chapter: '93', category: 'arms', keywords: ['firearms', 'similar', 'devices', 'which', 'operate', 'firing', 'explosive', 'charge', 'example', 'sporting'] },
  { code: '930400', description: 'Ammunition', chapter: '93', category: 'industrial', keywords: ['ammunition', 'bullets', 'shells', 'cartridges', 'arms', 'example', 'spring', 'air', 'gas', 'guns'] },
  { code: '930510', description: 'Parts and accessories of articles of headings 9301 to 9304:Of revolvers or pi...', chapter: '93', category: 'arms', keywords: ['accessories', 'headings', '9301', '9304of', 'revolvers', 'pistols857'] },
  { code: '930520', description: 'Parts and accessories of articles of headings 9301 to 9304:Of shotguns or rif...', chapter: '93', category: 'arms', keywords: ['accessories', 'headings', '9301', '9304of', 'shotguns', 'rifles', 'heading', '9303'] },
  { code: '930591', description: 'Parts and accessories of articles of headings 9301 to 9304:Other:*For militar...', chapter: '93', category: 'arms', keywords: ['accessories', 'headings', '9301', '9304for', 'military', 'weapons', 'falling', 'within', 'heading'] },
  { code: '930599', description: 'Parts and accessories of articles of headings 9301 to 9304:Other:*Other', chapter: '93', category: 'arms', keywords: ['accessories', 'headings', '9301', '9304'] },
  { code: '930621', description: 'Bombs, grenades, torpedoes, mines, missiles and similar munitions of war and ...', chapter: '93', category: 'arms', keywords: ['bombs', 'grenades', 'torpedoes', 'mines', 'missiles', 'similar', 'munitions', 'war', 'cartridges', 'ammunition'] },
  { code: '930629', description: 'Bombs, grenades, torpedoes, mines, missiles and similar munitions of war and ...', chapter: '93', category: 'arms', keywords: ['bombs', 'grenades', 'torpedoes', 'mines', 'missiles', 'similar', 'munitions', 'war', 'cartridges', 'ammunition'] },
  { code: '930630', description: 'Bombs, grenades, torpedoes, mines, missiles and similar munitions of war and ...', chapter: '93', category: 'arms', keywords: ['bombs', 'grenades', 'torpedoes', 'mines', 'missiles', 'similar', 'munitions', 'war', 'cartridges', 'ammunition'] },
  { code: '930690', description: 'Bombs, grenades, torpedoes, mines, missiles and similar munitions of war and ...', chapter: '93', category: 'arms', keywords: ['bombs', 'grenades', 'torpedoes', 'mines', 'missiles', 'similar', 'munitions', 'war', 'cartridges', 'ammunition'] },
  { code: '930700', description: 'Swords, cutlasses, bayonets, lances and similar arms and parts thereof and sc...', chapter: '93', category: 'arms', keywords: ['swords', 'cutlasses', 'bayonets', 'lances', 'similar', 'arms', 'scabbards', 'sheaths', 'therefor857'] },
];
